// GENERATED by dartvel add from path:vendor/slugify. Do not edit.
//
// The native carrier: what each operation does when the
// application runs on a device.
library;

import 'package:slugify/slugify.dart' as source;

String slugify(String text, {String separator = '-'}) =>
    source.slugify(text, separator: separator);
