// GENERATED by dartvel routes -- do not edit.
//
// Every file this project bundles, from pubspec.yaml. Pass one
// where an image, a video or a model is asked for:
// DVBox.image(DVAsset.logoSmall). A renamed file is then a
// compile error rather than a blank box on a device.
import 'package:dartvel_flutter/dartvel_flutter.dart';

enum DVAsset implements DVAssetRef {
  /// This project bundles no assets yet.
  none('', DVAssetKind.data);

  const DVAsset(this.path, this.kind);

  @override
  final String path;

  @override
  final DVAssetKind kind;
}
