// GENERATED – do not edit.
// Generated by dartvel 0.9.0
library dartvel_client;

// Core's own DV, for the server side, is in package:dartvel_core/dv.dart
// and not in this barrel: a page's DV is the application's.
//
// The cache's machinery stays out. dartvel.cache sets the store DV.Cache uses
// and the adapters switch store in code, through DV.Cache.withAdapter.
export 'package:dartvel_core/dartvel.dart'
    hide
        DVAtomicCacheAdapter,
        DVCacheAdapterRemove,
        DVCacheConfig,
        DVCacheConfigException,
        DVCacheStore,
        DVCacheTags,
        DVCountingCacheAdapter,
        DVMemcachedConnect,
        DVMemcachedConnection,
        DVMemcachedException,
        DVRedisClient,
        DVRedisConnect,
        DVRedisConnection,
        DVRedisException;
export 'package:dartvel_flutter/dartvel_flutter.dart';
export 'account.g.dart';
export 'assets.g.dart';
export 'config.g.dart';
export 'dartvel_config.g.dart';
export 'dartvel_runtime.dart';
export 'env.g.dart';
export 'ai_tools.g.dart';
export 'analytics.g.dart';
export 'asyncapi.g.dart';
export 'functions.g.dart';
export 'flags.g.dart';
export 'http.g.dart';
export 'jobs.g.dart';
export 'client_jobs.g.dart';
export 'models.g.dart';
export 'openapi.g.dart';
export 'platform_api.g.dart';
export 'policies.g.dart';
export 'privacy.g.dart';
export 'home_widgets.g.dart';
// The mounted modules and their pages as typed targets. Generated and never
// exported, so DV.Modules.<id>Routes was unreachable through the one import
// application code is told to use, and a link into a module had to be written
// out as a string -- which is the drift typed routes exist to prevent.
export 'modules.g.dart';
export 'router.g.dart';
export 'schedules.g.dart';
// The static-path manifest. It was generated and never exported, so the
// enumeration of a model's public pages was unreachable through the one
// import application code is told to use -- and unreachable to the build that
// has to know which pages to write.
export 'static_paths.g.dart';
export 'widgets.g.dart';
