// GENERATED BY DARTVEL - DO NOT EDIT
//
// Static paths for parameterized routes, discovered from
// @DVModel(generatePublicPages:) and
// @DVModel(publicPathsResolver:).

/// A route whose parameter values are enumerated at build
/// time.
class DVStaticPathsEntry {
  const DVStaticPathsEntry({
    required this.name,
    required this.route,
    required this.resolve,
  });

  /// The provider function name.
  final String name;

  /// The route these paths belong to, if declared.
  final String? route;

  /// Produces the parameter values to generate.
  final Future<List<String>> Function() resolve;
}

/// Every discovered static-path provider.
const List<DVStaticPathsEntry> dartvelStaticPaths = <DVStaticPathsEntry>[
];

/// Resolves every provider into the concrete paths to
/// generate, keyed by provider name.
///
/// A provider that throws is reported and skipped rather
/// than ending the resolution. They are independent: a
/// model whose pages need a database that is not reachable
/// at build time should not stop a resolver that reads a
/// file from producing its pages, and one exception
/// otherwise silently costs the site every generated page.
Future<Map<String, List<String>>> resolveDartvelStaticPaths({
  void Function(String provider, Object error)? onError,
}) async {
  final resolved = <String, List<String>>{};
  for (final entry in dartvelStaticPaths) {
    try {
      resolved[entry.name] = await entry.resolve();
    } on Object catch (error) {
      resolved[entry.name] = const <String>[];
      if (onError != null) onError(entry.name, error);
    }
  }
  return resolved;
}
