import 'package:flutter/material.dart';

import '../../dartvel_client/dartvel_client.dart';

@DVPage(
  title: 'Embed Dartvel in an existing native app',
  description: 'Add Dartvel to an existing native application across all Dartvel targets. '
      'dartvel build <target> --brownfield builds the native artifacts and generates '
      'typed host APIs.',
  showAppBar: false,
)
@pragma('vm:entry-point')
Widget _docsExistingNativeAppsPage(BuildContext context) => const DocsArticle(
      page: DVRoutes.docsexistingnativeapps,
      lead: <String>[
        'An organisation with an existing native app rarely rewrites it: it adds screens.',
        'Flutter solves add-to-app, and Dartvel extends it with `--brownfield` across all Dartvel targets.',
      ],
      sections: <DocsSection>[
        DocsSection(
          id: 'what-is-it',
          title: 'What it is',
          children: <Widget>[
            DocsText(
              'Brownfield integration allows an existing native host application to embed '
              'one or more Dartvel projects without a full rewrite. The same `dartvel build <target>` '
              'commands that build standalone apps produce the exact native artifact the host embeds '
              'when passed `--brownfield`.',
            ),
            DocsText(
              'There is no separate package or secondary CLI. The runtime support lives in '
              'the packages a Dartvel project already depends on, and the host\'s typed API is '
              'generated by the build and shipped inside the artifact (Kotlin, Swift, TypeScript, or C).',
            ),
            Bullets(<String>[
              'Android and iOS embed through Flutter\'s add-to-app engine architecture.',
              'Web hosts embed through multi-view custom elements that mount into the DOM.',
              'Desktop hosts (Linux, macOS, Windows) link shared libraries via embedder APIs.',
              'TV and embedded targets (Apple TV, Samsung Tizen, Sony eLinux, LG webOS) embed via native vendor embedders.',
              'Terminal and extension hosts embed via headless Dartvel modules and C interop.',
            ]),
          ],
        ),
        DocsSection(
          id: 'build-commands',
          title: 'Build commands and artifacts',
          children: <Widget>[
            DocsShell(<String>[
              'dartvel build android --brownfield            # an AAR for Gradle',
              'dartvel build ios --brownfield                # xcframeworks for Xcode',
              'dartvel build web --brownfield                # script & custom element',
              'dartvel build linux --brownfield              # shared library for host window',
              'dartvel build tizen --brownfield              # TPK / shared library for Samsung Smart TVs',
              'dartvel build sony-elinux --brownfield        # shared library for Sony eLinux devices',
              'dartvel build tvos --brownfield               # framework for Apple TV apps',
              'dartvel build android --brownfield --integrated',
            ]),
            Bullets(<String>[
              'Android produces an AAR package ready for Gradle dependency resolution.',
              'iOS and tvOS produce pre-built frameworks / xcframeworks for Xcode project linking.',
              'Web produces a lightweight bootstrap script and a custom HTML element.',
              'Desktop (Linux, macOS, Windows) produces a shared library and C/C++ header for native host windows.',
              'TV and embedded targets (Tizen, Sony eLinux, webOS) produce vendor embedder modules.',
            ]),
          ],
        ),
        DocsSection(
          id: 'modes',
          title: 'Isolated and integrated modes',
          children: <Widget>[
            DocsSubheading('Isolated mode (default)'),
            DocsText(
              'In isolated mode, each Dartvel project inside the host runs in its own Flutter '
              'engine with its own Dart isolate, router, signals, cache, and session. Nothing is '
              'shared with another project beyond declared host messages. A crash or memory leak in '
              'one screen cannot affect the host or other embedded modules.',
            ),
            DocsSubheading('Integrated mode (--integrated)'),
            DocsText(
              'Passing `--integrated` compiles multiple projects into one add-to-app module using '
              '`FlutterEngineGroup`. The engine group shares the Flutter framework machinery and Dart '
              'heap, allowing subsequent screens to start in megabytes rather than full engines. Projects '
              'still maintain strict state isolation.',
            ),
          ],
        ),
        DocsSection(
          id: 'multi-project',
          title: 'Multiple projects and federation',
          children: <Widget>[
            DocsText(
              'A native app embedding multiple distinct Dartvel projects (e.g. checkout, support chat, '
              'and a store locator) can merge them into a single module with an entrypoint per project. '
              '`dartvel build <target> --brownfield` verifies that all projects agree on Dartvel and Flutter versions.',
            ),
            DocsText(
              'When projects use different Flutter or Dartvel versions, they run federated side-by-side '
              'as separate modules. The build reports version discrepancies and calculates the memory savings '
              'of aligning them.',
            ),
          ],
        ),
        DocsSection(
          id: 'host-features',
          title: 'What the host gets',
          children: <Widget>[
            Bullets(<String>[
              'Typed route mounting: Mount a project or specific route from `DVRoutes` into a View, Fragment, ViewController, or DOM element.',
              'Bidirectional messaging: `@DVHostMessage` generates typed, versioned bindings over FFI and C interop, never platform channels.',
              'Coordinated back navigation: Android back and iOS swipe pop Dartvel routes first, delegating to the host when the stack is empty.',
              'Lifecycle & warm-up: Host lifecycle events propagate to project signals, with pre-warming support before display.',
              'Session hand-off: Hosts pass identity tokens via declared messages, verified server-side by Dartvel auth providers.',
            ]),
          ],
        ),
        DocsSection(
          id: 'diagnostics',
          title: 'Brownfield diagnostics',
          children: <Widget>[
            DocsTable(
              columns: <String>['Code', 'Reason', 'Level'],
              rows: <List<String>>[
                <String>[
                  'DV-BROWNFIELD-001',
                  'Two projects in one integrated module disagree on Dartvel or Flutter version',
                  'build error',
                ],
                <String>[
                  'DV-BROWNFIELD-002',
                  'A host message is declared on one side and not the other',
                  'build error',
                ],
                <String>[
                  'DV-BROWNFIELD-003',
                  'A target has no embedder API a host can start an engine through',
                  'build error',
                ],
              ],
            ),
          ],
        ),
      ],
    );
