package dev.dartvel.jni;

// GENERATED by dartvel build. Somewhere for a camera application to put a
// photo.
//
// androidx.core.content.FileProvider does this, and depending on it would
// mean editing the application's Gradle files to add a library that may or
// may not already be on the classpath. This serves one directory in the
// cache and needs nothing.
//
// A file:// URI would need none of this and has thrown
// FileUriExposedException since API 24.

import android.content.ContentProvider;
import android.content.ContentValues;
import android.content.Context;
import android.database.Cursor;
import android.database.MatrixCursor;
import android.net.Uri;
import android.os.ParcelFileDescriptor;
import android.provider.OpenableColumns;

import java.io.File;
import java.io.FileNotFoundException;

public final class DartvelCaptureFiles extends ContentProvider {
  /// The directory this provider serves, and the only one it will.
  static File directory(Context context) {
    return new File(context.getCacheDir(), "dartvel-capture");
  }

  /// The content:// URI for a file in that directory.
  public static Uri uriFor(Context context, File file) {
    return Uri.parse("content://" + context.getPackageName()
        + ".dartvelcapture/" + Uri.encode(file.getName()));
  }

  /// The file a URI names, or null when it names something outside the
  /// directory.
  ///
  /// The check is not decoration. The camera application is handed a grant
  /// on this provider, and a URI it built itself with ".." in the path would
  /// otherwise reach any file the application can open.
  private File resolve(Uri uri) {
    Context context = getContext();
    if (context == null) return null;
    String name = uri.getLastPathSegment();
    if (name == null || name.length() == 0) return null;
    if (name.contains("/") || name.contains("..")) return null;
    return new File(directory(context), name);
  }

  @Override
  public boolean onCreate() {
    return true;
  }

  @Override
  public ParcelFileDescriptor openFile(Uri uri, String mode)
      throws FileNotFoundException {
    File file = resolve(uri);
    if (file == null) throw new FileNotFoundException("not this provider's");
    // parseMode rather than flags of our own. A camera application opens
    // with "w", which means create and truncate as well as write, and a
    // hand-built READ_WRITE|CREATE would leave the tail of a previous photo
    // behind the new one in a file that is reused.
    int flags = ParcelFileDescriptor.MODE_READ_WRITE
        | ParcelFileDescriptor.MODE_CREATE;
    if (mode != null && mode.length() > 0) {
      flags = ParcelFileDescriptor.parseMode(mode);
    }
    return ParcelFileDescriptor.open(file, flags);
  }

  @Override
  public Cursor query(Uri uri, String[] projection, String selection,
      String[] selectionArgs, String sortOrder) {
    // Camera applications ask for the name and the size before writing.
    File file = resolve(uri);
    if (file == null) return null;
    MatrixCursor cursor = new MatrixCursor(new String[] {
      OpenableColumns.DISPLAY_NAME,
      OpenableColumns.SIZE,
    });
    cursor.addRow(new Object[] {file.getName(), Long.valueOf(file.length())});
    return cursor;
  }

  @Override
  public String getType(Uri uri) {
    return "image/jpeg";
  }

  @Override
  public Uri insert(Uri uri, ContentValues values) {
    return null;
  }

  @Override
  public int delete(Uri uri, String selection, String[] selectionArgs) {
    File file = resolve(uri);
    if (file == null || !file.exists()) return 0;
    return file.delete() ? 1 : 0;
  }

  @Override
  public int update(Uri uri, ContentValues values, String selection,
      String[] selectionArgs) {
    return 0;
  }
}
