package dev.dartvel.jni;

// GENERATED by dartvel build. The Activity plumbing behind the
// permission-gated platform bindings.
//
// Dart reaches every method here by name through JClass.forName, the same
// way it reaches DartvelContext. Renaming one, or changing its signature,
// is a lookup that fails on a device and nowhere else -- so the monorepo
// test test/unit/android_jni_signature_test.dart reads this source and the
// Dart that calls it and fails when they stop agreeing.
//
// Results are collected here and polled from Dart rather than pushed back
// over a callback. A callback into Dart from an arbitrary Android thread is
// the part of JNI most likely to be subtly wrong, and this needs none of it:
// the answer to "has the person finished with the camera" is a string that
// either exists yet or does not.

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.content.pm.PackageInfo;
import android.content.pm.PackageManager;
import android.database.Cursor;
import android.location.Location;
import android.location.LocationListener;
import android.location.LocationManager;
import android.os.Build;
import android.os.Bundle;
import android.os.Handler;
import android.os.Looper;
import android.provider.ContactsContract;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.json.JSONArray;
import org.json.JSONObject;

public final class DartvelActivityBridge {
  private DartvelActivityBridge() {}

  public static final String EXTRA_ID = "dev.dartvel.id";
  public static final String EXTRA_OP = "dev.dartvel.op";
  public static final String EXTRA_ARG = "dev.dartvel.arg";

  private static final Map<Integer, String> sResults =
      new HashMap<Integer, String>();
  private static int sNext = 1;

  /// Why nothing can be started, or null when something can.
  ///
  /// Separate from every operation's own errors so that "this APK was built
  /// with plain flutter build" reads differently from "the person said no".
  public static String state() {
    if (DartvelContext.context() == null) {
      return "Android has not created the Context provider yet";
    }
    return null;
  }

  /// What Android says about one of Dartvel's permission names, as JSON.
  ///
  /// Carries `declared` beside `granted` deliberately. Requesting a
  /// permission the manifest does not declare is refused immediately, with
  /// no dialog shown and the same result code a person tapping Deny
  /// produces. Without this key those two are the same answer, and the fix
  /// for one of them is a line in pubspec.yaml that nobody knows to add.
  public static String granted(String logical) {
    JSONObject out = new JSONObject();
    try {
      out.put("permission", logical);
      Context context = DartvelContext.context();
      if (context == null) {
        out.put("error", "there is no application Context yet");
        return out.toString();
      }
      String[] names = resolve(logical);
      if (names == null) {
        out.put("error", "Dartvel has no permission called " + logical);
        return out.toString();
      }
      JSONArray required = new JSONArray();
      boolean everyOneDeclared = true;
      boolean anyGranted = names.length == 0;
      boolean everyOneGranted = true;
      for (int i = 0; i < names.length; i++) {
        required.put(names[i]);
        if (!declared(context, names[i])) everyOneDeclared = false;
        if (held(context, names[i])) {
          anyGranted = true;
        } else {
          everyOneGranted = false;
        }
      }
      out.put("required", required);
      out.put("declared", names.length == 0 || everyOneDeclared);
      out.put("granted", anyOf(logical) ? anyGranted : everyOneGranted);
    } catch (Throwable error) {
      // Reported rather than thrown. A JNI call that throws leaves the
      // exception pending on the Dart side, where it surfaces later and
      // somewhere else.
      try {
        out.put("error", String.valueOf(error));
      } catch (Throwable ignored) {
        return "{}";
      }
    }
    return out.toString();
  }

  /// Starts [op] and returns the id its answer will arrive under.
  ///
  /// Negative means it never started: -1 for no Context, -2 for an operation
  /// this build does not have. Both are worth telling apart from an
  /// operation that started and was refused.
  public static int begin(String op, String argument) {
    Context context = DartvelContext.context();
    if (context == null) return -1;
    int id;
    synchronized (sResults) {
      id = sNext++;
    }
    String arg = argument == null ? "" : argument;
    if ("contacts".equals(op)) {
      startContacts(id, arg);
      return id;
    }
    if ("location".equals(op)) {
      startLocation(id, arg);
      return id;
    }
    if (!"permissions".equals(op) && !"camera".equals(op)
        && !"media".equals(op)) {
      return -2;
    }
    final Intent intent = new Intent(context, DartvelBridgeActivity.class);
    intent.putExtra(EXTRA_ID, id);
    intent.putExtra(EXTRA_OP, op);
    intent.putExtra(EXTRA_ARG, arg);
    final Activity activity = DartvelContext.activity();
    if (activity != null) {
      // From the Activity in front, so the transparent one joins the task
      // the person is already in. Started from the application Context it
      // would need FLAG_ACTIVITY_NEW_TASK and would appear as a second entry
      // in recents.
      //
      // On the main thread, because Dart calls this from the Flutter UI
      // thread and Activity methods are not promised to be safe anywhere
      // else.
      activity.runOnUiThread(new Runnable() {
        public void run() {
          activity.startActivity(intent);
        }
      });
    } else {
      intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
      context.startActivity(intent);
    }
    return id;
  }

  /// The answer to [id], once, or null while it has not arrived.
  ///
  /// Removed as it is read. Nothing asks twice, and a map that grew for the
  /// life of the process would hold every photo path an application ever
  /// captured.
  public static String poll(int id) {
    synchronized (sResults) {
      return sResults.remove(Integer.valueOf(id));
    }
  }

  static void complete(int id, String json) {
    synchronized (sResults) {
      sResults.put(Integer.valueOf(id), json);
    }
  }

  static void fail(int id, String reason) {
    JSONObject out = new JSONObject();
    try {
      out.put("error", reason);
    } catch (Throwable ignored) {
      complete(id, "{}");
      return;
    }
    complete(id, out.toString());
  }

  /// The Android permissions [logical] needs on this device, or null when
  /// Dartvel has no such name.
  ///
  /// Null and empty are different answers: empty means nothing has to be
  /// asked for, which is true of the clipboard, and null means the name is
  /// a typo. Answering "granted" to a typo is how an application ships
  /// believing it holds a permission it never asked for.
  static String[] resolve(String logical) {
    int sdk = Build.VERSION.SDK_INT;
    List<String> out = new ArrayList<String>();
    switch (logical) {
      case "camera":
        out.add("android.permission.CAMERA");
        break;
      case "microphone":
        out.add("android.permission.RECORD_AUDIO");
        break;
      case "location":
        out.add("android.permission.ACCESS_FINE_LOCATION");
        out.add("android.permission.ACCESS_COARSE_LOCATION");
        break;
      case "contacts":
        out.add("android.permission.READ_CONTACTS");
        break;
      case "notifications":
        if (sdk >= 33) out.add("android.permission.POST_NOTIFICATIONS");
        break;
      case "storage":
        if (sdk <= 32) out.add("android.permission.READ_EXTERNAL_STORAGE");
        break;
      case "photos":
        if (sdk >= 33) out.add("android.permission.READ_MEDIA_IMAGES");
        if (sdk <= 32) out.add("android.permission.READ_EXTERNAL_STORAGE");
        break;
      case "bluetooth":
        if (sdk >= 31) out.add("android.permission.BLUETOOTH_CONNECT");
        if (sdk >= 31) out.add("android.permission.BLUETOOTH_SCAN");
        if (sdk <= 30) out.add("android.permission.BLUETOOTH");
        if (sdk <= 30) out.add("android.permission.BLUETOOTH_ADMIN");
        break;
      case "nfc":
        out.add("android.permission.NFC");
        break;
      case "biometrics":
        out.add("android.permission.USE_BIOMETRIC");
        break;
      case "clipboard":
        break;
      case "files":
        break;
      default:
        return null;
    }
    return out.toArray(new String[out.size()]);
  }

  /// Whether holding one of the group is enough.
  static boolean anyOf(String logical) {
    return logical.equals("location")
        || logical.equals("photos");
  }

  /// Whether the manifest asks for [permission] at all.
  static boolean declared(Context context, String permission) {
    try {
      PackageManager packages = context.getPackageManager();
      PackageInfo info = packages.getPackageInfo(
          context.getPackageName(), PackageManager.GET_PERMISSIONS);
      String[] requested = info.requestedPermissions;
      if (requested == null) return false;
      for (int i = 0; i < requested.length; i++) {
        if (permission.equals(requested[i])) return true;
      }
      return false;
    } catch (Throwable error) {
      return false;
    }
  }

  /// Whether [permission] is held right now.
  static boolean held(Context context, String permission) {
    if (Build.VERSION.SDK_INT < 23) {
      // Before Marshmallow every declared permission is granted by
      // installing the application, and there is no runtime dialog to show.
      return declared(context, permission);
    }
    return context.checkSelfPermission(permission)
        == PackageManager.PERMISSION_GRANTED;
  }

  // --- contacts -----------------------------------------------------------

  /// The address book, on a thread of its own.
  ///
  /// Not on the caller's: Dart calls this from the Flutter UI thread, and a
  /// cursor over a few thousand contacts there is a frame budget spent on a
  /// database.
  private static void startContacts(final int id, final String argument) {
    new Thread(new Runnable() {
      public void run() {
        Context context = DartvelContext.context();
        if (context == null) {
          fail(id, "there is no application Context");
          return;
        }
        if (!held(context, "android.permission.READ_CONTACTS")) {
          fail(id, "READ_CONTACTS is not granted");
          return;
        }
        Cursor cursor = null;
        try {
          int limit = 0;
          try {
            limit = new JSONObject(argument).optInt("limit", 0);
          } catch (Throwable ignored) {
            limit = 0;
          }
          cursor = context.getContentResolver().query(
              ContactsContract.CommonDataKinds.Phone.CONTENT_URI,
              new String[] {
                ContactsContract.CommonDataKinds.Phone.CONTACT_ID,
                ContactsContract.CommonDataKinds.Phone.DISPLAY_NAME,
                ContactsContract.CommonDataKinds.Phone.NUMBER,
              },
              null,
              null,
              ContactsContract.CommonDataKinds.Phone.DISPLAY_NAME + " ASC");
          JSONArray people = new JSONArray();
          Set<String> seen = new LinkedHashSet<String>();
          if (cursor != null) {
            while (cursor.moveToNext()) {
              String contactId = cursor.getString(0);
              // One row per number, so a contact with a mobile and a work
              // number arrives twice. The first is kept; a list with the
              // same person in it three times is not an address book.
              if (contactId != null && !seen.add(contactId)) continue;
              JSONObject person = new JSONObject();
              person.put("id", contactId == null ? "" : contactId);
              person.put("name", nonNull(cursor.getString(1)));
              person.put("phone", nonNull(cursor.getString(2)));
              people.put(person);
              if (limit > 0 && people.length() >= limit) break;
            }
          }
          JSONObject out = new JSONObject();
          out.put("contacts", people);
          complete(id, out.toString());
        } catch (Throwable error) {
          fail(id, "the contacts query failed: " + error);
        } finally {
          if (cursor != null) cursor.close();
        }
      }
    }).start();
  }

  private static String nonNull(String value) {
    return value == null ? "" : value;
  }

  // --- location -----------------------------------------------------------

  /// Where the device is.
  ///
  /// The last known fix when there is a recent one, and a single update when
  /// there is not. Last-known alone is the usual shortcut and it is wrong
  /// often enough to matter: a phone that has not been asked for a position
  /// since it was last rebooted has none, and an API that answers zero
  /// there puts the person in the Gulf of Guinea.
  private static void startLocation(final int id, final String argument) {
    final Context context = DartvelContext.context();
    if (context == null) {
      fail(id, "there is no application Context");
      return;
    }
    int parsedAge = 120;
    int parsedTimeout = 20;
    try {
      JSONObject options = new JSONObject(argument);
      parsedAge = options.optInt("maxAgeSeconds", 120);
      parsedTimeout = options.optInt("timeoutSeconds", 20);
    } catch (Throwable ignored) {
      // The defaults above.
    }
    final int maxAgeSeconds = parsedAge;
    final int timeoutSeconds = parsedTimeout;
    final Handler handler = new Handler(Looper.getMainLooper());
    handler.post(new Runnable() {
      public void run() {
        if (!held(context, "android.permission.ACCESS_FINE_LOCATION")
            && !held(context, "android.permission.ACCESS_COARSE_LOCATION")) {
          fail(id, "neither location permission is granted");
          return;
        }
        LocationManager manager = (LocationManager)
            context.getSystemService(Context.LOCATION_SERVICE);
        if (manager == null) {
          fail(id, "this device has no location service");
          return;
        }
        Location best = null;
        List<String> providers = manager.getProviders(true);
        for (int i = 0; i < providers.size(); i++) {
          Location candidate = null;
          try {
            candidate = manager.getLastKnownLocation(providers.get(i));
          } catch (SecurityException error) {
            continue;
          }
          if (candidate == null) continue;
          if (best == null || candidate.getTime() > best.getTime()) {
            best = candidate;
          }
        }
        long age = best == null
            ? Long.MAX_VALUE
            : (System.currentTimeMillis() - best.getTime()) / 1000L;
        if (best != null && age <= maxAgeSeconds) {
          complete(id, describe(best, age));
          return;
        }
        if (providers.isEmpty()) {
          fail(id, "every location provider is turned off");
          return;
        }
        final Location stale = best;
        final LocationManager located = manager;
        final boolean[] answered = new boolean[] {false};
        final LocationListener[] listener = new LocationListener[1];
        listener[0] = new LocationListener() {
          public void onLocationChanged(Location location) {
            if (answered[0]) return;
            answered[0] = true;
            located.removeUpdates(listener[0]);
            complete(id, describe(location, 0));
          }

          public void onStatusChanged(String provider, int status,
              Bundle extras) {}

          public void onProviderEnabled(String provider) {}

          public void onProviderDisabled(String provider) {}
        };
        try {
          for (int i = 0; i < providers.size(); i++) {
            located.requestLocationUpdates(
                providers.get(i), 0L, 0f, listener[0], Looper.getMainLooper());
          }
        } catch (SecurityException error) {
          fail(id, "the location permission was revoked mid-request");
          return;
        }
        handler.postDelayed(new Runnable() {
          public void run() {
            if (answered[0]) return;
            answered[0] = true;
            located.removeUpdates(listener[0]);
            if (stale != null) {
              // Old, and said to be old. A stale fix is usually the right
              // answer indoors, and a caller that cares can look at the age
              // rather than be told nothing.
              complete(id, describe(stale,
                  (System.currentTimeMillis() - stale.getTime()) / 1000L));
              return;
            }
            fail(id, "no location arrived within " + timeoutSeconds
                + " seconds and the device has no earlier fix");
          }
        }, timeoutSeconds * 1000L);
      }
    });
  }

  private static String describe(Location location, long ageSeconds) {
    JSONObject out = new JSONObject();
    try {
      out.put("latitude", location.getLatitude());
      out.put("longitude", location.getLongitude());
      out.put("accuracy", location.hasAccuracy() ? location.getAccuracy() : -1);
      out.put("altitude", location.hasAltitude() ? location.getAltitude() : 0);
      out.put("provider", nonNull(location.getProvider()));
      out.put("ageSeconds", ageSeconds);
      out.put("timestamp", location.getTime());
    } catch (Throwable error) {
      return "{}";
    }
    return out.toString();
  }
}
