package dev.dartvel.jni;

// GENERATED by dartvel build. Holds the application Context so Dart can
// reach it over JNI.
//
// A ContentProvider because Android creates every declared provider before
// Application.onCreate returns, and hands it a Context. That is earlier than
// any Activity and earlier than the Flutter engine, so a binding registered
// during startup has something to bind to.

import android.app.Activity;
import android.app.Application;
import android.app.admin.DevicePolicyManager;
import android.content.ComponentName;
import android.content.ContentProvider;
import android.content.ContentValues;
import android.content.Context;
import android.database.Cursor;
import android.net.Uri;
import android.os.Bundle;

public final class DartvelContext extends ContentProvider {
  private static Context sContext;
  private static Activity sActivity;

  /// The application Context, or null before Android has created this.
  public static Context context() {
    return sContext;
  }

  /// The Activity that is currently resumed, or null when none is.
  ///
  /// Lock task is an Activity method, and Dartvel used to look for one by
  /// registering lifecycle callbacks from Dart once the bindings came up --
  /// which is after the engine, and therefore after the first Activity had
  /// already resumed. Those callbacks only report what happens from the
  /// moment they are registered, so onActivityResumed never fired and every
  /// kiosk enforcement reported that no Activity had resumed on a device
  /// where one plainly had. Registered here, they see the first one.
  public static Activity activity() {
    return sActivity;
  }

  /// Allowlists this application for lock task, or says why it could not.
  ///
  /// Here rather than in Dart because it is three Android calls and an array,
  /// and the array is the part Dart cannot express without knowing exactly
  /// how the JNI bindings model one. In Java it is String[].
  ///
  /// Null means allowlisted. Anything else is a reason worth showing: being
  /// the device owner is not enough for lock task, and startLockTask() on a
  /// package that is not allowlisted does not throw -- Android shows the pin
  /// dialog instead, to nobody, on a unit in a lobby.
  public static String allowLockTask() {
    Context context = sContext;
    if (context == null) {
      return "there is no application Context yet";
    }
    DevicePolicyManager policy = (DevicePolicyManager)
        context.getSystemService(Context.DEVICE_POLICY_SERVICE);
    if (policy == null) {
      return "this device has no device policy service";
    }
    String pkg = context.getPackageName();
    if (!policy.isDeviceOwnerApp(pkg)) {
      // Not a failure to enforce. This application gets screen pinning,
      // which is a weaker kiosk rather than none.
      return "this application is not the device owner, so lock task is "
          + "screen pinning rather than the silent kind";
    }
    try {
      policy.setLockTaskPackages(
          new ComponentName(pkg, pkg + ".DartvelDeviceAdminReceiver"),
          new String[] {pkg});
      return null;
    } catch (SecurityException error) {
      return "the device policy service refused the allowlist ("
          + error.getMessage() + ")";
    }
  }

  @Override
  public boolean onCreate() {
    Context context = getContext();
    // The application's, not the provider's. They are the same object on
    // every version anyone runs, but not by contract, and asking is one word.
    sContext = context == null ? null : context.getApplicationContext();
    if (sContext instanceof Application) {
      ((Application) sContext).registerActivityLifecycleCallbacks(
          new Application.ActivityLifecycleCallbacks() {
            @Override
            public void onActivityCreated(Activity a, Bundle b) {}

            @Override
            public void onActivityStarted(Activity a) {}

            @Override
            public void onActivityResumed(Activity a) {
              sActivity = a;
            }

            @Override
            public void onActivityPaused(Activity a) {
              // Only if it is still the one being held. Two activities
              // handing over run resume-then-pause, so forgetting on any
              // pause would drop the one that just arrived.
              if (sActivity == a) sActivity = null;
            }

            @Override
            public void onActivityStopped(Activity a) {}

            @Override
            public void onActivitySaveInstanceState(Activity a, Bundle b) {}

            @Override
            public void onActivityDestroyed(Activity a) {
              if (sActivity == a) sActivity = null;
            }
          });
    }
    return true;
  }

  // A ContentProvider is abstract and these are why. Nothing queries this
  // one -- it is not exported and has no data -- but it has to compile.

  @Override
  public Cursor query(Uri uri, String[] projection, String selection,
      String[] selectionArgs, String sortOrder) {
    return null;
  }

  @Override
  public String getType(Uri uri) {
    return null;
  }

  @Override
  public Uri insert(Uri uri, ContentValues values) {
    return null;
  }

  @Override
  public int delete(Uri uri, String selection, String[] selectionArgs) {
    return 0;
  }

  @Override
  public int update(Uri uri, ContentValues values, String selection,
      String[] selectionArgs) {
    return 0;
  }
}
