package dev.dartvel.jni;

// GENERATED by dartvel build. The Activity that receives
// onRequestPermissionsResult and onActivityResult.
//
// It exists because those two callbacks are delivered to an Activity and to
// nothing else, and because the application's MainActivity belongs to the
// developer. This one is transparent, is excluded from recents, does the one
// thing its Intent asked for, and finishes.

import android.app.Activity;
import android.content.ClipData;
import android.content.Intent;
import android.content.pm.PackageManager;
import android.database.Cursor;
import android.net.Uri;
import android.os.Build;
import android.os.Bundle;
import android.provider.MediaStore;
import android.provider.OpenableColumns;

import java.io.File;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.ArrayList;
import java.util.List;

import org.json.JSONArray;
import org.json.JSONObject;

public final class DartvelBridgeActivity extends Activity {
  private static final int PERMISSIONS = 4001;
  private static final int CAMERA = 4002;
  private static final int MEDIA = 4003;

  private int id = -1;
  private String[] asked = new String[0];
  private String logical = "";
  private File photo;

  @Override
  protected void onCreate(Bundle saved) {
    super.onCreate(saved);
    Intent intent = getIntent();
    id = intent.getIntExtra(DartvelActivityBridge.EXTRA_ID, -1);
    String op = intent.getStringExtra(DartvelActivityBridge.EXTRA_OP);
    String argument = intent.getStringExtra(DartvelActivityBridge.EXTRA_ARG);
    if (saved != null) {
      // Recreated after Android killed the process behind the camera. The
      // result map went with it, so there is nobody left to answer.
      finish();
      return;
    }
    try {
      if ("permissions".equals(op)) {
        startPermissions(argument);
      } else if ("camera".equals(op)) {
        startCamera();
      } else if ("media".equals(op)) {
        startMedia(argument);
      } else {
        answer(error("unknown operation " + op));
      }
    } catch (Throwable failure) {
      answer(error(String.valueOf(failure)));
    }
  }

  private void startPermissions(String argument) throws Exception {
    JSONObject options = new JSONObject(argument);
    logical = options.optString("permission", "");
    String[] names = DartvelActivityBridge.resolve(logical);
    if (names == null) {
      answer(error("Dartvel has no permission called " + logical));
      return;
    }
    List<String> missing = new ArrayList<String>();
    for (int i = 0; i < names.length; i++) {
      if (!DartvelActivityBridge.held(this, names[i])) {
        missing.add(names[i]);
      }
    }
    if (missing.isEmpty() || Build.VERSION.SDK_INT < 23) {
      // Nothing to ask for, or a device from before runtime permissions
      // existed. Either way the answer is what the manifest already got.
      answer(permissionResult(names));
      return;
    }
    asked = missing.toArray(new String[missing.size()]);
    requestPermissions(asked, PERMISSIONS);
  }

  @Override
  public void onRequestPermissionsResult(int request, String[] permissions,
      int[] results) {
    super.onRequestPermissionsResult(request, permissions, results);
    if (request != PERMISSIONS) return;
    answer(permissionResult(DartvelActivityBridge.resolve(logical)));
  }

  /// What the platform says now, rather than what the dialog returned.
  ///
  /// The result array is not the whole answer: a permission that was already
  /// held is not in it, and one refused permanently comes back denied with
  /// no dialog having been shown. Asking the package manager afterwards is
  /// one source for both.
  private String permissionResult(String[] names) {
    JSONObject out = new JSONObject();
    try {
      out.put("permission", logical);
      boolean everyOneDeclared = true;
      boolean anyGranted = names == null || names.length == 0;
      boolean everyOneGranted = true;
      boolean blocked = false;
      JSONArray required = new JSONArray();
      if (names != null) {
        for (int i = 0; i < names.length; i++) {
          required.put(names[i]);
          if (!DartvelActivityBridge.declared(this, names[i])) {
            everyOneDeclared = false;
          }
          if (DartvelActivityBridge.held(this, names[i])) {
            anyGranted = true;
          } else {
            everyOneGranted = false;
            // "Don't ask again", or a policy that forbids it. Android says
            // so by refusing to show a rationale for a permission that is
            // not held, and the difference decides whether an application
            // should ask again or send the person to Settings.
            if (Build.VERSION.SDK_INT >= 23
                && !shouldShowRequestPermissionRationale(names[i])) {
              blocked = true;
            }
          }
        }
      }
      out.put("required", required);
      out.put("declared", names == null || names.length == 0
          || everyOneDeclared);
      out.put("granted", DartvelActivityBridge.anyOf(logical)
          ? anyGranted : everyOneGranted);
      out.put("blocked", blocked && !everyOneGranted);
    } catch (Throwable failure) {
      return error(String.valueOf(failure));
    }
    return out.toString();
  }

  private void startCamera() {
    File directory = new File(getCacheDir(), "dartvel-capture");
    directory.mkdirs();
    photo = new File(directory,
        "capture-" + System.currentTimeMillis() + ".jpg");
    Uri target = DartvelCaptureFiles.uriFor(this, photo);
    Intent capture = new Intent(MediaStore.ACTION_IMAGE_CAPTURE);
    capture.putExtra(MediaStore.EXTRA_OUTPUT, target);
    // Without both grants the camera application is handed a URI it is not
    // allowed to open, and returns RESULT_CANCELED with no explanation --
    // which is indistinguishable from the person pressing back.
    capture.addFlags(Intent.FLAG_GRANT_WRITE_URI_PERMISSION);
    capture.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);
    if (capture.resolveActivity(getPackageManager()) == null) {
      answer(error("this device has no camera application"));
      return;
    }
    startActivityForResult(capture, CAMERA);
  }

  private void startMedia(String argument) throws Exception {
    JSONObject options = new JSONObject(argument);
    String kind = options.optString("type", "image");
    boolean multiple = options.optBoolean("multiple", false);
    // ACTION_OPEN_DOCUMENT rather than the gallery: it is the system picker,
    // it needs no permission at all, and what it returns is readable
    // whether the file is on the device or in a cloud provider.
    Intent pick = new Intent(Intent.ACTION_OPEN_DOCUMENT);
    pick.addCategory(Intent.CATEGORY_OPENABLE);
    if ("image".equals(kind)) {
      pick.setType("image/*");
    } else if ("video".equals(kind)) {
      pick.setType("video/*");
    } else if ("audio".equals(kind)) {
      pick.setType("audio/*");
    } else {
      pick.setType("*/*");
    }
    if (multiple) {
      pick.putExtra(Intent.EXTRA_ALLOW_MULTIPLE, true);
    }
    startActivityForResult(pick, MEDIA);
  }

  @Override
  protected void onActivityResult(int request, int result, Intent data) {
    super.onActivityResult(request, result, data);
    if (result != RESULT_OK) {
      // The person pressed back. Not an error, and not the same as a
      // failure: an empty list is what a cancelled picker means everywhere
      // else in Dartvel.
      answer(cancelled());
      return;
    }
    try {
      if (request == CAMERA) {
        answer(cameraResult());
      } else if (request == MEDIA) {
        answer(mediaResult(data));
      } else {
        answer(cancelled());
      }
    } catch (Throwable failure) {
      answer(error(String.valueOf(failure)));
    }
  }

  private String cameraResult() throws Exception {
    if (photo == null || !photo.exists() || photo.length() == 0) {
      // RESULT_OK and nothing written. Some camera applications answer this
      // way when they were handed a URI they could not open, and a caller
      // told "here is your photo" would read an empty file.
      return error("the camera reported success and wrote no file");
    }
    JSONObject item = new JSONObject();
    item.put("path", photo.getAbsolutePath());
    item.put("name", photo.getName());
    item.put("type", "image");
    item.put("bytes", photo.length());
    JSONArray items = new JSONArray();
    items.put(item);
    JSONObject out = new JSONObject();
    out.put("items", items);
    return out.toString();
  }

  private String mediaResult(Intent data) throws Exception {
    List<Uri> chosen = new ArrayList<Uri>();
    if (data != null) {
      ClipData clip = data.getClipData();
      if (clip != null) {
        for (int i = 0; i < clip.getItemCount(); i++) {
          Uri uri = clip.getItemAt(i).getUri();
          if (uri != null) chosen.add(uri);
        }
      } else if (data.getData() != null) {
        chosen.add(data.getData());
      }
    }
    if (chosen.isEmpty()) return cancelled();

    File directory = new File(getCacheDir(), "dartvel-picked");
    directory.mkdirs();
    JSONArray items = new JSONArray();
    for (int i = 0; i < chosen.size(); i++) {
      Uri uri = chosen.get(i);
      String name = displayName(uri);
      // Copied out rather than handed over as a content:// URI. Every
      // Dartvel media API answers with a path, and a URI in a field called
      // path is a string that opens nowhere.
      File file = new File(directory, System.currentTimeMillis() + "-" + name);
      copy(uri, file);
      JSONObject item = new JSONObject();
      item.put("path", file.getAbsolutePath());
      item.put("name", name);
      item.put("mimeType", nonNull(getContentResolver().getType(uri)));
      item.put("bytes", file.length());
      items.put(item);
    }
    JSONObject out = new JSONObject();
    out.put("items", items);
    return out.toString();
  }

  private void copy(Uri uri, File target) throws Exception {
    InputStream input = getContentResolver().openInputStream(uri);
    if (input == null) throw new IllegalStateException("could not open " + uri);
    OutputStream output = new FileOutputStream(target);
    try {
      byte[] buffer = new byte[8192];
      int read;
      while ((read = input.read(buffer)) > 0) {
        output.write(buffer, 0, read);
      }
      output.flush();
    } finally {
      try {
        input.close();
      } catch (Throwable ignored) {
        // Closing a stream that is already gone.
      }
      try {
        output.close();
      } catch (Throwable ignored) {
        // The same.
      }
    }
  }

  private String displayName(Uri uri) {
    Cursor cursor = null;
    try {
      cursor = getContentResolver().query(uri, null, null, null, null);
      if (cursor != null && cursor.moveToFirst()) {
        int column = cursor.getColumnIndex(OpenableColumns.DISPLAY_NAME);
        if (column >= 0) {
          String name = cursor.getString(column);
          if (name != null && name.length() > 0) return sanitise(name);
        }
      }
    } catch (Throwable ignored) {
      // A provider that answers no metadata. The fallback below is a name.
    } finally {
      if (cursor != null) cursor.close();
    }
    String last = uri.getLastPathSegment();
    return last == null ? "file" : sanitise(last);
  }

  /// A file name with nothing in it that can leave the directory.
  ///
  /// The name comes from whichever application answered the picker, so it is
  /// somebody else's string. A provider returning "../../databases/app.db"
  /// would otherwise have this copy a chosen file over the application's own
  /// data.
  private String sanitise(String name) {
    String out = name.replace("/", "_").replace("\\", "_");
    while (out.startsWith(".")) {
      out = out.substring(1);
    }
    if (out.length() == 0) return "file";
    return out.length() > 120 ? out.substring(out.length() - 120) : out;
  }

  private String cancelled() {
    JSONObject out = new JSONObject();
    try {
      out.put("cancelled", true);
      out.put("items", new JSONArray());
    } catch (Throwable ignored) {
      return "{}";
    }
    return out.toString();
  }

  private String error(String reason) {
    JSONObject out = new JSONObject();
    try {
      out.put("error", reason);
    } catch (Throwable ignored) {
      return "{}";
    }
    return out.toString();
  }

  private String nonNull(String value) {
    return value == null ? "" : value;
  }

  private void answer(String json) {
    if (id >= 0) DartvelActivityBridge.complete(id, json);
    finish();
    // No animation. This Activity is plumbing and a fade would look like the
    // application flickering.
    overridePendingTransition(0, 0);
  }
}
