import 'package:flutter/material.dart';
import '../dartvel_client/dartvel_client.dart';
import '../components/record.dart';
import '../components/site.dart';

/// Every section the repository records as Shipped, and nothing else.
///
/// The list follows docs/spec-status.json, and tool/site_features_check.dart
/// fails CI when the two disagree. Each body is a summary of that record in
/// a sentence or two; a section that names something missing says so after
/// "Absent:", and the card shows it.
///
/// Public because the page body is lowered into the generated router,
/// which reaches a page's public symbols through its import and cannot see
/// a private one at all.
const List<(String, String, String)> shipped = <(String, String, String)>[
  (
    'UI',
    'DVBox and DVText',
    'One layout primitive with a modifier chain. DVBox.list, .row, .grid and '
        '.wrapLine take collections, and DVBox(child) takes one child.',
  ),
  (
    'Pages',
    '@DVPage',
    'A private annotated function becomes a page. It can have a block body or '
        'an expression body.',
  ),
  (
    'Routing',
    'Files, lib/routes.dart, GoRouter',
    'File pages and lib/routes.dart share one typed router, with a stack per '
        'tab. Moving a page breaks the build at every link to it, and '
        'dartvelRoutes(at:) mounts the lot into your own GoRouter. Absent: typed '
        'targets for routes inside DVGoRoutes.',
  ),
  (
    'State',
    'Signals',
    'Signals from context.signal, reactive models and DV.global. The result '
        'of price * quantity is a signal that tracks both.',
  ),
  (
    'Models',
    '@DVModel',
    'One annotated class gives you the typed client, form, table and admin, '
        'regenerated by dartvel dev on save. Serialization comes with it.',
  ),
  (
    'Forms',
    'DVForm<T>',
    'Inputs, validation and error messages come from the model\'s fields.',
  ),
  (
    'Backend',
    '@DVBackendFunction',
    'A Dart function becomes an HTTP endpoint with a generated typed client.',
  ),
  (
    'Streaming Functions',
    'Server-sent events',
    'Return a Stream and the function is served as SSE, with a typed client '
        'that reads it.',
  ),
  (
    'Authorization',
    'DV.Auth.authorization',
    'Typed policies over models, functions and pages. A policy nobody '
        'registered answers no.',
  ),
  (
    'Authentication',
    'Passkeys, SAML, LDAP, Web3',
    'WebAuthn passkeys, SAML 2.0, LDAP and Sign-In with Ethereum. LDAP runs '
        'against a real server in CI. Absent: biometric sign-in.',
  ),
  (
    'Database',
    'SQLite by default',
    'Zero-config SQLite locally, plus Postgres and MySQL with TLS. Migrations '
        'run on SQLite with dartvel db migrate, which writes the SQL for the '
        'others.',
  ),
  (
    'APIs',
    'dartvel import openapi',
    'Import an OpenAPI spec or a Postman collection as models and typed '
        'functions.',
  ),
  (
    'Cache',
    'Distributed cache',
    'Keys spread across servers by rendezvous hashing. Adding a node moves '
        'only that node\'s share of keys.',
  ),
  (
    'SEO',
    'Head tags and a sitemap',
    'dartvel build web writes title, description, canonical and Open Graph '
        'tags. The sitemap leaves out guarded routes.',
  ),
  (
    'PWA',
    'Installable and offline',
    'dartvel build web writes the manifest, icons and service worker. A write '
        'made offline replays in order, tested in Chrome on every push.',
  ),
  (
    'Search',
    'Meilisearch, OpenSearch, Algolia',
    'Queries with highlights and facet counts. Meilisearch and OpenSearch run '
        'live in CI. Absent: a live Algolia test, since it has no local server.',
  ),
  (
    'Internationalization and Localization',
    'Typed keys, CLDR plurals',
    'Translation keys are typed and extracted to ARB. Plurals follow CLDR '
        'rules for each language.',
  ),
  (
    'Accessibility',
    'Audited at build time',
    'dartvel build web fails on a control with no name, an empty heading or a '
        'skipped heading level.',
  ),
  (
    'Dartvel Studio',
    'Visual page builder',
    'Drag and drop, an inspector, undo and export to an ordinary @DVPage. '
        'The workflow builder, Figma import, history and multi-user editing '
        'are in the paid Pro tier.',
  ),
  (
    'Admin, Devtools, and Scaffolding',
    'dartvel inspect, dartvel mcp',
    'One graph of your routes, models, functions and jobs. A coding agent '
        'reads it through dartvel mcp.',
  ),
  (
    'Deployment',
    'dartvel build web-server',
    'One file from dartvel build web-server runs your backend and web app on '
        'Linux, macOS or Windows, x64 or arm64. It creates its SQLite database '
        'on the first run, and dartvel deploy --functions writes an artifact per '
        'function. Absent: building for another OS, and deploying to a cloud '
        'with your credentials.',
  ),
  (
    'CSRF Protection',
    'On by default',
    'Every state-changing call to a generated function needs a CSRF token, '
        'and the generated client sends it.',
  ),
  (
    'Reversible Transactions',
    'DV.transaction',
    'context.afterCommit and context.compensate undo what ran when a later '
        'step fails.',
  ),
  (
    'Background and Durable Work',
    '@DVJob',
    'A backend function dispatches a generated job and answers at once. A '
        'worker runs it from your database, Redis, SQS, RabbitMQ, Pub/Sub or Kafka.',
  ),
  (
    'Static Web Generation',
    'dartvel build web',
    'One HTML page per route, with head tags, structured data and text a '
        'crawler can read.',
  ),
];

/// Partly built: what works, then what is missing after "Absent:". The
/// checker holds this list to the index's Partial sections exactly.
const List<(String, String, String)> partial = <(String, String, String)>[
  (
    'Module Sources',
    'dartvel add',
    'Present: the lockfile pins a foreign source and the graph reports it. '
        'Absent: the resolver, so nothing is generated.',
  ),
  (
    'Native Binding Graph',
    'Five binding kinds',
    'Present: the set is closed and checked. Absent: the five kinds '
        'themselves.',
  ),
  (
    'Styling',
    'Fluent modifiers',
    'Present: padding, corners, colour, type, shadows, blur and rotation on '
        'one DVModifier chain. Absent: hover, pressed, dark and breakpoint '
        'variants, and scale-valued padding and colour.',
  ),
  (
    'AI',
    'DV.AI',
    'Present: a local adapter, structured outputs, embeddings and provider '
        'extension points. Absent: tool approvals, searchable MCP tool '
        'catalogs and per-step agent middleware.',
  ),
  (
    'Testing',
    'dartvel test',
    'Present: fakes for auth, queues, mail, storage and AI, plus generated '
        'model factories. Absent: running only the tests a diff can reach, '
        'and scored AI evals.',
  ),
  (
    'Project Structure',
    'dartvel: in pubspec.yaml',
    'Present: default paths, per-key overrides and a Dart config file. '
        'Absent: glob patterns, so pages cannot live in two directories.',
  ),
  (
    'Record History and Optimistic Concurrency',
    'Versioned writes',
    'Present: a model saves at the version it read. A hand-built model cannot '
        'overwrite a stored row, and soft delete, restore and revert are '
        'generated. Absent: form reload-and-merge and the Studio history view.',
  ),
  (
    'Outbound HTTP',
    'DV.Http',
    'Present: declared hosts with timeouts, retries, a circuit breaker and a '
        'test fake, and an undeclared URL is refused. Absent: provider adapters '
        'built on it.',
  ),
  (
    'Scheduling',
    'Cron on client and server',
    'Present: declared schedules are registered and tick in a served backend '
        'and in the app. Absent: a per-target report of how often each can run.',
  ),
  (
    'Middleware',
    '@DVUseMiddleware',
    'Present: ten built-in middlewares run in the order you declare. Absent: '
        'page middleware that preloads data or sets SEO context.',
  ),
  (
    'Edge Security',
    'GraphQL limits and WAF rules',
    'Present: GraphQL depth and cost budgets on by default, and persisted '
        'queries. Absent: generated clients that send query hashes.',
  ),
  (
    'Sessions and Account Management',
    'Sessions, MFA, recovery codes',
    'Present: hashed session tokens, TOTP second factors and sign-in endpoints. '
        'Absent: passkeys as a second factor.',
  ),
  (
    'Theme',
    'DV.Theme.mode',
    'Present: light, dark and system switching. Absent: design tokens, fonts '
        'from config and Figma variable import.',
  ),
  (
    'Platform',
    'DV.Platform',
    'Present: native bindings through FFI and jnigen, 63 on Linux and 36 on '
        'Android. Absent: most bindings on iOS, which has 7.',
  ),
  (
    'Storage-Neutral Records',
    'One data layer, any engine',
    'Present: records, filters and versioned writes that compile to SQL, with '
        'Studio and its stores already on them. Absent: models and the other '
        'framework stores, and the MongoDB engine itself.',
  ),
  (
    'Schema Evolution',
    'Online migrations',
    'Present: a planner that classifies blocking changes per database version '
        'and runs resumable backfills. Absent: MongoDB, which is planned as the '
        'first document database.',
  ),
  (
    'Platform API: Keys, Scopes and OAuth Provider',
    'API keys and OAuth',
    'Present: scoped API keys and an OAuth provider with PKCE. Absent: a '
        'generated ApiKey model.',
  ),
  (
    'Outbound Webhooks',
    'DVWebhooks',
    'Present: signed deliveries that survive a restart and refuse private '
        'addresses. Absent: generated subscriptions and model events.',
  ),
  (
    'Model Sync and Presence',
    'Built on models and signals',
    'Present: generated change streams, watch and presence inside one '
        'process. Absent: a transport that carries changes between servers '
        'and devices.',
  ),
  (
    'Offline-First Models',
    'DVOfflineStore',
    'Present: a local store with an ordered mutation log that replays on '
        'reconnect. Absent: @DVModel(offline:) and an IndexedDB store on web.',
  ),
  (
    'Mail and Notifications',
    'DV.Notifications.mail',
    'Present: email, in-app, push and web push. SMTP is tested against a real '
        'server. Absent: a test against a real APNS or push service.',
  ),
  (
    'Media Pipeline',
    'Image variants',
    'Present: resized image variants for web builds. Absent: uploads, AVIF and '
        'video.',
  ),
  (
    'Media Playback and Capture',
    'DVBox.video',
    'Present: player and capture state as signals, with Linux audio. Absent: '
        'playback backends for Android, iOS, macOS, Windows and web.',
  ),
  (
    'Multi-tenancy',
    'tenantScoped: true',
    'Present: tenant resolution, filtered reads and writes on generated '
        'models, and jobs that run as their tenant. Absent: '
        'creating the per-tenant schemas and databases.',
  ),
  (
    'Feature Flags and Staged Rollout',
    'DVFlags',
    'Present: typed flags with percentage rollout and targeting. Absent: '
        'publishing flag rules per environment.',
  ),
  (
    'OTA Updates',
    'DV.Updates',
    'Present: DV.Updates.check, apply and rollback run on the Shorebird '
        'updater. Patches publish into your own web-server binary with dartvel '
        'updates patch --patch-source, and CI patches an Android release that '
        'way with no Shorebird account. Absent: iOS.',
  ),
  (
    'Protocol Versioning and Client Compatibility',
    'dartvel.protocol.lock',
    'Present: a protocol lockfile and a handshake that refuses clients outside '
        'the window. Absent: generated clients that send the protocol header.',
  ),
  (
    'AI Operations',
    'Versioned prompts',
    'Present: fingerprinted prompts, a prompt lockfile, budgets and evals. '
        'Absent: a generator for @DVPrompt, so prompts are registered by hand.',
  ),
  (
    'Monitoring and Observability',
    'GET /metrics, GET /health',
    'Present: Prometheus metrics and health checks on every server. Absent: '
        'a log sink, so nothing an app logs goes anywhere.',
  ),
  (
    'Distributed Tracing',
    'W3C Trace Context',
    'Present: trace context across requests, with consistent sampling. '
        'Absent: an OTLP exporter, so no span reaches a collector.',
  ),
  (
    'Crash Reporting and Release Health',
    'DV.Crashes',
    'Present: Dart and web errors recorded and sent on the next launch. '
        'Absent: native crash handlers on JVM, iOS and Windows.',
  ),
  (
    'Alerting, SLOs and Status Pages',
    'DVServiceLevel, DVAlerting',
    'Present: error budgets, burn-rate alerts and PagerDuty delivery. Absent: '
        'incidents as a generated model.',
  ),
  (
    'Product Analytics and Consent',
    'DVAnalytics, DVConsent',
    'Present: typed events that drop what consent denies. Absent: generated '
        'page-view and model events.',
  ),
  (
    'Semantic Search and Embeddings',
    'Model.semanticSearch',
    'Present: keyword, semantic and hybrid search with tenant filtering, on '
        'the data model. Absent: a pgvector or hosted vector adapter.',
  ),
  (
    'Billing',
    'Stripe and Paddle',
    'Present: checkout and signed webhooks for Stripe and Paddle. Absent: a '
        'test against either live service.',
  ),
  (
    'Purchases and Entitlements',
    'DVPurchases',
    'Present: server-side receipt checks and a grants ledger. Absent: real App '
        'Store and Play adapters.',
  ),
  (
    'Usage Metering and Quotas',
    'DVMeters',
    'Present: per-tenant counters, limits and billing reports. Absent: the '
        '@DVMeter annotation and generated accessors.',
  ),
  (
    'Commerce: Tax, Promotions, Disputes and Payouts',
    'DVTax, promotions',
    'Present: tax, promotion, dispute and payout rules, tested against fakes. '
        'Absent: a test against a live provider.',
  ),
  (
    'Desktop, Embedded, and Qt-Critical Capabilities',
    'Tray, menus, drag and drop',
    'Present: tray, menus, shortcuts and drag and drop on Linux, Windows and '
        'macOS. Absent: images and HTML on the clipboard.',
  ),
  (
    'Platform Memory',
    'DV.Memory',
    'Present: preallocated memory arenas shared across isolates. Absent: a test in a '
        'real browser.',
  ),
  (
    'Compute: Workers and Native Offload',
    'DV.Workers',
    'Present: a bounded isolate pool on native and web workers on web. '
        'Absent: a build-time check for captures a worker cannot send.',
  ),
  (
    'Kiosk Mode',
    'DVKiosk',
    'Present: kiosk policy and native enforcement on Android, Linux, Windows, '
        'macOS and web. Absent: enforcement on iPadOS, Tizen and webOS.',
  ),
  (
    'Terminal Rendering',
    'dartvel build linux-cli',
    'Present: terminal size as a signal and launch negotiation. Absent: the '
        'renderer and a distributable runner.',
  ),
  (
    '3D Scenes',
    'DVBox.scene',
    'Present: a scene document, scene graph and ray picking. Absent: a GPU '
        'renderer, so every target shows the poster.',
  ),
  (
    'XR: Spatial Presentation',
    'Volumes and immersive spaces',
    'Present: spatial window kinds, anchors and a session driven by the '
        'device. Absent: a WebGL2 renderer.',
  ),
  (
    'Multi-Window',
    'DVWindows',
    'Present: display lists on all three desktops, single-instance launch and '
        'workspace restore. Absent: tear-out.',
  ),
  (
    'Tab Workspaces',
    'DVTab',
    'Present: tab strips with reorder, persistence and a TV switcher. Absent: '
        'dragging a tab between real OS windows.',
  ),
  (
    'Content Workflow',
    'DVContentWorkflow',
    'Present: draft, review, approve and publish with an audit trail. Absent: '
        'theme and translation content in the workflow.',
  ),
  (
    'Data Import, Export, and Reporting',
    'Order.importCsv',
    'Present: CSV, NDJSON and tab-separated import, CSV, JSON, NDJSON and '
        'Excel export, and monthly reports, per model. Absent: PDF export.',
  ),
  (
    'Change Data Capture and Warehouse Sync',
    'DVCapture',
    'Present: an ordered change log with checkpoints for consumers. Absent: '
        '@DVModel(capture: true).',
  ),
  (
    'Secrets and Environments',
    'dartvel key',
    'Present: the app key in the Keychain, DPAPI, Secret Service and WebCrypto. '
        'Absent: Vault and KMS adapters.',
  ),
  (
    'Server Provisioning',
    'dartvel infra',
    'Present: a server rendered from pubspec.yaml into systemd units, Caddy '
        'and a firewall. Absent: fixing package drift, which it only reports.',
  ),
  (
    'Backend Release Management',
    'Canary and blue-green',
    'Present: release gates that roll back on a regression. Absent: dartvel ci '
        'init.',
  ),
  (
    'Preview Environments',
    'dartvel.preview',
    'Present: per-branch preview identities and secret checks. Absent: an '
        'adapter that hosts a preview.',
  ),
  (
    'Dev Client',
    'dartvel dev',
    'Present: Android, iOS, macOS, Linux and Windows development builds pair '
        'over TLS and hot reload on every save. Absent: connecting to a preview '
        'environment, and embedded and TV development builds.',
  ),
  (
    'CLI',
    'One tool',
    'Present: create, dev, build, deploy, updates, admin, key and '
        'more, with generation inside dev and build. Absent: the crashes and '
        'meters commands, deploy --plan and deploy rollback.',
  ),
  (
    'Package Structure',
    'dartvel_dev',
    'Present: the barrels under dartvel_dev. Absent: the Rust bindings '
        'beyond one integer type. DVRust and DVRustInt are types you '
        'construct; DV has no Rust member.',
  ),
  (
    'Home Widgets',
    '@DVHomeWidget',
    'Present: generated widget pages packaged for Android and WidgetKit. '
        'Absent: a check that the Swift compiles in Xcode.',
  ),
  (
    'The Golden Path',
    'create to deploy',
    'Present: create, dev, generate, db migrate, test, build, deploy and '
        'upgrade --plan. Absent: applying an upgrade, so you make the changes '
        'the plan lists.',
  ),
  (
    'Adoption',
    'dartvel init',
    'Present: dartvel init adds Dartvel to an existing Flutter project and '
        'changes nothing else. Absent: Riverpod and stream bridges, and Firebase '
        'or Supabase auth adapters.',
  ),
  (
    'Lifecycle Signals',
    'DV.lifecycle',
    'Present: app, build, page, request, transaction and kiosk signals. '
        'Absent: loading and route-transition states.',
  ),
  (
    'Backend Function Request Lifecycle',
    'context.lifecycle.request',
    'Present: DVContext injected first, and the stage as a read-only signal. '
        'Absent: most stages between received and response, and the '
        'transaction, authentication, rateLimit and rawPath options.',
  ),
  (
    'Modules',
    'DV.Modules',
    'Present: a module is a whole Dartvel app mounted under a path. Absent: '
        'an exports block that limits which models a parent may use.',
  ),
  (
    'Module Distribution and Trust',
    'dartvel.module.lock',
    'Present: signed module packages pinned by digest and key. Absent: '
        'checking a module\'s network and secret access while it runs.',
  ),
  (
    'Queues, Jobs, and Signals',
    'DV.Jobs and DV.Queues',
    'Present: seven queue adapters, from in-memory to Kafka, tested against '
        'real brokers in CI. Absent: delayed jobs, a backoff schedule and '
        'uniqueness keys.',
  ),
  (
    'File Storage',
    'S3, Azure Blob, GCS',
    'Present: one storage API over three object stores, run against Azurite '
        'and fake-gcs-server in CI. Absent: a local disk adapter and streams.',
  ),
  (
    'Generated Model Pages',
    'Model.Page(...)',
    'Present: public pages per model with .async, .signal and .fromId. '
        'Absent: resized favicons on server-rendered pages.',
  ),
  (
    'Error, Empty, and Loading States',
    'page.loading.dart',
    'Present: loading and error companions for each page. Absent: '
        'page-level error boundaries and generated status pages.',
  ),
  (
    'Sensitive Model Fields',
    '@DVModel.sensitiveField()',
    'Present: kept out of logs, search and the admin, and encrypted: true '
        'seals the field. Absent: re-encrypting rows when a key rotates.',
  ),
  (
    'Data Compliance and Lifecycle',
    'DVPrivacy',
    'Present: erasure, export and retention sweeps with signed receipts. '
        'Absent: retention schedules set per deployment.',
  ),
  (
    'Web Server Rendering',
    'dartvel build web-server',
    'Present: pages rendered on request from model data, with head tags and '
        'streaming. Absent: Flutter widgets rendered to HTML.',
  ),
  (
    'Embedded, Television, and Extension Build Targets',
    'Tizen, webOS, eLinux',
    'Present: Tizen, VS Code and Sony eLinux release builds. Absent: dartvel '
        'build webos, whose embedder ships Dart 3.10.9, and Fuchsia.',
  ),
  (
    'Unified Development, Transparency, and Contracts',
    'dartvel inspect, dartvel explain',
    'Present: inspectors for routes, models, functions and jobs. Absent: '
        'module, transaction and schema inspectors.',
  ),
  (
    'Generated Code Determinism',
    'dartvel generate --check',
    'Present: identical inputs give byte-identical output. Absent: dart format '
        'on generated files.',
  ),
  (
    'Documentation Generation',
    'dartvel docs',
    'Present: a static docs site built from your project graph. Absent: running it '
        'as part of build or dev.',
  ),
  (
    'App Store Deployment and Privacy Manifests',
    'dartvel deploy --store',
    'Present: dartvel deploy --store uploads an App Bundle to Play or an IPA to App '
        'Store Connect. Absent: generated privacy manifests.',
  ),
  (
    'Dartvel Cloud',
    'dartvel build ios --cloud',
    'Present: the --cloud options on build, deploy and key. Absent: the '
        'hosted machines that run cloud builds.',
  ),
];

@DVPage(
  title: 'Dartvel features: what ships and what is partial',
  description: 'What ships in Dartvel today and what is partial, section by '
      'section, with the evidence behind each status.',
  showAppBar: false,
  sitemap: DVPageSitemap(
    priority: 0.8,
    changeFrequency: DVSitemapChangeFrequency.weekly,
  ),
)
@pragma('vm:entry-point')
Widget _featuresPage(BuildContext context) => const SingleChildScrollView(
  child: DVBox.list(<Widget>[
    Section(
      children: <Widget>[
        Eyebrow('WHAT WORKS TODAY'),
        Heading('Twenty-five shipped sections.', level: 1),
        Bullets(<String>[
          'Seventy-seven more are partial, and each card says what is missing.',
          'Every card summarises an entry in docs/spec-status.json, and CI '
              'fails when they disagree.',
        ]),
        ExternalLink('Read spec-status.json', kSpecStatusUrl),
      ],
    ),
    Section(
      tint: true,
      children: <Widget>[
        Eyebrow('SHIPPED'),
        Heading('Shipped, each backed by tests in the repo.', level: 2),
        FeatureGrid(items: shipped),
      ],
    ),
    Section(
      children: <Widget>[
        Eyebrow('PARTIAL'),
        Heading('Partly built, with the gap named.', level: 2),
        FeatureGrid(items: partial),
      ],
    ),
    Section(
      tint: true,
      children: <Widget>[
        Eyebrow('START'),
        Heading('Try the shipped parts in a new app.'),
        Objection(
          'Can I rely on a partial section?',
          'Only on the part its card lists as working. Read its entry in '
              'spec-status.json first.',
        ),
        DVBox.wrapLine(<Widget>[PrimaryLink('Create your first app', '/docs')]),
      ],
    ),
    SiteFooter(),
  ], spacing: 0),
);

/// A grid where there is room, one column where there is not.
@DVFunctionalWidget()
Widget _featureGrid(
  BuildContext context, {
  required List<(String, String, String)> items,
}) =>
    LayoutBuilder(
      builder: (BuildContext context, BoxConstraints constraints) {
        final int columns = constraints.maxWidth >= 900 ? 2 : 1;
        if (columns == 1) {
          return DVBox.list(<Widget>[
            for (final (String area, String surface, String body) f in items)
              FeatureRow(area: f.$1, surface: f.$2, body: f.$3),
          ], spacing: 14);
        }
        const double gap = 18;
        final double width =
            (constraints.maxWidth - gap * (columns - 1)) / columns;
        return Wrap(
          spacing: gap,
          runSpacing: gap,
          children: <Widget>[
            for (final (String area, String surface, String body) f in items)
              SizedBox(
                width: width,
                child: FeatureRow(area: f.$1, surface: f.$2, body: f.$3),
              ),
          ],
        );
      },
    );

/// One capability: the area, the surface you actually type, what works and,
/// when the record names one, what is missing.
@DVFunctionalWidget()
Widget _featureRow(
  BuildContext context, {
  required String area,
  required String surface,
  required String body,
}) {
  final Palette palette = Palette.of(context);
  final String gap = siteGap(body);
  return DVBox(
    DVBox.list(<Widget>[
      // A wrapping line: the chip carries an API name and some are long.
      DVBox.wrapLine(<Widget>[
        DVText(area).modifier(
          const DVModifier()
              .fontSize(17)
              .fontWeight(FontWeight.w700)
              .color(palette.ink)
              .semanticHeading(3),
        ),
        SiteChip(surface),
      ], spacing: 10),
      // One sentence. Three lines at most, so one long opening cannot make
      // its card taller than the row it sits in.
      DVText(siteLead(body)).modifier(
        const DVModifier()
            .fontSize(15)
            .color(palette.muted)
            .lineHeight(1.6)
            .maxLines(3)
            .overflow(TextOverflow.ellipsis),
      ),
      if (gap.isNotEmpty)
        DVBox.list(<Widget>[
          const DVText('Missing').modifier(const DVModifier()
              .fontSize(12)
              .fontWeight(FontWeight.w700)
              .letterSpacing(0.8)
              .color(palette.faint)),
          DVText(gap).modifier(
            const DVModifier()
                .fontSize(15)
                .color(palette.muted)
                .lineHeight(1.6)
                .maxLines(3)
                .overflow(TextOverflow.ellipsis),
          ),
        ], spacing: 4, crossAlign: DVCrossAlign.start),
    ], spacing: 10),
    const DVModifier()
        // No height: a wrap gives its children unbounded height.
        .paddingOnly(left: 20, top: 18, right: 20, bottom: 20)
        .backgroundColor(palette.page)
        .rounded(12)
        .border(Border.all(color: palette.rule)),
  );
}
