// What `dartvel build android` adds for media: ExoPlayer, the media session
// and its foreground service, picture-in-picture and CameraX -- only for an
// application whose code uses them.
//
// The silent failures: a torch application shipping two megabytes of video
// player because the framework could; a second build adding a second copy
// of the service, which Android refuses to install; a player that streams a
// URL from an application whose release manifest has no INTERNET line and so
// fails only in release; and a camera box whose permission request is
// refused without a dialog because nothing declared CAMERA.
import 'package:dartvel_cli/src/build/android_media_bridge.dart';
import 'package:test/test.dart';

const String _manifest = '''
<manifest xmlns:android="http://schemas.android.com/apk/res/android">
    <application
        android:label="example"
        android:name="\${applicationName}">
        <activity
            android:name=".MainActivity"
            android:exported="true"
            android:launchMode="singleTop">
        </activity>
    </application>
</manifest>
''';

const String _gradleKts = '''
plugins {
    id("com.android.application")
    id("dev.flutter.flutter-gradle-plugin")
}

android {
    namespace = "com.example.app"
}

flutter {
    source = "../.."
}
''';

void main() {
  group('what the code uses', () {
    test('a page with no media uses nothing', () {
      final DVAndroidMediaUsage usage = dvAndroidMediaUsage(<String>[
        "DVBox.list([DVText('hello'), DVBox.image(DVAsset.logo)])",
      ]);
      expect(usage.player, isFalse);
      expect(usage.camera, isFalse);
      expect(usage.any, isFalse);
    });

    test('every way into the player counts', () {
      for (final String source in <String>[
        'DVBox.video(DVMediaSource.url(u))',
        'DVBox.audio(src)',
        'const DVBackgroundVideo(source: s)',
        'DVModifier().backgroundVideo(DVAsset.clip)',
        'await DV.Platform.media.precache(source)',
      ]) {
        expect(dvAndroidMediaUsage(<String>[source]).player, isTrue,
            reason: source);
      }
    });

    test('the camera box and video recording count as camera', () {
      expect(dvAndroidMediaUsage(<String>['DVBox.camera()']).camera, isTrue);
      expect(
          dvAndroidMediaUsage(<String>['DV.Platform.media.recordVideo()'])
              .camera,
          isTrue);
      expect(dvAndroidMediaUsage(<String>['DVBox.camera()']).player, isFalse);
    });

    test('a comment is not a call site', () {
      expect(
          dvAndroidMediaUsage(<String>[
            '// DVBox.video is how you would show a film\n'
                '/// See [DVBox.camera].\nvoid main() {}',
          ]).any,
          isFalse);
    });
  });

  group('Java', () {
    test('the classes a used feature needs, in the bridge package', () {
      final Map<String, String> both = dvAndroidMediaSources(
          const DVAndroidMediaUsage(player: true, camera: true));
      expect(both.keys, containsAll(<String>[
        dvAndroidMediaPlayerPath,
        dvAndroidMediaSessionPath,
        dvAndroidMediaServicePath,
        dvAndroidAudioFocusPath,
        dvAndroidCameraPath,
      ]));
      for (final String source in both.values) {
        expect(source, startsWith('package dev.dartvel.jni;'));
        expect(source, contains('GENERATED by dartvel build'));
      }
      final Map<String, String> player = dvAndroidMediaSources(
          const DVAndroidMediaUsage(player: true, camera: false));
      expect(player.keys, isNot(contains(dvAndroidCameraPath)));
      expect(dvAndroidMediaSources(const DVAndroidMediaUsage()), isEmpty);
    });

    test('the player draws into a Flutter texture and is polled, not called '
        'back', () {
      final String source = dvAndroidMediaSources(
          const DVAndroidMediaUsage(player: true))[dvAndroidMediaPlayerPath]!;
      expect(source, contains('FlutterEngine.engineForId'));
      expect(source, contains('createSurfaceProducer'));
      expect(source, contains('public static String poll(long handle)'));
      expect(source, isNot(contains('MethodChannel')));
    });

    test('every static method the Dart side calls exists with its signature',
        () {
      final Map<String, String> sources = dvAndroidMediaSources(
          const DVAndroidMediaUsage(player: true, camera: true));
      // Whitespace-normalised: a declaration wrapped over two lines is
      // still the declaration.
      final String all =
          sources.values.join(' ').replaceAll(RegExp(r'\s+'), ' ');
      for (final String method in dvAndroidMediaJavaMethods) {
        expect(all, contains('public static $method'), reason: method);
      }
    });
  });

  group('Gradle', () {
    test('dependencies are added in one marked block, once', () {
      final String once = dvAndroidMediaGradle(_gradleKts,
          const DVAndroidMediaUsage(player: true, camera: true),
          kotlin: true);
      expect(once, contains('implementation("androidx.media3:media3-exoplayer:'));
      expect(once, contains('implementation("androidx.media3:media3-session:'));
      expect(once, contains('implementation("androidx.camera:camera-camera2:'));
      expect(once, contains('implementation("androidx.camera:camera-video:'));
      final String twice = dvAndroidMediaGradle(once,
          const DVAndroidMediaUsage(player: true, camera: true),
          kotlin: true);
      expect(twice, once);
    });

    test('an application that stops using media loses the dependencies', () {
      final String added = dvAndroidMediaGradle(
          _gradleKts, const DVAndroidMediaUsage(player: true),
          kotlin: true);
      expect(
          dvAndroidMediaGradle(added, const DVAndroidMediaUsage(), kotlin: true),
          _gradleKts);
    });

    test('Groovy gets Groovy', () {
      final String groovy = dvAndroidMediaGradle(
          "android {\n}\n", const DVAndroidMediaUsage(camera: true),
          kotlin: false);
      expect(groovy, contains("implementation 'androidx.camera:camera-lifecycle:"));
      expect(groovy, isNot(contains('media3')));
    });
  });

  group('manifest', () {
    test('the player gets INTERNET, the service and picture-in-picture', () {
      final String out =
          dvAndroidMediaManifest(_manifest, const DVAndroidMediaUsage(player: true));
      expect(out, contains('android.permission.INTERNET'));
      expect(out, contains('android.permission.FOREGROUND_SERVICE"'));
      expect(out, contains('FOREGROUND_SERVICE_MEDIA_PLAYBACK'));
      expect(out, contains('dev.dartvel.jni.DartvelMediaService'));
      expect(out, contains('android:foregroundServiceType="mediaPlayback"'));
      expect(out, contains('androidx.media3.session.MediaSessionService'));
      expect(out, contains('android:supportsPictureInPicture="true"'));
      // The service sits inside <application>, the permissions outside it.
      expect(out.indexOf('DartvelMediaService'),
          greaterThan(out.indexOf('<application')));
      expect(out.indexOf('FOREGROUND_SERVICE"'),
          lessThan(out.indexOf('<application')));
    });

    test('is idempotent and reversible', () {
      const DVAndroidMediaUsage usage = DVAndroidMediaUsage(player: true);
      final String once = dvAndroidMediaManifest(_manifest, usage);
      expect(dvAndroidMediaManifest(once, usage), once);
      expect(dvAndroidMediaManifest(once, const DVAndroidMediaUsage()),
          _manifest);
    });

    test('INTERNET is not declared twice', () {
      final String declared = _manifest.replaceFirst('<application',
          '<uses-permission android:name="android.permission.INTERNET"/>\n    <application');
      final String out =
          dvAndroidMediaManifest(declared, const DVAndroidMediaUsage(player: true));
      expect('android.permission.INTERNET'.allMatches(out), hasLength(1));
    });

    test('the camera alone adds no service', () {
      final String out =
          dvAndroidMediaManifest(_manifest, const DVAndroidMediaUsage(camera: true));
      expect(out, isNot(contains('DartvelMediaService')));
      expect(out, isNot(contains('supportsPictureInPicture')));
    });

    test('the permissions the camera box needs are asked for', () {
      expect(dvAndroidMediaPermissions(const DVAndroidMediaUsage(camera: true)),
          <String>['camera', 'microphone']);
      expect(dvAndroidMediaPermissions(const DVAndroidMediaUsage(player: true)),
          isEmpty);
    });
  });
}
