package dev.dartvel.devclient;

// GENERATED by dartvel build --profile development. Do not edit.

import android.app.Activity;
import android.content.Intent;
import android.net.Uri;
import android.os.Bundle;

public final class DartvelDevPairActivity extends Activity {
  @Override
  protected void onCreate(Bundle state) {
    super.onCreate(state);
    Uri data = getIntent() == null ? null : getIntent().getData();
    if (data != null) {
      DartvelDevClient.pair(getApplicationContext(), data.toString());
    }
    Intent launch = getPackageManager().getLaunchIntentForPackage(getPackageName());
    if (launch != null) {
      launch.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
      startActivity(launch);
    }
    finish();
  }
}
