package dev.dartvel.devclient;

// GENERATED by dartvel build --profile development. Do not edit.
//
// The phone dials out to `dartvel dev` over TLS, trusting the connection only
// when the server's certificate is for the key in the pairing link, so the
// token and everything after it are unreadable to the rest of the network. The
// server also answers with a signature over this device's nonce by that key;
// nothing is sent until both verify. Then the server asks for streams, and each stream
// is piped to the Dart VM service on this phone's loopback.

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.math.BigInteger;
import java.net.InetSocketAddress;
import java.net.Socket;
import java.net.URI;
import java.net.URLDecoder;
import java.nio.charset.Charset;
import java.security.KeyFactory;
import java.security.KeyPairGenerator;
import java.security.PublicKey;
import java.security.SecureRandom;
import java.security.Signature;
import java.security.interfaces.ECPublicKey;
import java.security.spec.ECGenParameterSpec;
import java.security.spec.ECParameterSpec;
import java.security.spec.ECPoint;
import java.security.spec.ECPublicKeySpec;
import java.security.cert.CertificateException;
import java.security.cert.X509Certificate;
import javax.net.ssl.SSLContext;
import javax.net.ssl.SSLHandshakeException;
import javax.net.ssl.SSLSocketFactory;
import javax.net.ssl.TrustManager;
import javax.net.ssl.X509TrustManager;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;

public final class DartvelDevTunnel implements Runnable {
  public interface Listener {
    void status(String message);
  }

  static final String PATH = "/_dartvel/dev-client/tunnel";
  static final String PROTOCOL = "dartvel-dev-tunnel-v1";
  static final String SCHEME = "dartvel-dev";
  static final Charset UTF8 = Charset.forName("UTF-8");

  final String host;
  final int port;
  final String token;
  final PublicKey key;
  final int vmPort;
  final String vmPath;
  final String manifestJson;
  final Listener listener;
  private volatile boolean closed;
  private volatile Socket control;

  private DartvelDevTunnel(String host, int port, String token, PublicKey key,
      int vmPort, String vmPath, String manifestJson, Listener listener) {
    this.host = host;
    this.port = port;
    this.token = token;
    this.key = key;
    this.vmPort = vmPort;
    this.vmPath = vmPath;
    this.manifestJson = manifestJson;
    this.listener = listener;
  }

  /** A tunnel for [link], a dartvel-dev://pair link, to [vmService]. */
  public static DartvelDevTunnel fromLink(String link, String vmService,
      String manifestJson, Listener listener) {
    URI uri = URI.create(link.trim());
    if (!SCHEME.equals(uri.getScheme())) {
      throw new IllegalArgumentException("Not a " + SCHEME + " link: " + link);
    }
    Map<String, String> query = new HashMap<String, String>();
    String raw = uri.getRawQuery();
    if (raw == null) {
      // dartvel-dev://pair?... is opaque to java.net.URI.
      String s = uri.getRawSchemeSpecificPart();
      int q = s.indexOf('?');
      raw = q < 0 ? "" : s.substring(q + 1);
    }
    for (String pair : raw.split("&")) {
      int eq = pair.indexOf('=');
      if (eq <= 0) continue;
      query.put(decode(pair.substring(0, eq)), decode(pair.substring(eq + 1)));
    }
    String server = query.get("server");
    String token = query.get("token");
    String key = query.get("key");
    if (server == null || token == null || key == null) {
      throw new IllegalArgumentException("The link names no server, token or key.");
    }
    URI serverUri = URI.create(server);
    if (!"https".equals(serverUri.getScheme())) {
      throw new IllegalArgumentException("The link names a dev server that is not https; "
          + "scan the code a current dartvel dev prints.");
    }
    URI vm = URI.create(vmService);
    return new DartvelDevTunnel(
        serverUri.getHost(),
        serverUri.getPort() < 0 ? 443 : serverUri.getPort(),
        token,
        publicKey(base64UrlDecode(key)),
        vm.getPort(),
        vm.getRawPath() == null || vm.getRawPath().isEmpty() ? "/" : vm.getRawPath(),
        manifestJson,
        listener);
  }

  /**
   * The VM service URI to tunnel to: the first one this process reported.
   *
   * The VM service's address cannot change while the process lives, but what
   * a restarted isolate reports can: with DDS attached it reports DDS's
   * address, which is on the dev machine, not the phone.
   */
  public static String vmServiceToKeep(String held, String offered) {
    return held != null ? held : offered;
  }

  public String server() {
    return host + ":" + port;
  }

  public void close() {
    closed = true;
    Socket s = control;
    if (s != null) {
      try {
        s.close();
      } catch (IOException ignored) {
      }
    }
  }

  @Override
  public void run() {
    int attempt = 0;
    while (!closed) {
      try {
        attempt++;
        listener.status("connecting to " + server());
        runControl();
        if (closed) return;
        listener.status("the dev server at " + server() + " disconnected");
        attempt = 0;
      } catch (Refused refused) {
        listener.status(refused.getMessage());
        return;
      } catch (IOException e) {
        listener.status("could not reach the dev server at " + server() + ": " + e.getMessage());
      }
      try {
        Thread.sleep(Math.max(1000L, Math.min(10000L, 1000L * attempt)));
      } catch (InterruptedException e) {
        return;
      }
    }
  }

  /** A refusal a retry cannot fix: the wrong server, key or project. */
  static final class Refused extends IOException {
    Refused(String message) {
      super(message);
    }
  }

  private void runControl() throws IOException {
    Socket socket = open("role=control");
    control = socket;
    try {
      OutputStream out = socket.getOutputStream();
      String hello = "{\"vmService\":\"" + vmPath + "\",\"manifest\":" + manifestJson + "}\n";
      out.write(hello.getBytes(UTF8));
      out.flush();
      listener.status("paired with " + server());
      InputStream in = socket.getInputStream();
      String line;
      while ((line = readLine(in)) != null) {
        if (line.startsWith("open ")) {
          final String id = line.substring(5).trim();
          Thread t = new Thread(new Runnable() {
            public void run() {
              stream(id);
            }
          }, "dartvel-dev-stream-" + id);
          t.setDaemon(true);
          t.start();
        } else if (line.startsWith("refused ")) {
          throw new Refused("the dev server refused this build: " + line.substring(8));
        }
      }
    } finally {
      control = null;
      try {
        socket.close();
      } catch (IOException ignored) {
      }
    }
  }

  private void stream(String id) {
    Socket up = null;
    Socket vm = null;
    try {
      up = open("role=stream&id=" + id);
      vm = new Socket();
      vm.connect(new InetSocketAddress("127.0.0.1", vmPort), 5000);
      pipe(up, vm);
      pipe(vm, up);
    } catch (IOException e) {
      listener.status("a stream to the VM service failed: " + e.getMessage());
      closeQuietly(up);
      closeQuietly(vm);
    }
  }

  private static void pipe(final Socket from, final Socket to) {
    Thread t = new Thread(new Runnable() {
      public void run() {
        byte[] buffer = new byte[16384];
        try {
          InputStream in = from.getInputStream();
          OutputStream out = to.getOutputStream();
          int n;
          while ((n = in.read(buffer)) >= 0) {
            out.write(buffer, 0, n);
            out.flush();
          }
        } catch (IOException ignored) {
        } finally {
          closeQuietly(from);
          closeQuietly(to);
        }
      }
    }, "dartvel-dev-pipe");
    t.setDaemon(true);
    t.start();
  }

  static void closeQuietly(Socket s) {
    if (s == null) return;
    try {
      s.close();
    } catch (IOException ignored) {
    }
  }

  /** Opens a tunnel connection and verifies the server's proof. */
  private Socket open(String query) throws IOException {
    byte[] random = new byte[32];
    new SecureRandom().nextBytes(random);
    String nonce = base64UrlEncode(random);
    Socket raw = new Socket();
    raw.connect(new InetSocketAddress(host, port), 5000);
    Socket socket = raw;
    boolean ok = false;
    try {
      javax.net.ssl.SSLSocket secure =
          (javax.net.ssl.SSLSocket) tls().createSocket(raw, host, port, true);
      socket = secure;
      try {
        secure.startHandshake();
      } catch (SSLHandshakeException e) {
        throw new Refused("the server at " + server() + " did not present the key this device "
            + "was paired with, so nothing was sent to it.");
      }
      OutputStream out = socket.getOutputStream();
      String request = "GET " + PATH + "?" + query + "&nonce=" + nonce + " HTTP/1.1\r\n"
          + "Host: " + host + ":" + port + "\r\n"
          + "Authorization: Bearer " + token + "\r\n"
          + "Connection: Upgrade\r\n"
          + "Upgrade: " + PROTOCOL + "\r\n\r\n";
      out.write(request.getBytes(UTF8));
      out.flush();

      InputStream in = socket.getInputStream();
      String status = readLine(in);
      if (status == null) throw new IOException("the dev server closed the connection");
      Map<String, String> headers = new HashMap<String, String>();
      String line;
      while ((line = readLine(in)) != null && !line.isEmpty()) {
        int colon = line.indexOf(':');
        if (colon > 0) {
          headers.put(line.substring(0, colon).trim().toLowerCase(Locale.ROOT),
              line.substring(colon + 1).trim());
        }
      }
      String[] parts = status.split(" ");
      int code = parts.length > 1 ? Integer.parseInt(parts[1]) : 0;
      if (code == 401) {
        throw new Refused("the dev server at " + server() + " refused this device. "
            + "Its pairing ends when dartvel dev restarts; scan the new code.");
      }
      if (code != 101) throw new IOException("the dev server answered HTTP " + code);
      String proof = headers.get("x-dartvel-proof");
      if (proof == null || !verify(nonce, proof)) {
        throw new Refused("the server at " + server() + " could not give proof that it holds "
            + "the key this device was paired with, so nothing was sent to it.");
      }
      ok = true;
      return socket;
    } finally {
      if (!ok) closeQuietly(socket);
    }
  }

  /** TLS that trusts one certificate: the one for the pairing key. */
  private SSLSocketFactory tls() throws IOException {
    try {
      SSLContext context = SSLContext.getInstance("TLS");
      context.init(null, new TrustManager[] {new PinnedKey(key)}, new SecureRandom());
      return context.getSocketFactory();
    } catch (java.security.GeneralSecurityException e) {
      throw new IOException("TLS is not available: " + e);
    }
  }

  /** Trusts a server whose certificate's public key is [pinned], and no other. */
  static final class PinnedKey implements X509TrustManager {
    private final PublicKey pinned;

    PinnedKey(PublicKey pinned) {
      this.pinned = pinned;
    }

    public void checkClientTrusted(X509Certificate[] chain, String authType)
        throws CertificateException {
      throw new CertificateException("a device does not trust clients");
    }

    public void checkServerTrusted(X509Certificate[] chain, String authType)
        throws CertificateException {
      if (chain == null || chain.length == 0 || !samePoint(chain[0].getPublicKey(), pinned)) {
        throw new CertificateException("not the key this device was paired with");
      }
    }

    public X509Certificate[] getAcceptedIssuers() {
      return new X509Certificate[0];
    }
  }

  static boolean samePoint(PublicKey a, PublicKey b) {
    if (!(a instanceof ECPublicKey) || !(b instanceof ECPublicKey)) return false;
    ECPoint x = ((ECPublicKey) a).getW();
    ECPoint y = ((ECPublicKey) b).getW();
    return x.getAffineX().equals(y.getAffineX()) && x.getAffineY().equals(y.getAffineY());
  }

  private boolean verify(String nonce, String proof) {
    try {
      byte[] raw = base64UrlDecode(proof);
      if (raw.length != 64) return false;
      Signature signature = Signature.getInstance("SHA256withECDSA");
      signature.initVerify(key);
      signature.update((PROTOCOL + "\n" + nonce).getBytes(UTF8));
      return signature.verify(der(raw));
    } catch (Exception e) {
      return false;
    }
  }

  /** A raw r||s signature as the DER sequence java.security expects. */
  static byte[] der(byte[] raw) {
    byte[] r = new BigInteger(1, java.util.Arrays.copyOfRange(raw, 0, 32)).toByteArray();
    byte[] s = new BigInteger(1, java.util.Arrays.copyOfRange(raw, 32, 64)).toByteArray();
    ByteArrayOutputStream out = new ByteArrayOutputStream();
    out.write(0x30);
    out.write(4 + r.length + s.length);
    out.write(0x02);
    out.write(r.length);
    out.write(r, 0, r.length);
    out.write(0x02);
    out.write(s.length);
    out.write(s, 0, s.length);
    return out.toByteArray();
  }

  /** An uncompressed P-256 point as a public key. */
  static PublicKey publicKey(byte[] point) {
    if (point.length != 65 || point[0] != 0x04) {
      throw new IllegalArgumentException("The link's key is not a P-256 point.");
    }
    try {
      // The curve's parameters from a generated key, which every Android
      // version has; AlgorithmParameters("EC") does not exist before API 26.
      KeyPairGenerator generator = KeyPairGenerator.getInstance("EC");
      generator.initialize(new ECGenParameterSpec("secp256r1"));
      ECParameterSpec curve = ((ECPublicKey) generator.generateKeyPair().getPublic()).getParams();
      ECPoint w = new ECPoint(
          new BigInteger(1, java.util.Arrays.copyOfRange(point, 1, 33)),
          new BigInteger(1, java.util.Arrays.copyOfRange(point, 33, 65)));
      return KeyFactory.getInstance("EC").generatePublic(new ECPublicKeySpec(w, curve));
    } catch (Exception e) {
      throw new IllegalArgumentException("The link's key could not be read: " + e);
    }
  }

  /** A line ending in \n, read a byte at a time so nothing after it is taken. */
  static String readLine(InputStream in) throws IOException {
    ByteArrayOutputStream line = new ByteArrayOutputStream();
    int b;
    while ((b = in.read()) >= 0) {
      if (b == '\n') break;
      line.write(b);
      if (line.size() > 65536) throw new IOException("a line from the dev server is too long");
    }
    if (b < 0 && line.size() == 0) return null;
    String text = new String(line.toByteArray(), UTF8);
    return text.endsWith("\r") ? text.substring(0, text.length() - 1) : text;
  }

  private static String decode(String s) {
    try {
      return URLDecoder.decode(s, "UTF-8");
    } catch (java.io.UnsupportedEncodingException e) {
      throw new IllegalStateException(e);
    }
  }

  private static final String ALPHABET =
      "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_";

  // Both by hand: java.util.Base64 arrived in Android API 26, and
  // android.util.Base64 does not exist on a JVM.
  static String base64UrlEncode(byte[] data) {
    StringBuilder out = new StringBuilder();
    int i = 0;
    while (i + 2 < data.length) {
      int n = ((data[i] & 0xff) << 16) | ((data[i + 1] & 0xff) << 8) | (data[i + 2] & 0xff);
      out.append(ALPHABET.charAt((n >> 18) & 63)).append(ALPHABET.charAt((n >> 12) & 63))
          .append(ALPHABET.charAt((n >> 6) & 63)).append(ALPHABET.charAt(n & 63));
      i += 3;
    }
    int left = data.length - i;
    if (left == 1) {
      int n = (data[i] & 0xff) << 16;
      out.append(ALPHABET.charAt((n >> 18) & 63)).append(ALPHABET.charAt((n >> 12) & 63));
    } else if (left == 2) {
      int n = ((data[i] & 0xff) << 16) | ((data[i + 1] & 0xff) << 8);
      out.append(ALPHABET.charAt((n >> 18) & 63)).append(ALPHABET.charAt((n >> 12) & 63))
          .append(ALPHABET.charAt((n >> 6) & 63));
    }
    return out.toString();
  }

  static byte[] base64UrlDecode(String text) {
    String s = text.replace('+', '-').replace('/', '_');
    while (s.endsWith("=")) s = s.substring(0, s.length() - 1);
    ByteArrayOutputStream out = new ByteArrayOutputStream();
    int buffer = 0;
    int bits = 0;
    for (int i = 0; i < s.length(); i++) {
      int v = ALPHABET.indexOf(s.charAt(i));
      if (v < 0) throw new IllegalArgumentException("not base64url");
      buffer = (buffer << 6) | v;
      bits += 6;
      if (bits >= 8) {
        bits -= 8;
        out.write((buffer >> bits) & 0xff);
      }
    }
    return out.toByteArray();
  }
}
