package dev.dartvel.devclient;

// GENERATED by dartvel build --profile development. Do not edit.
//
// Dart calls vmService() over JNI when the app starts, with the URI of its own
// VM service. A scanned dartvel-dev:// link arrives through
// DartvelDevPairActivity. With both, the tunnel starts on a Java thread, which
// a hot restart -- that kills every Dart isolate -- does not touch.

import android.content.Context;
import android.content.SharedPreferences;
import android.util.Log;

public final class DartvelDevClient {
  /** The binding manifest this build compiled in. */
  static final String MANIFEST = "{\"target\":\"android\",\"bindings\":[\"dartvel_flutter@0.9.3\",\"plugin:jni\"]}";

  /** Referenced so the build is recognisable as a development build. */
  static final String MARKER = "dartvel-dev-client-shell-v1";

  private static final String TAG = "DartvelDevClient";
  private static final String PREFS = "dev.dartvel.devclient";

  private static String link;
  private static String vmService;
  private static DartvelDevTunnel tunnel;
  private static String status = "not paired: scan the code dartvel dev prints";

  private DartvelDevClient() {}

  /** Called from Dart with this app's VM service URI. Returns the status. */
  public static synchronized String vmService(String uri) {
    vmService = DartvelDevTunnel.vmServiceToKeep(vmService, uri);
    if (link == null) link = stored();
    start();
    return status;
  }

  /** A scanned or opened pairing link. */
  public static synchronized void pair(Context context, String newLink) {
    link = newLink;
    if (context != null) {
      prefs(context).edit().putString("link", newLink).apply();
    }
    if (tunnel != null) {
      tunnel.close();
      tunnel = null;
    }
    start();
  }

  public static synchronized String status() {
    return status;
  }

  /** The dev server's host, for reaching the backend it runs beside. */
  public static synchronized String serverHost() {
    return tunnel == null ? null : tunnel.host;
  }

  private static void start() {
    if (link == null || vmService == null || tunnel != null) return;
    try {
      tunnel = DartvelDevTunnel.fromLink(link, vmService, MANIFEST,
          new DartvelDevTunnel.Listener() {
            public void status(String message) {
              Log.i(TAG, message);
              synchronized (DartvelDevClient.class) {
                status = message;
              }
            }
          });
    } catch (IllegalArgumentException e) {
      status = "the pairing link could not be used: " + e.getMessage();
      Log.w(TAG, status);
      return;
    }
    Thread thread = new Thread(tunnel, "dartvel-dev-tunnel");
    thread.setDaemon(true);
    thread.start();
  }

  private static String stored() {
    Context context = dev.dartvel.jni.DartvelContext.context();
    return context == null ? null : prefs(context).getString("link", null);
  }

  private static SharedPreferences prefs(Context context) {
    return context.getSharedPreferences(PREFS, Context.MODE_PRIVATE);
  }
}
