// GENERATED by tool/cli_reference.dart from the dartvel command table.
// Run: dart run tool/cli_reference.dart

import 'docs_cli_command.dart';

/// Every visible dartvel command, alphabetically.
const List<DocsCliCommand> kCliCommands = <DocsCliCommand>[
  DocsCliCommand(
    name: 'admin',
    description: 'Generate Dartvel admin surfaces.',
    subcommands: <DocsCliCommand>[
      DocsCliCommand(
        name: 'generate',
        description: 'Generate Dartvel admin and devtools pages.',
        options: <String>[
          '-f, --[no-]force    Overwrite generated admin files.',
        ],
      ),
    ],
  ),
  DocsCliCommand(
    name: 'ai',
    description: 'Leverage Dartvel AI integration helper commands.',
    subcommands: <DocsCliCommand>[
      DocsCliCommand(
        name: 'context',
        description: 'Export the codebase context to markdown for AI tools.',
      ),
      DocsCliCommand(
        name: 'doctor',
        description: 'Diagnose and automatically resolve configuration issues using AI.',
      ),
      DocsCliCommand(
        name: 'generate',
        description: 'Generate features, models, or views from a natural language prompt.',
      ),
    ],
  ),
  DocsCliCommand(
    name: 'analyze',
    description: 'Analyze a running application: performance measurements and findings.',
    options: <String>[
      '    --json    Emit the published measurements as JSON.',
    ],
  ),
  DocsCliCommand(
    name: 'artifact',
    description: 'Split a large build artifact into committable chunks, or rejoin them.',
    subcommands: <DocsCliCommand>[
      DocsCliCommand(
        name: 'join',
        description: 'Rebuild a file from its chunks and manifest.',
        options: <String>[
          '-o, --out     Where to write the rebuilt file. Defaults to the manifest\'s own name, beside it.',
        ],
      ),
      DocsCliCommand(
        name: 'split',
        description: 'Split a file into chunks plus a manifest, for committing.',
        options: <String>[
          '-o, --out           Directory to write the chunks and manifest into.',
          '                    (defaults to ".")',
          '    --chunk-size    Bytes per chunk. The default is under GitHub\'s 100 MB hard block.',
          '                    (defaults to "94371840")',
        ],
      ),
    ],
  ),
  DocsCliCommand(
    name: 'build',
    description: 'Build for production. Pass a platform (dartvel build web) or omit it to build every available platform.',
    options: <String>[
      '-p, --platform                   Target platform (or pass it positionally)',
      '                                 [android, ios, web, windows, macos, linux, fireos, tizen, sony-elinux, webos, tvos, fuchsia, vscode, chrome-extension, firefox-extension, web-server, tpk, sony-elinux-iso, sony-elinux-img, linux-cli, linux-tui, windows-cli, windows-tui, macos-cli, macos-tui, fuchsia-cli, fuchsia-tui, all (default)]',
      '    --profile                    What kind of build to make.',
      '',
      '          [development]          Flutter debug (JIT). On Android it carries the dev-client pairing, so `dartvel dev --dev-client` can hot reload it over the network.',
      '          [profile]              Flutter profile mode.',
      '          [release] (default)    Flutter release mode.',
      '',
      '-t, --target                     Target entry point',
      '    --format                     Sony eLinux output format (bundle | iso | img)',
      '                                 [bundle, iso, img]',
      '    --device-profile             Named embedded device profile from pubspec.yaml',
      '    --simulator                  Build for a simulator rather than a device (tvOS). Device builds are AOT and need a configured Xcode signing team, so this is the only unsigned path.',
      '    --build-timeout              Minutes before a stalled build is killed (0 disables). A build that stops producing output is the failure mode worth guarding: it looks identical to a slow one and costs far more.',
      '    --arch                       Target architecture for embedded builds',
      '                                 [arm, arm64 (default), x64]',
      '    --[no-]split-per-abi         Split APKs per ABI (Android)',
      '    --build-number               Build number',
      '    --build-name                 Build name/version',
      '    --[no-]obfuscate             Obfuscate code (release only)',
      '                                 (defaults to on)',
      '    --[no-]tree-shake-icons      Tree shake icons',
      '                                 (defaults to on)',
      '    --[no-]auto-install          Install missing build tools without prompting. Defaults to prompting when interactive, and to installing in CI. Use --no-auto-install to require a pre-provisioned toolchain.',
    ],
  ),
  DocsCliCommand(
    name: 'cache',
    description: 'Inspect and revalidate the Dartvel cache.',
    subcommands: <DocsCliCommand>[
      DocsCliCommand(
        name: 'clear',
        description: 'Clear a persistent cache, or local cache tag metadata.',
        options: <String>[
          '    --database    Path to the SQLite database backing DVDatabaseCacheAdapter.',
          '    --table       Cache table name, when it was customised.',
          '                  (defaults to "dartvel_cache")',
        ],
      ),
      DocsCliCommand(
        name: 'inspect',
        description: 'Inspect cache keys attached to a tag.',
      ),
      DocsCliCommand(
        name: 'purge',
        description: 'Remove expired entries from a persistent cache, reclaiming space.',
        options: <String>[
          '    --database    Path to the SQLite database backing DVDatabaseCacheAdapter.',
          '    --table       (defaults to "dartvel_cache")',
        ],
      ),
      DocsCliCommand(
        name: 'revalidate',
        description: 'Revalidate a cache tag and print affected keys.',
      ),
    ],
  ),
  DocsCliCommand(
    name: 'capture',
    description: 'Capture what a target rendered, and check that it rendered anything.',
    subcommands: <DocsCliCommand>[
      DocsCliCommand(
        name: 'firefox',
        description: 'Photograph a page in Firefox after it has drawn.',
        options: <String>[
          '    --firefox    The Firefox binary to drive.',
          '                 (defaults to "firefox")',
          '    --profile    A prepared profile directory.',
          '    --settle     Seconds to wait for the page to lay out before giving up.',
          '                 (defaults to "40")',
          '    --width      (defaults to "1280")',
          '    --height     (defaults to "900")',
        ],
      ),
      DocsCliCommand(
        name: 'pty',
        description: 'Run a command under a pseudo-terminal and save its raw output.',
        options: <String>[
          '    --seconds    How long to let the command run before ending the capture.',
          '                 (defaults to "25")',
          '    --rows       Terminal height. The application lays out against this.',
          '                 (defaults to "40")',
          '    --columns    Terminal width.',
          '                 (defaults to "120")',
        ],
      ),
      DocsCliCommand(
        name: 'pwa-sync',
        description: 'Fail unless a POST made offline is queued by the worker and replayed once online, in a real browser.',
        options: <String>[
          '    --web                The built web output, with its sw.js.',
          '                         (defaults to "build/web")',
          '    --chrome             The browser to run. Defaults to DARTVEL_CHROME or a system Chrome.',
          '    --[no-]allow-skip    Exit 0 when no browser can be launched, instead of failing. For machines that never had one.',
        ],
      ),
      DocsCliCommand(
        name: 'verify',
        description: 'Fail unless the capture is a PNG showing something rendered.',
        options: <String>[
          '    --min-width        Reject a capture narrower than this.',
          '                       (defaults to "1")',
          '    --min-height       Reject a capture shorter than this.',
          '                       (defaults to "1")',
          '    --max-dominant     Share of one colour above which the capture is called blank.',
          '                       (defaults to "0.99")',
          '    --expect-colour    An "r,g,b" the capture must contain.',
          '    --label            What is being verified, for the failure message.',
          '                       (defaults to "the capture")',
        ],
      ),
    ],
  ),
  DocsCliCommand(
    name: 'create',
    description: 'Initialize a new Dartvel project with best practices. (Aliases: new)',
    aliases: <String>['new'],
    options: <String>[
      '    --[no-]web        Include web platform',
      '                      (defaults to on)',
      '    --[no-]mobile     Include mobile platforms',
      '                      (defaults to on)',
      '    --[no-]desktop    Include desktop platforms',
      '    --[no-]ssr        Enable SSR/SSG features',
      '-n, --name            Project name',
      '-o, --org             Organization domain',
      '                      (defaults to "com.example")',
    ],
  ),
  DocsCliCommand(
    name: 'db',
    description: 'Manage the Dartvel database schemas, migrations, and seeding.',
    subcommands: <DocsCliCommand>[
      DocsCliCommand(
        name: 'migrate',
        description: 'Run pending database schema migrations.',
        options: <String>[
          '    --tenant                     Which tenant the rows written before the tenant column existed belong to. Required to add that column to a table that already has rows, because without it they belong to nobody and every tenant sees an empty table.',
          '    --orphan-existing-rows       Add the tenant column and leave existing rows belonging to no tenant, which hides them. For a staging database or a table being emptied. Never the default.',
          '    --plan                       Print the class of every change -- instant, online or blocking -- and apply none of them.',
          '    --dry-run                    Plan and gate the migration as if running it, and apply nothing.',
          '    --against                    Rehearse against a snapshot of production: its server, version, columns and row counts. Needs --dry-run or --plan.',
          '                                 [snapshot]',
          '    --snapshot                   The snapshot file for --against snapshot. Defaults to .dartvel/db/production.snapshot.json.',
          '    --production                 This migration runs against production: a blocking change is refused without --allow-blocking (DV-SCHEMA-002).',
          '    --allow-blocking=<reason>    Run a blocking change against production anyway. The reason is required and is logged to .dartvel/db/schema_overrides.jsonl.',
        ],
      ),
      DocsCliCommand(
        name: 'pull',
        description: 'Pull the remote database schema snapshot, or with --local print model suggestions from drift, isar and sqflite schemas.',
        options: <String>[
          '    --local    Print @DVModel suggestions from the drift tables, isar collections and sqflite CREATE TABLE statements under lib/. Suggestions are printed, never applied.',
        ],
      ),
      DocsCliCommand(
        name: 'push',
        description: 'Push local schema changes directly to the database.',
      ),
      DocsCliCommand(
        name: 'seed',
        description: 'Seed the database with test data.',
      ),
    ],
  ),
  DocsCliCommand(
    name: 'deploy',
    description: 'Deploy to production (web/server).',
    options: <String>[
      '-t, --target             Deployment target',
      '                         [web, server, all (default)]',
      '    --provider           Cloud provider',
      '                         [firebase, vercel, netlify, cloudflare, custom]',
      '-e, --environment        Environment to deploy to. Declared secrets required for it must resolve before anything ships.',
      '                         (defaults to "production")',
      '    --functions          Function mode: write a deployment artifact per backend function instead of deploying the whole build.',
      '    --function-target    Where the functions go: lambda, cloud-run, container, edge, fly, railway, bare-metal.',
      '                         (defaults to "container")',
      '    --[no-]build         Build before deploying',
      '                         (defaults to on)',
      '    --[no-]verify        Verify deployment',
      '                         (defaults to on)',
    ],
  ),
  DocsCliCommand(
    name: 'dev',
    description: 'Run the Dartvel development server and Flutter app. (Aliases: run, start)',
    aliases: <String>['run', 'start'],
    options: <String>[
      '-d, --device                   Target device id or name (prefixes allowed)',
      '    --[no-]release             Build in release mode',
      '    --[no-]profile             Build in profile mode',
      '    --[no-]debug               Build in debug mode',
      '    --dart-define              Pass additional dart-defines to Flutter',
      '    --dart-define-from-file    Pass dart-define-from-file to Flutter',
      '    --web-renderer             Select web renderer (auto, html, canvaskit)',
      '    --web-hostname             Hostname for the Flutter web-server device',
      '    --web-port                 Port for the Flutter web-server device',
      '-v, --[no-]verbose             Verbose output',
      '    --dev-client               Pair development builds (dartvel build android --profile development) over the network: print a QR code to scan, and hot reload every paired device on save. With no -d, no local app is started.',
      '    --dev-client-port          Port the dev-client bundles are served on',
      '                               (defaults to "8787")',
    ],
  ),
  DocsCliCommand(
    name: 'devtools',
    description: 'Generate and open Dartvel devtools metadata pages.',
    options: <String>[
      '-f, --[no-]force    Overwrite generated devtools files.',
    ],
  ),
  DocsCliCommand(
    name: 'docs',
    description: 'Build the documentation site from the project graph.',
    options: <String>[
      '-o, --output            Where to write the site, relative to the project.',
      '                        (defaults to "build/docs")',
      '    --serve             Serve the site on loopback and rebuild it when the project changes.',
      '    --port              The port for --serve.',
      '                        (defaults to "4180")',
      '    --fatal-warnings    Exit non-zero when a decision names a node that is gone (DV-DOCS-001) or a node cannot be mapped to its source (DV-DOCS-002).',
    ],
  ),
  DocsCliCommand(
    name: 'doctor',
    description: 'Check your environment and project for common issues.',
    options: <String>[
      '    --modules    Verify every module pin (digest, signing key, publisher, version) and compare what each module uses against what this application grants.',
      '    --target     Validate the toolchain for an embedded, TV or extension build target, or, for android and ios, the deep-link verification documents the declared domains serve. Comma-separate several: --target android,ios.',
      '                 [tizen, sony-elinux, webos, tvos, fuchsia, vscode, chrome-extension, firefox-extension, linux-cli, linux-tui, windows-cli, windows-tui, macos-cli, macos-tui, fuchsia-cli, fuchsia-tui, android, ios]',
    ],
  ),
  DocsCliCommand(
    name: 'engine',
    description: 'Resolve and verify a from-source Flutter engine build.',
    subcommands: <DocsCliCommand>[
      DocsCliCommand(
        name: 'plan',
        description: 'Print the build a given architecture and mode resolves to.',
        options: <String>[
          '    --arch              Architecture to build for.',
          '                        [x64 (default), arm64, arm]',
          '    --os                Target operating system.',
          '                        [linux (default), fuchsia]',
          '    --mode              Engine runtime mode.',
          '                        [debug, profile, release (default)]',
          '    --src-root          Absolute path to engine/src, so paths handed to gn resolve.',
          '    --toolchain-root    Directory to assemble the custom toolchain in, when one is needed.',
          '    --github-output     Emit key=value lines for \$GITHUB_OUTPUT instead of prose.',
        ],
      ),
      DocsCliCommand(
        name: 'verify',
        description: 'Fail unless the built engine is actually the requested architecture.',
        options: <String>[
          '    --arch    Architecture to build for.',
          '              [x64 (default), arm64, arm]',
          '    --os      Target operating system.',
          '              [linux (default), fuchsia]',
          '    --mode    Engine runtime mode.',
          '              [debug, profile, release (default)]',
        ],
      ),
    ],
  ),
  DocsCliCommand(
    name: 'ensure-path',
    description: 'Add the dartvel command to your PATH, if it is not already.',
    options: <String>[
      '    --dry-run      Print what would change without changing anything.',
      '    --system       Change the PATH for every user rather than just this one. Needs administrator on Windows and root elsewhere.',
      '    --directory    The directory to add. Defaults to the one this binary is in.',
    ],
  ),
  DocsCliCommand(
    name: 'explain',
    description: 'Explain a Dartvel diagnostic code, e.g. dartvel explain DV-WINDOW-004.',
  ),
  DocsCliCommand(
    name: 'flags',
    description: 'List the declared feature flags, and the ones past their expiry.',
    subcommands: <DocsCliCommand>[
      DocsCliCommand(
        name: 'list',
        description: 'Every declared flag, with its type, default, owner and expiry.',
      ),
      DocsCliCommand(
        name: 'prune',
        description: 'Flags past their expiry, with the code that still reads each one.',
      ),
    ],
  ),
  DocsCliCommand(
    name: 'generate',
    description: 'Generate Dartvel template files for pages, models, forms, and backend functions. With --check, fail when generated output is stale.',
    options: <String>[
      '    --check     Regenerate into a scratch location and compare, twice. Exits non-zero and prints the paths when the project\'s generated output is stale (DV-GEN-001) or generation is not deterministic (DV-GEN-002). Writes nothing into the project.',
      '    --render    The rendering backends the checked output was generated for (gui, terminal, or both), as `dartvel routes --render`.',
    ],
    subcommands: <DocsCliCommand>[
      DocsCliCommand(
        name: 'backend-function',
        description: 'Generate a new backend function.',
      ),
      DocsCliCommand(
        name: 'form',
        description: 'Generate a form functional widget for a model.',
      ),
      DocsCliCommand(
        name: 'model',
        description: 'Generate a new data model class.',
      ),
      DocsCliCommand(
        name: 'page',
        description: 'Generate a new page functional widget.',
      ),
    ],
  ),
  DocsCliCommand(
    name: 'i18n',
    description: 'Extract translatable strings and check locale catalogues.',
    subcommands: <DocsCliCommand>[
      DocsCliCommand(
        name: 'check',
        description: 'Report untranslated and stale keys in each locale catalogue.',
        options: <String>[
          '    --strict    Exit non-zero when a locale is missing a translation.',
        ],
      ),
      DocsCliCommand(
        name: 'extract',
        description: 'Collect translatable strings into lib/l10n/app_<locale>.arb.',
        options: <String>[
          '-l, --locale    Locales to write. Defaults to the catalogues already present.',
        ],
      ),
    ],
  ),
  DocsCliCommand(
    name: 'import',
    description: 'Bring an external description into the project.',
    subcommands: <DocsCliCommand>[
      DocsCliCommand(
        name: 'openapi',
        description: 'Generate models and a typed client from an OpenAPI document.',
        options: <String>[
          '    --dry-run      List what would be written, and write nothing.',
          '    --overwrite    Replace files that are already there.',
        ],
      ),
      DocsCliCommand(
        name: 'postman',
        description: 'Generate a typed client from a Postman collection export.',
        options: <String>[
          '    --dry-run      List what would be written, and write nothing.',
          '    --overwrite    Replace files that are already there.',
        ],
      ),
    ],
  ),
  DocsCliCommand(
    name: 'infra',
    description: 'Provision and check the hosts declared under dartvel.infra.',
    subcommands: <DocsCliCommand>[
      DocsCliCommand(
        name: 'check',
        description: 'Report drift, stopped services, failing certificate renewal and stale restores as DV-INFRA findings.',
        options: <String>[
          '    --json    Print findings as JSON.',
        ],
      ),
      DocsCliCommand(
        name: 'plan',
        description: 'Show the steps that would converge each host on dartvel.infra.<env>.',
        options: <String>[
          '    --out     Write the plan to this file for `provision --plan`.',
        ],
      ),
      DocsCliCommand(
        name: 'provision',
        description: 'Apply the plan to each host and verify the host matches afterwards.',
        options: <String>[
          '    --plan                   Apply this plan file, and only while it is still the plan.',
          '    --confirm-destructive    Apply steps that remove units, files or credentials without asking.',
        ],
      ),
    ],
  ),
  DocsCliCommand(
    name: 'init',
    description: 'Add Dartvel to an existing project: the dependency and the dartvel: key, nothing else.',
    options: <String>[
      '    --dry-run    Print the compatibility report and the pubspec changes; write nothing.',
      '-y, --yes        Apply without asking. Required where there is no terminal to ask at.',
    ],
  ),
  DocsCliCommand(
    name: 'inspect',
    description: 'Inspect the project graph: routes, models, functions and jobs.',
    options: <String>[
      '    --json              Emit the graph as JSON. The shape is versioned by graphVersion.',
      '    --device-profile    For kiosk: the device profile a build would select, whose kiosk entry goes over the section.',
    ],
  ),
  DocsCliCommand(
    name: 'key',
    description: 'The application key: generate, rotate or inspect it in the platform key store.',
    subcommands: <DocsCliCommand>[
      DocsCliCommand(
        name: 'generate',
        description: 'Generate the application key. Refuses if one exists.',
        options: <String>[
          '    --store    Where the key is held. auto uses the Secret Service when one answers, else a file only you can read.',
          '               [auto (default), secret-service, file]',
          '    --home     The home directory for the file store. Defaults to yours.',
          '    --app      The application the key belongs to. Defaults to the pubspec name here.',
        ],
      ),
      DocsCliCommand(
        name: 'rotate',
        description: 'Replace the application key, recording both fingerprints.',
        options: <String>[
          '    --store    Where the key is held. auto uses the Secret Service when one answers, else a file only you can read.',
          '               [auto (default), secret-service, file]',
          '    --home     The home directory for the file store. Defaults to yours.',
          '    --app      The application the key belongs to. Defaults to the pubspec name here.',
        ],
      ),
      DocsCliCommand(
        name: 'status',
        description: 'Say whether there is a key, where it is held, and its fingerprint.',
        options: <String>[
          '    --store    Where the key is held. auto uses the Secret Service when one answers, else a file only you can read.',
          '               [auto (default), secret-service, file]',
          '    --home     The home directory for the file store. Defaults to yours.',
          '    --app      The application the key belongs to. Defaults to the pubspec name here.',
        ],
      ),
    ],
  ),
  DocsCliCommand(
    name: 'logs',
    description: 'Read the recent log records of a running Dartvel server.',
    options: <String>[
      '    --url      Base URL of the running Dartvel server to read from.',
      '               (defaults to "http://localhost:8080")',
      '    --limit    Show only the most recent N entries.',
      '    --json     Print each entry as the JSON the server sent, for piping.',
    ],
  ),
  DocsCliCommand(
    name: 'mcp',
    description: 'Serve Dartvel\'s project-graph inspectors to a coding agent over MCP.',
  ),
  DocsCliCommand(
    name: 'metrics',
    description: 'Fetch the /metrics endpoint of a running Dartvel server.',
    options: <String>[
      '    --url     Base URL of the running Dartvel server to read /metrics from.',
      '              (defaults to "http://localhost:8080")',
    ],
  ),
  DocsCliCommand(
    name: 'modules',
    description: 'Inspect mounted modules, publish a signed module, and pin what is mounted.',
    subcommands: <DocsCliCommand>[
      DocsCliCommand(
        name: 'list',
        description: 'The modules this application mounts.',
      ),
      DocsCliCommand(
        name: 'manifest',
        description: 'Write the manifest this module publishes about itself.',
        options: <String>[
          '    --out       Where to write the manifest.',
          '                (defaults to "build/module-manifest.json")',
          '    --key       A file holding the 32-byte P-256 signing key, base64url. Without it the manifest is written unsigned.',
          '    --key-id    The name a parent knows the signing key by.',
        ],
      ),
      DocsCliCommand(
        name: 'pin',
        description: 'Pin the version, digest, signing key and publisher of mounted modules into dartvel.module.lock.',
        options: <String>[
          '    --allow-downgrade    Pin a version older than the current pin. Without it, a rollback is refused.',
        ],
      ),
      DocsCliCommand(
        name: 'publish',
        description: 'Check a module\'s declared capabilities against its code, sign it, and publish it to pub.dev.',
        options: <String>[
          '    --key          A file holding the 32-byte P-256 signing key, base64url.',
          '    --key-id       Your name for the signing key.',
          '    --publisher    The verified pub.dev publisher, as a claim. Parents never trust it for itself: they pin what the registry verifies.',
          '    --dry-run      Sign, then run dart pub publish --dry-run.',
          '    --sign-only    Sign, and leave publishing to you.',
        ],
      ),
    ],
  ),
  DocsCliCommand(
    name: 'plugin',
    description: 'Manage Dartvel plugins.',
    subcommands: <DocsCliCommand>[
      DocsCliCommand(
        name: 'add',
        description: 'Add a plugin to your project.',
        options: <String>[
          '-n, --name    Plugin name (e.g., auth, analytics)',
        ],
      ),
      DocsCliCommand(
        name: 'list',
        description: 'List available plugins.',
      ),
      DocsCliCommand(
        name: 'remove',
        description: 'Remove a plugin from your project.',
      ),
    ],
  ),
  DocsCliCommand(
    name: 'prerender',
    description: 'Prerender routes to static HTML for SEO.',
    options: <String>[
      '-p, --port        Port the app is serving on',
      '                  (defaults to "8080")',
      '-o, --output      Output directory',
      '                  (defaults to "build/web")',
      '    --base-url    Canonical base URL for sitemap.xml and robots.txt',
      '                  (defaults to "http://localhost:8080")',
    ],
  ),
  DocsCliCommand(
    name: 'preview',
    description: 'Preview the production build locally, or manage preview environments (create, list, open, destroy, sweep).',
  ),
  DocsCliCommand(
    name: 'privacy',
    description: 'Check subject paths and retention, and export, erase or plan a retention sweep over the application database.',
    subcommands: <DocsCliCommand>[
      DocsCliCommand(
        name: 'check',
        description: 'List every model with its subject path and retention.',
      ),
      DocsCliCommand(
        name: 'erase',
        description: 'Erase a subject\'s records: delete them, or keep and anonymize the ones a declared retention holds.',
        options: <String>[
          '    --subject    The subject, as model:id -- user:1042.',
          '    --reason     Why, as the audit record will say.',
          '    --yes        Erase without asking. Required where nobody can be asked.',
        ],
      ),
      DocsCliCommand(
        name: 'export',
        description: 'Write a subject\'s records, as JSON, to the path --out names.',
        options: <String>[
          '    --subject    The subject, as model:id -- user:1042.',
          '    --out        Where to write the archive. Required.',
          '    --force      Replace a file already at --out.',
        ],
      ),
      DocsCliCommand(
        name: 'retention',
        description: 'Preview the next retention sweep (--plan). Sweeps run as a job.',
        options: <String>[
          '    --plan    Say what the next sweep would delete or anonymize, changing nothing.',
        ],
      ),
    ],
  ),
  DocsCliCommand(
    name: 'publish',
    description: 'Publish a built application to a store (play, appstore, testflight, firebase).',
    options: <String>[
      '    --dry-run     Print the command that would run, and run nothing.',
      '    --artifact    The file to upload, when it is not where the build puts it.',
    ],
  ),
  DocsCliCommand(
    name: 'queue',
    description: 'Work and inspect Dartvel queues.',
    subcommands: <DocsCliCommand>[
      DocsCliCommand(
        name: 'failed',
        description: 'List dead-lettered jobs for a queue.',
        options: <String>[
          '    --queue    Queue name.',
          '               (defaults to "default")',
        ],
      ),
      DocsCliCommand(
        name: 'flush',
        description: 'Remove pending and failed jobs for a queue.',
        options: <String>[
          '    --queue    Queue name.',
          '               (defaults to "default")',
        ],
      ),
      DocsCliCommand(
        name: 'retry',
        description: 'Retry a dead-lettered job by id.',
      ),
      DocsCliCommand(
        name: 'work',
        description: 'Run queued jobs for a queue.',
        options: <String>[
          '    --queue       Queue name to work.',
          '                  (defaults to "default")',
          '    --max-jobs    Maximum jobs to reserve and process.',
          '                  (defaults to "1")',
        ],
      ),
    ],
  ),
  DocsCliCommand(
    name: 'routes',
    description: 'Generate routes and client artifacts.',
    options: <String>[
      '    --render    The rendering backends this build links (gui, terminal, or both). `dartvel build` passes what it resolved from the -cli/-tui suffix and dartvel.terminal; run by hand it defaults to gui.',
    ],
  ),
  DocsCliCommand(
    name: 'sh',
    description: 'Run a cross-platform command with Dartvel escaping, env, and glob handling.',
    options: <String>[
      '-p, --[no-]print    Print the resolved executable and arguments before running.',
      '-q, --[no-]quiet    Do not stream child process stdout/stderr.',
      '    --env           Environment override in KEY=value form. Can be repeated.',
    ],
  ),
  DocsCliCommand(
    name: 'spec',
    description: 'Inspect the specification status index.',
    subcommands: <DocsCliCommand>[
      DocsCliCommand(
        name: 'status',
        description: 'Summarise docs/spec-status.json: what is built and what is not.',
        options: <String>[
          '    --contracts    List the frozen surfaces that are not finished.',
        ],
      ),
    ],
  ),
  DocsCliCommand(
    name: 'task',
    description: 'Run a task from pubspec.yaml dartvel.tasks.',
    options: <String>[
      '-l, --[no-]list     List available Dartvel tasks.',
      '-p, --[no-]print    Print the resolved executable and arguments before running.',
      '-q, --[no-]quiet    Do not stream child process stdout/stderr.',
    ],
  ),
  DocsCliCommand(
    name: 'test',
    description: 'Run Dartvel tests.',
    options: <String>[
      '    --[no-]flutter           Force flutter test instead of dart test.',
      '    --[no-]dart              Force dart test instead of flutter test.',
      '    --[no-]watch             Run tests in watch mode when supported by the selected runner.',
      '    --[no-]dry-run           Print the resolved test command without executing it.',
      '    --total-shards           Total number of CI shards running this test suite.',
      '    --shard-index            Zero-based index of this CI shard.',
      '    --[no-]isolate           Run tests with per-file isolation by forcing single concurrency.',
      '    --[no-]update-goldens    Update golden snapshot files for golden UI tests.',
      '    --reporter               Pass a reporter to the selected test runner.',
    ],
  ),
  DocsCliCommand(
    name: 'traces',
    description: 'Read the recent trace spans of a running Dartvel server.',
    options: <String>[
      '    --url      Base URL of the running Dartvel server to read from.',
      '               (defaults to "http://localhost:8080")',
      '    --limit    Show only the most recent N entries.',
      '    --json     Print each entry as the JSON the server sent, for piping.',
    ],
  ),
  DocsCliCommand(
    name: 'update',
    description: 'Update the Dartvel CLI to the latest published release.',
    options: <String>[
      '    --check    Report whether an update exists without installing it.',
      '    --force    Reinstall even when the running version is already the latest.',
    ],
  ),
  DocsCliCommand(
    name: 'updates',
    description: 'Manage Over-The-Air (OTA) updates.',
    subcommands: <DocsCliCommand>[
      DocsCliCommand(
        name: 'patch',
        description: 'Create Shorebird patches for target platforms.',
        options: <String>[
          '-p, --platform           Target platform. Repeat to run multiple platforms.',
          '                         [android (default), ios (default)]',
          '    --[no-]dry-run       Print Shorebird commands without executing them.',
          '    --release-version    Existing release version to patch.',
        ],
      ),
      DocsCliCommand(
        name: 'push',
        description: 'Alias for updates patch. Use updates patch in new scripts.',
        options: <String>[
          '-p, --platform           Target platform. Repeat to run multiple platforms.',
          '                         [android (default), ios (default)]',
          '    --[no-]dry-run       Print Shorebird commands without executing them.',
          '    --release-version    Existing release version to patch.',
        ],
      ),
      DocsCliCommand(
        name: 'release',
        description: 'Create Shorebird releases for target platforms.',
        options: <String>[
          '-p, --platform        Target platform. Repeat to run multiple platforms.',
          '                      [android (default), ios (default)]',
          '    --[no-]dry-run    Print Shorebird commands without executing them.',
        ],
      ),
      DocsCliCommand(
        name: 'rollback',
        description: 'Roll back a Shorebird patch track.',
        options: <String>[
          '    --release-version (mandatory)    Release version containing the patch.',
          '    --patch-number (mandatory)       Patch number to move to the selected track.',
          '    --track                          Target Shorebird track.',
          '                                     (defaults to "stable")',
          '    --[no-]dry-run                   Print the Shorebird command without executing it.',
        ],
      ),
    ],
  ),
  DocsCliCommand(
    name: 'version',
    description: 'Print the current version of Dartvel CLI.',
  ),
  DocsCliCommand(
    name: 'webos',
    description: 'Inspect and verify assembled webOS packages.',
    subcommands: <DocsCliCommand>[
      DocsCliCommand(
        name: 'verify-package',
        description: 'Fail unless the package holds everything appinfo.json names.',
      ),
    ],
  ),
];

/// The .htaccess dartvel build web writes, line by line.
const List<String> kApacheConfig = <String>[
  '# Written by dartvel build web. Edits are kept: this file is only created when',
  '# it is absent.',
  '',
  '<IfModule mod_rewrite.c>',
  '  RewriteEngine On',
  '  RewriteBase /',
  '',
  '  # Served as themselves. Without these the fallback below swallows every',
  '  # asset and the page loads index.html as its own JavaScript.',
  '  RewriteCond %{REQUEST_FILENAME} -f [OR]',
  '  RewriteCond %{REQUEST_FILENAME} -d',
  '  RewriteRule ^ - [L]',
  '',
  '  # Everything else is a route. The application reads the URL and renders it.',
  '  RewriteRule . /index.html [L]',
  '</IfModule>',
  '',
  '# Where mod_rewrite is off. The rewrite above sends unknown paths to the',
  '# application shell, which is right for a route the router knows and wrong for',
  '# one nothing does -- and it does not run at all on a host without',
  '# mod_rewrite, where this is what a visitor sees instead of the server\'s own',
  '# branding.',
  'ErrorDocument 404 /404/index.html',
  '',
  '# The Universal Links document has no extension for AddType to match, and iOS',
  '# refuses it as anything but JSON.',
  '<Files "apple-app-site-association">',
  '  ForceType application/json',
  '</Files>',
  '',
  '<IfModule mod_mime.c>',
  '  # instantiateStreaming refuses a wasm module served as anything else.',
  '  AddType application/wasm .wasm',
  '  AddType application/javascript .js',
  '  AddType application/json .json',
  '</IfModule>',
  '',
  '<IfModule mod_headers.c>',
  '  # Not cached, because Flutter does not content-hash any of these: a build',
  '  # from today and a build from last year both produce a file called',
  '  # main.dart.js. A blanket immutable rule over *.js froze the site for every',
  '  # returning visitor -- no error, no way for them to know, and no way out',
  '  # from their side once the service worker was cached too.',
  '  <FilesMatch "^(index\\.html|main\\.dart\\.js|flutter_bootstrap\\.js|flutter_service_worker\\.js|version\\.json|manifest\\.json)\$">',
  '    Header set Cache-Control "no-cache, must-revalidate"',
  '  </FilesMatch>',
  '',
  '  # These do carry a version in their path, and they are the large ones.',
  '  <FilesMatch "^(canvaskit/|assets/).*\\.(js|wasm|woff2|otf|ttf|png|jpg|svg|json)\$">',
  '    Header set Cache-Control "public, max-age=31536000, immutable"',
  '  </FilesMatch>',
  '</IfModule>',
];
