/// What every described API shares: the package it becomes.
///
/// OpenAPI, GraphQL and gRPC are three documents and one outcome. A described
/// API produces a **pure Dart module** -- no foreign runtime, no artifact and
/// no binding of any kind -- whose calls go over `DV.Http` against a host
/// declared in the generated package's own pubspec. So the retries, timeouts,
/// circuit breaking and secret resolution are the ones the specification
/// already defines rather than a second set written into generated code.
///
/// The pubspec, the naming and the refusal live here because two generators
/// writing them separately is two generators that drift.
library;

import 'dart:convert';

/// Thrown when a document cannot become a module.
class DVDescribedApiRefused implements Exception {
  const DVDescribedApiRefused(this.message);

  final String message;

  @override
  String toString() => message;
}

/// A module package, ready to be written to disk.
class DVGeneratedModule {
  const DVGeneratedModule({
    required this.id,
    required this.packageName,
    required this.host,
    required this.files,
  });

  /// What the parent knows it by: `DV.Modules.<id>`.
  final String id;

  /// The Dart package name, which is [id] in the spelling pub wants.
  final String packageName;

  /// The `dartvel.http.hosts` entry the calls go through.
  final String host;

  /// Path inside the package, to contents. Ordered, so two runs on one
  /// document produce the same package rather than the same set of files.
  final Map<String, String> files;
}

/// The module's pubspec: what it is called, that it is a module, and the one
/// host its calls go to.
String dvDescribedApiPubspec({
  required String packageName,
  required String moduleId,
  required String hostName,
  required String baseUrl,
  required String title,
  required String from,
}) =>
    '''
# GENERATED by dartvel add from $from.
#
# A described API is a source, not a binding: this package is pure Dart and
# its calls go over DV.Http, against the host declared below.
name: $packageName
description: ${dvYamlScalar('$title, as a Dartvel module.')}
publish_to: none
version: 0.0.1

environment:
  sdk: ">=3.13.0 <4.0.0"

dependencies:
  dartvel_core: any

dartvel:
  module:
    id: $moduleId
    kind: describedApi
  http:
    hosts:
      $hostName:
        baseUrl: ${dvYamlScalar(baseUrl)}
''';

/// A value from the document, written into YAML so it stays one scalar.
///
/// A JSON string is a valid YAML double-quoted scalar, and the values here
/// are somebody else's: a title holding a colon or a URL holding a `#` would
/// otherwise write a pubspec that does not parse, or one that parses into
/// something other than what the document said.
String dvYamlScalar(String value) => jsonEncode(value);

/// The words in [text], with a camel-cased run split apart.
List<String> dvWords(String text) => text
    .replaceAllMapped(RegExp('([a-z0-9])([A-Z])'),
        (Match m) => '${m.group(1)} ${m.group(2)}')
    .split(RegExp(r'[^A-Za-z0-9]+'))
    .where((String part) => part.isNotEmpty)
    .toList();

/// `orderLines`, for a Dart member.
String dvCamel(String text) {
  final List<String> parts = dvWords(text);
  if (parts.isEmpty) return text;
  final StringBuffer out = StringBuffer(parts.first.toLowerCase());
  for (final String part in parts.skip(1)) {
    out.write(part[0].toUpperCase());
    out.write(part.substring(1));
  }
  final String name = out.toString();
  return RegExp(r'^[0-9]').hasMatch(name) ? 'n$name' : name;
}

/// `OrderLines`, for a Dart type.
String dvClassName(String text) {
  final List<String> parts = dvWords(text);
  if (parts.isEmpty) return text;
  return parts
      .map((String part) => '${part[0].toUpperCase()}${part.substring(1)}')
      .join();
}

/// `order_lines`, for a package or a file.
String dvSnake(String text) =>
    dvWords(text).map((String part) => part.toLowerCase()).join('_');

/// The exception a generated module throws for a call the service refused.
String dvDescribedApiExceptionSource(String moduleId) {
  final String name = '${dvClassName(moduleId)}Exception';
  return '''
/// A call this module made that the service refused.
class $name implements Exception {
  const $name(this.operation, this.status, [this.detail]);

  /// The operation, as the document names it.
  final String operation;

  /// The status the call came back with.
  final int status;

  /// What the service said was wrong, where it says so in a field meant to
  /// be read. Never the response body: a service's error text is not this
  /// application's to carry around, and a body can hold anything at all.
  final String? detail;

  @override
  String toString() => detail == null
      ? '\$operation answered \$status.'
      : '\$operation answered \$status: \$detail';
}
''';
}
