/// The `dartvel:` object of a project, whichever way it is written.
///
/// `dartvel:` is either a YAML map in `pubspec.yaml` or the path of a Dart
/// file whose public class extends `DartvelConfig` (package:dartvel_core/config.dart).
/// Both end up as the same map here: the Dart class is run once and asked for
/// `toPubspec()`, so every reader of the configuration sees one shape and a
/// key cannot work in one spelling and be ignored in the other.
library;

import 'dart:convert';
import 'dart:io';

import 'package:path/path.dart' as p;
import 'package:yaml/yaml.dart';

/// What reading the section found.
class DVDartvelSection {
  const DVDartvelSection(this.values, {this.problems = const <String>[], this.fromDartConfig});

  /// The `dartvel:` object. Empty when the project has none.
  final Map<Object?, Object?> values;

  /// Why the Dart config could not be read, when it could not.
  final List<String> problems;

  /// The Dart config file the values came from, or null for YAML.
  final String? fromDartConfig;
}

/// Reads the `dartvel:` section of the project at [root]. Never throws.
DVDartvelSection dvDartvelSection(String root) {
  final File pubspec = File(p.join(root, 'pubspec.yaml'));
  if (!pubspec.existsSync()) return const DVDartvelSection(<Object?, Object?>{});
  Object? document;
  try {
    document = loadYaml(pubspec.readAsStringSync());
  } on Object {
    return const DVDartvelSection(<Object?, Object?>{});
  }
  final Object? dartvel = document is Map ? document['dartvel'] : null;
  if (dartvel is Map) return DVDartvelSection(dartvel);
  if (dartvel is String) return dvEvaluateDartConfig(root, dartvel);
  return const DVDartvelSection(<Object?, Object?>{});
}

/// The `dartvel:` object a Dart config file describes.
///
/// The class is imported by a small program the build writes under
/// `.dart_tool/dartvel/` and asked for `toPubspec()`. The answer is cached
/// against the file's size and modification time, so a build reads it once.
DVDartvelSection dvEvaluateDartConfig(String root, String relativePath) {
  final File configFile = File(p.join(root, relativePath));
  if (!configFile.existsSync()) {
    return DVDartvelSection(const <Object?, Object?>{},
        problems: <String>['dartvel: points at $relativePath, which is not there.'], fromDartConfig: relativePath);
  }
  final String source = configFile.readAsStringSync();
  final Match? declaration = RegExp(r'class\s+(?:const\s+)?([A-Z][A-Za-z0-9_]*)(?:\s*\([^)]*\))?\s+extends\s+DartvelConfig\b').firstMatch(source);
  if (declaration == null) {
    return DVDartvelSection(const <Object?, Object?>{},
        problems: <String>['$relativePath must declare a public class extending DartvelConfig.'], fromDartConfig: relativePath);
  }
  final String className = declaration.group(1)!;
  final Directory work = Directory(p.join(root, '.dart_tool', 'dartvel'))..createSync(recursive: true);
  final FileStat stat = configFile.statSync();
  final String stamp = '${stat.size}:${stat.modified.millisecondsSinceEpoch}:$className';
  final File cache = File(p.join(work.path, 'dart_config.json'));
  if (cache.existsSync()) {
    try {
      final Object? cached = jsonDecode(cache.readAsStringSync());
      if (cached is Map && cached['stamp'] == stamp && cached['values'] is Map) {
        return DVDartvelSection(cached['values'] as Map<Object?, Object?>, fromDartConfig: relativePath);
      }
    } on FormatException {
      // A cache that will not parse is rebuilt below.
    }
  }
  final File probe = File(p.join(work.path, 'dart_config_probe.dart'));
  final String importPath = p.relative(configFile.path, from: work.path).replaceAll(r'\', '/');
  probe.writeAsStringSync('''
// GENERATED by dartvel. Reads the project's Dart config as the build sees it.
import 'dart:convert';
import '$importPath' as config;

void main() => print(jsonEncode(const config.$className().toPubspec()));
''');
  // The VM running this when it is the Dart SDK's, else `dart` from PATH: a
  // compiled dartvel binary is not a Dart VM and cannot run a program.
  final String dart = p.basenameWithoutExtension(Platform.resolvedExecutable) == 'dart' ? Platform.resolvedExecutable : 'dart';
  final ProcessResult result = Process.runSync(dart, <String>['run', probe.path], workingDirectory: root, runInShell: Platform.isWindows);
  if (result.exitCode != 0) {
    return DVDartvelSection(const <Object?, Object?>{},
        problems: <String>[
          'Could not read $relativePath: ${'${result.stderr}'.trim().split('\n').take(6).join(' ')} '
              '(the class needs a const constructor with no arguments).',
        ],
        fromDartConfig: relativePath);
  }
  final String output = '${result.stdout}'.trim().split('\n').last;
  try {
    final Object? values = jsonDecode(output);
    if (values is! Map) throw const FormatException('not an object');
    cache.writeAsStringSync(jsonEncode(<String, Object?>{'stamp': stamp, 'values': values}));
    return DVDartvelSection(values, fromDartConfig: relativePath);
  } on FormatException {
    return DVDartvelSection(const <Object?, Object?>{},
        problems: <String>['$relativePath did not describe a dartvel: object.'], fromDartConfig: relativePath);
  }
}

/// The package name in the project's pubspec, or null.
String? dvPackageName(String root) {
  final File pubspec = File(p.join(root, 'pubspec.yaml'));
  if (!pubspec.existsSync()) return null;
  try {
    final Object? document = loadYaml(pubspec.readAsStringSync());
    final Object? name = document is Map ? document['name'] : null;
    return name is String ? name : null;
  } on Object {
    return null;
  }
}
