// GENERATED by dartvel add from path:vendor/slugify.
//
// Runs on the Dart VM, which is the backend environment.
import 'package:dv_slugify_module/dv_slugify_module.dart';
import 'package:dartvel_core/dartvel.dart';
import 'package:test/test.dart';

void main() {
  test('the module is its declared surface', () {
    expect(const SlugifyModule(), isNotNull);
  });
}
