// Writes the CLI reference from the CLI's own command table.
//
//   dart run tool/cli_reference.dart
//
// The table is dartvelCommandRunner() in dartvel_cli, the same object
// `dartvel --help` prints. The reference lands in
// lib/components/docs_cli_reference.dart, because the web build cannot import
// the CLI, and test/docs_cli_reference_test.dart fails when it is stale: add a
// command or a flag and the test names this script.
import 'dart:io';

import 'package:args/command_runner.dart';
import 'package:dartvel_cli/dartvel_impl.dart';
// The .htaccess dartvel build web writes, shown on the static hosting page.
// ignore: implementation_imports
import 'package:dartvel_cli/src/build/server_config.dart' show dvApacheConfig;

/// The generated file, relative to the site.
const String kCliReferenceOutput = 'lib/components/docs_cli_reference.dart';

/// The Dart source of the reference, from the live command table.
String cliReferenceSource() {
  final CommandRunner<void> runner = dartvelCommandRunner();
  final StringBuffer out = StringBuffer()
    ..writeln('// GENERATED by tool/cli_reference.dart from the dartvel command table.')
    ..writeln('// Run: dart run tool/cli_reference.dart')
    ..writeln()
    ..writeln("import 'docs_cli_command.dart';")
    ..writeln()
    ..writeln('/// Every visible dartvel command, alphabetically.')
    ..writeln('const List<DocsCliCommand> kCliCommands = <DocsCliCommand>[');
  for (final Command<void> command in _visible(runner.commands)) {
    _write(out, command, '  ');
  }
  out.writeln('];');
  out
    ..writeln()
    ..writeln('/// The .htaccess dartvel build web writes, line by line.')
    ..writeln('const List<String> kApacheConfig = <String>[');
  final List<String> apache = dvApacheConfig().split('\n');
  while (apache.isNotEmpty && apache.last.isEmpty) {
    apache.removeLast();
  }
  for (final String line in apache) {
    out.writeln('  ${_literal(line)},');
  }
  out.writeln('];');
  return out.toString();
}

List<Command<void>> _visible(Map<String, Command<void>> commands) {
  final Map<String, Command<void>> byName = <String, Command<void>>{};
  for (final Command<void> c in commands.values) {
    if (!c.hidden) byName[c.name] = c;
  }
  final List<String> names = byName.keys.toList()..sort();
  return <Command<void>>[for (final String n in names) byName[n]!];
}

void _write(StringBuffer out, Command<void> command, String indent) {
  final List<String> usage = command.argParser.usage
      .split('\n')
      .where((String l) => !l.contains('Print this usage information.'))
      .toList();
  out
    ..writeln('${indent}DocsCliCommand(')
    ..writeln("$indent  name: ${_literal(command.name)},")
    ..writeln("$indent  description: ${_literal(command.description)},");
  if (command.aliases.isNotEmpty) {
    out.writeln(
        "$indent  aliases: <String>[${command.aliases.map(_literal).join(', ')}],");
  }
  if (usage.any((String l) => l.trim().isNotEmpty)) {
    out.writeln('$indent  options: <String>[');
    for (final String line in usage) {
      out.writeln('$indent    ${_literal(line)},');
    }
    out.writeln('$indent  ],');
  }
  final List<Command<void>> subs = _visible(command.subcommands);
  if (subs.isNotEmpty) {
    out.writeln('$indent  subcommands: <DocsCliCommand>[');
    for (final Command<void> sub in subs) {
      _write(out, sub, '$indent    ');
    }
    out.writeln('$indent  ],');
  }
  out.writeln('$indent),');
}

String _literal(String text) {
  final String escaped = text
      .replaceAll(r'\', r'\\')
      .replaceAll("'", r"\'")
      .replaceAll(r'$', r'\$')
      .replaceAll('\n', r'\n');
  return "'$escaped'";
}

void main() {
  File(kCliReferenceOutput).writeAsStringSync(cliReferenceSource());
  stdout.writeln('wrote $kCliReferenceOutput');
}
