// Copies the docs' code samples out of examples/docs_samples.
//
//   dart run tool/docs_samples.dart
//
// A sample is the lines between `// docs:start <name>` and `// docs:end` in
// any Dart file of that project, or `# docs:start` and `# docs:end` in its
// pubspec.yaml. CI generates the project's client, analyzes
// it and runs its tests, so a sample shown on the site has compiled. The
// copy lands in lib/components/docs_samples.dart, because a web build cannot
// read files, and test/docs_samples_test.dart fails when the copy is stale.
import 'dart:io';

/// The project the samples are compiled in, from the site's directory.
const String kDocsSamplesProject = '../../examples/docs_samples';

/// The generated file, relative to the site.
const String kDocsSamplesOutput = 'lib/components/docs_samples.dart';

/// Every sample in [project], by name, with its common indent removed.
Map<String, List<String>> readDocsSamples(Directory project) {
  final Map<String, List<String>> samples = <String, List<String>>{};
  final List<File> files = <File>[
    for (final String dir in <String>['lib', 'test'])
      if (Directory('${project.path}/$dir').existsSync())
        for (final FileSystemEntity e
            in Directory('${project.path}/$dir').listSync(recursive: true))
          if (e is File &&
              e.path.endsWith('.dart') &&
              !e.path.contains('dartvel_client'))
            e,
    // The dartvel: blocks the docs show, which generation reads and checks.
    File('${project.path}/pubspec.yaml'),
  ]..sort((File a, File b) => a.path.compareTo(b.path));

  final RegExp start = RegExp(r'^\s*(?://|#) docs:start ([a-z0-9-]+)\s*$');
  final RegExp end = RegExp(r'^\s*(?://|#) docs:end\s*$');
  for (final File file in files) {
    String? open;
    List<String> lines = <String>[];
    int number = 0;
    for (final String line in file.readAsLinesSync()) {
      number++;
      final Match? s = start.firstMatch(line);
      if (s != null) {
        if (open != null) {
          throw StateError('${file.path}:$number opens ${s[1]} inside $open');
        }
        open = s[1];
        lines = <String>[];
        continue;
      }
      if (end.hasMatch(line)) {
        if (open == null) {
          throw StateError('${file.path}:$number closes nothing');
        }
        if (samples.containsKey(open)) {
          throw StateError('${file.path}:$number repeats the sample $open');
        }
        samples[open] = _dedent(lines);
        open = null;
        continue;
      }
      if (open != null) lines.add(line);
    }
    if (open != null) throw StateError('${file.path} never closes $open');
  }
  return samples;
}

List<String> _dedent(List<String> lines) {
  int indent = 1 << 20;
  for (final String line in lines) {
    if (line.trim().isEmpty) continue;
    final int lead = line.length - line.trimLeft().length;
    if (lead < indent) indent = lead;
  }
  return <String>[
    for (final String line in lines)
      line.trim().isEmpty ? '' : line.substring(indent),
  ];
}

/// The Dart source of lib/components/docs_samples.dart for [samples].
String docsSamplesSource(Map<String, List<String>> samples) {
  final StringBuffer out = StringBuffer()
    ..writeln('// GENERATED by tool/docs_samples.dart from examples/docs_samples.')
    ..writeln('// Edit the sample there, then run: dart run tool/docs_samples.dart')
    ..writeln()
    ..writeln('/// The docs code samples, each compiled in examples/docs_samples.')
    ..writeln('const Map<String, List<String>> kDocsSamples = <String, List<String>>{');
  final List<String> names = samples.keys.toList()..sort();
  for (final String name in names) {
    out.writeln("  '$name': <String>[");
    for (final String line in samples[name]!) {
      out.writeln('    ${_literal(line)},');
    }
    out.writeln('  ],');
  }
  out.writeln('};');
  return out.toString();
}

String _literal(String line) {
  final String escaped = line
      .replaceAll(r'\', r'\\')
      .replaceAll("'", r"\'")
      .replaceAll(r'$', r'\$')
      // Escaped, because Dartvel's generators find annotations by reading
      // source text: a sample holding @DVFunctionalWidget() in a string was
      // generated into the site as a real widget.
      .replaceAll('@', r'\u0040');
  return "'$escaped'";
}

void main() {
  final Map<String, List<String>> samples =
      readDocsSamples(Directory(kDocsSamplesProject));
  File(kDocsSamplesOutput).writeAsStringSync(docsSamplesSource(samples));
  stdout.writeln('${samples.length} samples written to $kDocsSamplesOutput');
}
