include: package:lints/recommended.yaml

analyzer:
  exclude:
    - ".dart_tool/**"

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - avoid_print
