// Writes docs/spec-gaps.md: every section of NEW_SPEC.md, whether it is
// built, and what is still missing, from docs/spec-status.json.
//
//   dart tool/spec_gaps.dart
//
// The status file is the record; this is a view of it for a reader who
// wants the gaps in one table rather than one JSON entry at a time. Nothing
// here is written by hand, so the table cannot drift from the file.
//
// dart:io only, so it runs from a checkout with nothing resolved.
import 'dart:convert';
import 'dart:io';

void main() {
  final Map<String, Object?> status = jsonDecode(
          File('docs/spec-status.json').readAsStringSync())
      as Map<String, Object?>;
  final List<Map<String, Object?>> sections = <Map<String, Object?>>[
    for (final Object? s in status['sections']! as List<Object?>)
      (s! as Map).cast<String, Object?>(),
  ].where((Map<String, Object?> s) => s['kind'] != 'narrative').toList();

  final Map<String, int> counts = <String, int>{};
  for (final Map<String, Object?> s in sections) {
    counts['${s['status']}'] = (counts['${s['status']}'] ?? 0) + 1;
  }

  final StringBuffer out = StringBuffer()
    ..writeln('# NEW_SPEC.md: what is built and what is not')
    ..writeln()
    ..writeln('Generated by `dart tool/spec_gaps.dart` from '
        '`docs/spec-status.json`, which `dart run tool/spec_status_check.dart` '
        'validates against the evidence it names. Do not edit this file; edit '
        'the status file and regenerate.')
    ..writeln()
    ..writeln('${sections.length} sections carry a status: '
        '${counts.entries.map((MapEntry<String, int> e) => '${e.value} ${e.key}').join(', ')}.')
    ..writeln()
    ..writeln('"Partial" means some of the section is built and tested and '
        'the rest is named below; "Designed" means specified and not built. '
        'The missing column is the status file\'s own account, shortened to '
        'what it says is absent.')
    ..writeln()
    ..writeln('| Section | Stability | Status | Evidence | Missing |')
    ..writeln('|---|---|---|---|---|');
  for (final Map<String, Object?> s in sections) {
    final List<Object?> evidence = s['evidence'] as List<Object?>? ?? <Object?>[];
    out.writeln('| ${s['section']} | ${s['stability'] ?? ''} | ${s['status']} | '
        '${evidence.length} file${evidence.length == 1 ? '' : 's'} | '
        '${_missing(s)} |');
  }
  File('docs/spec-gaps.md').writeAsStringSync(out.toString());
  stdout.writeln('docs/spec-gaps.md: ${sections.length} sections.');
}

/// What the entry says is absent, or nothing for a shipped section.
String _missing(Map<String, Object?> s) {
  if (s['status'] == 'Shipped') return '';
  final String absent = '${s['absent'] ?? ''}'.replaceAll('\n', ' ').replaceAll('|', '/');
  final int at = absent.lastIndexOf(RegExp(r'Absent:|Not built:|Newly specified and unbuilt:|Still absent:'));
  final String tail = at < 0 ? absent : absent.substring(at);
  return tail.length > 400 ? '${tail.substring(0, 397)}...' : tail;
}
