// GENERATED by dartvel add from path:vendor/slugify. Do not edit.
//
// The environment is chosen when the application is compiled:
// a browser build imports the web carrier, a device build the
// native one, the backend the backend one. Nothing a carrier
// does not need reaches that environment's build.
library;

import 'src/carrier_backend.dart'
    if (dart.library.js_interop) 'src/carrier_web.dart'
    if (dart.library.ui) 'src/carrier_native.dart' as carrier;
export 'package:slugify/slugify.dart';

/// path:vendor/slugify, as the `slugify` module.
///
/// Reached as `DV.Modules.slugify`. What each operation
/// does in each environment is declared in this package's
/// pubspec and listed in its README.
class SlugifyModule {
  const SlugifyModule();

  /// [text] as a URL slug: lowercase words joined by [separator].
  String slugify(String text, {String separator = '-'}) =>
      carrier.slugify(text, separator: separator);
}
