/// What `dartvel build android --profile development` writes so the build can
/// be paired with `dartvel dev --dev-client` and hot reloaded over the network.
///
/// A Flutter debug build already runs the Dart VM service: it is how
/// `flutter run` reloads an app over USB. On a phone scanning a QR code there
/// is no USB, and the VM service listens only on the phone's loopback. So the
/// build gets a small tunnel: the phone dials out to the dev server, proves
/// nothing, and asks the server to prove it holds the key from the pairing
/// link; then the dev server reaches the VM service back through that
/// connection, and `flutter attach` does the rest -- incremental kernel,
/// hot reload, hot restart -- exactly as it does over USB.
///
/// The tunnel is Java on a Java thread, not Dart, because a hot restart kills
/// every Dart isolate and a tunnel inside one would cut the connection the
/// restart is travelling over. It lives in the debug source set, so a profile
/// or release build does not compile it.
library dartvel_cli.devclient.android_dev_client;

import 'dart:convert';

import '../build/build_profile.dart';

import 'package:dartvel_core/dartvel.dart'
    show
        DVDevClientManifest,
        dvDevClientLinkScheme,
        dvDevClientShellMarker,
        dvDevClientTunnelPath,
        dvDevClientTunnelProtocol;

/// Where the tunnel is written, relative to the project root.
const String dvAndroidDevTunnelPath =
    'android/app/src/debug/java/dev/dartvel/devclient/DartvelDevTunnel.java';

/// Where the Android glue is written.
const String dvAndroidDevClientPath =
    'android/app/src/debug/java/dev/dartvel/devclient/DartvelDevClient.java';

/// Where the activity a scanned link opens is written.
const String dvAndroidDevPairActivityPath =
    'android/app/src/debug/java/dev/dartvel/devclient/DartvelDevPairActivity.java';

/// The debug manifest the activity is declared in.
const String dvAndroidDebugManifestPath =
    'android/app/src/debug/AndroidManifest.xml';

/// The class Dart hands its VM service URI to, in JNI's form.
const String dvAndroidDevClientClass = 'dev/dartvel/devclient/DartvelDevClient';

/// The entrypoint a development build is built from and attached with.
///
/// The same path for both, because a hot restart runs the `main` of the
/// entrypoint `flutter attach` was given: attaching with the application's
/// own `lib/main.dart` would restart into an app with no tunnel.
const String dvDevelopmentEntrypoint = '.dart_tool/dartvel/development_main.dart';

/// The tunnel. Plain Java -- java.net and java.security only -- so it runs on
/// a JVM in a test as it runs on a phone.
String dvAndroidDevTunnelSource() => '''
package dev.dartvel.devclient;

// GENERATED by dartvel build --profile development. Do not edit.
//
// The phone dials out to `dartvel dev --dev-client`. The server answers with a
// signature over this device's nonce by the key in the pairing link; nothing
// is sent until it verifies. Then the server asks for streams, and each stream
// is piped to the Dart VM service on this phone's loopback.

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.math.BigInteger;
import java.net.InetSocketAddress;
import java.net.Socket;
import java.net.URI;
import java.net.URLDecoder;
import java.nio.charset.Charset;
import java.security.KeyFactory;
import java.security.KeyPairGenerator;
import java.security.PublicKey;
import java.security.SecureRandom;
import java.security.Signature;
import java.security.interfaces.ECPublicKey;
import java.security.spec.ECGenParameterSpec;
import java.security.spec.ECParameterSpec;
import java.security.spec.ECPoint;
import java.security.spec.ECPublicKeySpec;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;

public final class DartvelDevTunnel implements Runnable {
  public interface Listener {
    void status(String message);
  }

  static final String PATH = "$dvDevClientTunnelPath";
  static final String PROTOCOL = "$dvDevClientTunnelProtocol";
  static final String SCHEME = "$dvDevClientLinkScheme";
  static final Charset UTF8 = Charset.forName("UTF-8");

  final String host;
  final int port;
  final String token;
  final PublicKey key;
  final int vmPort;
  final String vmPath;
  final String manifestJson;
  final Listener listener;
  private volatile boolean closed;
  private volatile Socket control;

  private DartvelDevTunnel(String host, int port, String token, PublicKey key,
      int vmPort, String vmPath, String manifestJson, Listener listener) {
    this.host = host;
    this.port = port;
    this.token = token;
    this.key = key;
    this.vmPort = vmPort;
    this.vmPath = vmPath;
    this.manifestJson = manifestJson;
    this.listener = listener;
  }

  /** A tunnel for [link], a dartvel-dev://pair link, to [vmService]. */
  public static DartvelDevTunnel fromLink(String link, String vmService,
      String manifestJson, Listener listener) {
    URI uri = URI.create(link.trim());
    if (!SCHEME.equals(uri.getScheme())) {
      throw new IllegalArgumentException("Not a " + SCHEME + " link: " + link);
    }
    Map<String, String> query = new HashMap<String, String>();
    String raw = uri.getRawQuery();
    if (raw == null) {
      // dartvel-dev://pair?... is opaque to java.net.URI.
      String s = uri.getRawSchemeSpecificPart();
      int q = s.indexOf('?');
      raw = q < 0 ? "" : s.substring(q + 1);
    }
    for (String pair : raw.split("&")) {
      int eq = pair.indexOf('=');
      if (eq <= 0) continue;
      query.put(decode(pair.substring(0, eq)), decode(pair.substring(eq + 1)));
    }
    String server = query.get("server");
    String token = query.get("token");
    String key = query.get("key");
    if (server == null || token == null || key == null) {
      throw new IllegalArgumentException("The link names no server, token or key.");
    }
    URI serverUri = URI.create(server);
    URI vm = URI.create(vmService);
    return new DartvelDevTunnel(
        serverUri.getHost(),
        serverUri.getPort() < 0 ? 80 : serverUri.getPort(),
        token,
        publicKey(base64UrlDecode(key)),
        vm.getPort(),
        vm.getRawPath() == null || vm.getRawPath().isEmpty() ? "/" : vm.getRawPath(),
        manifestJson,
        listener);
  }

  public String server() {
    return host + ":" + port;
  }

  public void close() {
    closed = true;
    Socket s = control;
    if (s != null) {
      try {
        s.close();
      } catch (IOException ignored) {
      }
    }
  }

  @Override
  public void run() {
    int attempt = 0;
    while (!closed) {
      try {
        attempt++;
        listener.status("connecting to " + server());
        runControl();
        if (closed) return;
        listener.status("the dev server at " + server() + " disconnected");
        attempt = 0;
      } catch (Refused refused) {
        listener.status(refused.getMessage());
        return;
      } catch (IOException e) {
        listener.status("could not reach the dev server at " + server() + ": " + e.getMessage());
      }
      try {
        Thread.sleep(Math.max(1000L, Math.min(10000L, 1000L * attempt)));
      } catch (InterruptedException e) {
        return;
      }
    }
  }

  /** A refusal a retry cannot fix: the wrong server, key or project. */
  static final class Refused extends IOException {
    Refused(String message) {
      super(message);
    }
  }

  private void runControl() throws IOException {
    Socket socket = open("role=control");
    control = socket;
    try {
      OutputStream out = socket.getOutputStream();
      String hello = "{\\"vmService\\":\\"" + vmPath + "\\",\\"manifest\\":" + manifestJson + "}\\n";
      out.write(hello.getBytes(UTF8));
      out.flush();
      listener.status("paired with " + server());
      InputStream in = socket.getInputStream();
      String line;
      while ((line = readLine(in)) != null) {
        if (line.startsWith("open ")) {
          final String id = line.substring(5).trim();
          Thread t = new Thread(new Runnable() {
            public void run() {
              stream(id);
            }
          }, "dartvel-dev-stream-" + id);
          t.setDaemon(true);
          t.start();
        } else if (line.startsWith("refused ")) {
          throw new Refused("the dev server refused this build: " + line.substring(8));
        }
      }
    } finally {
      control = null;
      try {
        socket.close();
      } catch (IOException ignored) {
      }
    }
  }

  private void stream(String id) {
    Socket up = null;
    Socket vm = null;
    try {
      up = open("role=stream&id=" + id);
      vm = new Socket();
      vm.connect(new InetSocketAddress("127.0.0.1", vmPort), 5000);
      pipe(up, vm);
      pipe(vm, up);
    } catch (IOException e) {
      listener.status("a stream to the VM service failed: " + e.getMessage());
      closeQuietly(up);
      closeQuietly(vm);
    }
  }

  private static void pipe(final Socket from, final Socket to) {
    Thread t = new Thread(new Runnable() {
      public void run() {
        byte[] buffer = new byte[16384];
        try {
          InputStream in = from.getInputStream();
          OutputStream out = to.getOutputStream();
          int n;
          while ((n = in.read(buffer)) >= 0) {
            out.write(buffer, 0, n);
            out.flush();
          }
        } catch (IOException ignored) {
        } finally {
          closeQuietly(from);
          closeQuietly(to);
        }
      }
    }, "dartvel-dev-pipe");
    t.setDaemon(true);
    t.start();
  }

  static void closeQuietly(Socket s) {
    if (s == null) return;
    try {
      s.close();
    } catch (IOException ignored) {
    }
  }

  /** Opens a tunnel connection and verifies the server's proof. */
  private Socket open(String query) throws IOException {
    byte[] random = new byte[32];
    new SecureRandom().nextBytes(random);
    String nonce = base64UrlEncode(random);
    Socket socket = new Socket();
    socket.connect(new InetSocketAddress(host, port), 5000);
    boolean ok = false;
    try {
      OutputStream out = socket.getOutputStream();
      String request = "GET " + PATH + "?" + query + "&nonce=" + nonce + " HTTP/1.1\\r\\n"
          + "Host: " + host + ":" + port + "\\r\\n"
          + "Authorization: Bearer " + token + "\\r\\n"
          + "Connection: Upgrade\\r\\n"
          + "Upgrade: " + PROTOCOL + "\\r\\n\\r\\n";
      out.write(request.getBytes(UTF8));
      out.flush();

      InputStream in = socket.getInputStream();
      String status = readLine(in);
      if (status == null) throw new IOException("the dev server closed the connection");
      Map<String, String> headers = new HashMap<String, String>();
      String line;
      while ((line = readLine(in)) != null && !line.isEmpty()) {
        int colon = line.indexOf(':');
        if (colon > 0) {
          headers.put(line.substring(0, colon).trim().toLowerCase(Locale.ROOT),
              line.substring(colon + 1).trim());
        }
      }
      String[] parts = status.split(" ");
      int code = parts.length > 1 ? Integer.parseInt(parts[1]) : 0;
      if (code == 401) {
        throw new Refused("the dev server at " + server() + " refused this device. "
            + "Its pairing ends when dartvel dev restarts; scan the new code.");
      }
      if (code != 101) throw new IOException("the dev server answered HTTP " + code);
      String proof = headers.get("x-dartvel-proof");
      if (proof == null || !verify(nonce, proof)) {
        throw new Refused("the server at " + server() + " could not give proof that it holds "
            + "the key this device was paired with, so nothing was sent to it.");
      }
      ok = true;
      return socket;
    } finally {
      if (!ok) closeQuietly(socket);
    }
  }

  private boolean verify(String nonce, String proof) {
    try {
      byte[] raw = base64UrlDecode(proof);
      if (raw.length != 64) return false;
      Signature signature = Signature.getInstance("SHA256withECDSA");
      signature.initVerify(key);
      signature.update((PROTOCOL + "\\n" + nonce).getBytes(UTF8));
      return signature.verify(der(raw));
    } catch (Exception e) {
      return false;
    }
  }

  /** A raw r||s signature as the DER sequence java.security expects. */
  static byte[] der(byte[] raw) {
    byte[] r = new BigInteger(1, java.util.Arrays.copyOfRange(raw, 0, 32)).toByteArray();
    byte[] s = new BigInteger(1, java.util.Arrays.copyOfRange(raw, 32, 64)).toByteArray();
    ByteArrayOutputStream out = new ByteArrayOutputStream();
    out.write(0x30);
    out.write(4 + r.length + s.length);
    out.write(0x02);
    out.write(r.length);
    out.write(r, 0, r.length);
    out.write(0x02);
    out.write(s.length);
    out.write(s, 0, s.length);
    return out.toByteArray();
  }

  /** An uncompressed P-256 point as a public key. */
  static PublicKey publicKey(byte[] point) {
    if (point.length != 65 || point[0] != 0x04) {
      throw new IllegalArgumentException("The link's key is not a P-256 point.");
    }
    try {
      // The curve's parameters from a generated key, which every Android
      // version has; AlgorithmParameters("EC") does not exist before API 26.
      KeyPairGenerator generator = KeyPairGenerator.getInstance("EC");
      generator.initialize(new ECGenParameterSpec("secp256r1"));
      ECParameterSpec curve = ((ECPublicKey) generator.generateKeyPair().getPublic()).getParams();
      ECPoint w = new ECPoint(
          new BigInteger(1, java.util.Arrays.copyOfRange(point, 1, 33)),
          new BigInteger(1, java.util.Arrays.copyOfRange(point, 33, 65)));
      return KeyFactory.getInstance("EC").generatePublic(new ECPublicKeySpec(w, curve));
    } catch (Exception e) {
      throw new IllegalArgumentException("The link's key could not be read: " + e);
    }
  }

  /** A line ending in \\n, read a byte at a time so nothing after it is taken. */
  static String readLine(InputStream in) throws IOException {
    ByteArrayOutputStream line = new ByteArrayOutputStream();
    int b;
    while ((b = in.read()) >= 0) {
      if (b == '\\n') break;
      line.write(b);
      if (line.size() > 65536) throw new IOException("a line from the dev server is too long");
    }
    if (b < 0 && line.size() == 0) return null;
    String text = new String(line.toByteArray(), UTF8);
    return text.endsWith("\\r") ? text.substring(0, text.length() - 1) : text;
  }

  private static String decode(String s) {
    try {
      return URLDecoder.decode(s, "UTF-8");
    } catch (java.io.UnsupportedEncodingException e) {
      throw new IllegalStateException(e);
    }
  }

  private static final String ALPHABET =
      "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_";

  // Both by hand: java.util.Base64 arrived in Android API 26, and
  // android.util.Base64 does not exist on a JVM.
  static String base64UrlEncode(byte[] data) {
    StringBuilder out = new StringBuilder();
    int i = 0;
    while (i + 2 < data.length) {
      int n = ((data[i] & 0xff) << 16) | ((data[i + 1] & 0xff) << 8) | (data[i + 2] & 0xff);
      out.append(ALPHABET.charAt((n >> 18) & 63)).append(ALPHABET.charAt((n >> 12) & 63))
          .append(ALPHABET.charAt((n >> 6) & 63)).append(ALPHABET.charAt(n & 63));
      i += 3;
    }
    int left = data.length - i;
    if (left == 1) {
      int n = (data[i] & 0xff) << 16;
      out.append(ALPHABET.charAt((n >> 18) & 63)).append(ALPHABET.charAt((n >> 12) & 63));
    } else if (left == 2) {
      int n = ((data[i] & 0xff) << 16) | ((data[i + 1] & 0xff) << 8);
      out.append(ALPHABET.charAt((n >> 18) & 63)).append(ALPHABET.charAt((n >> 12) & 63))
          .append(ALPHABET.charAt((n >> 6) & 63));
    }
    return out.toString();
  }

  static byte[] base64UrlDecode(String text) {
    String s = text.replace('+', '-').replace('/', '_');
    while (s.endsWith("=")) s = s.substring(0, s.length() - 1);
    ByteArrayOutputStream out = new ByteArrayOutputStream();
    int buffer = 0;
    int bits = 0;
    for (int i = 0; i < s.length(); i++) {
      int v = ALPHABET.indexOf(s.charAt(i));
      if (v < 0) throw new IllegalArgumentException("not base64url");
      buffer = (buffer << 6) | v;
      bits += 6;
      if (bits >= 8) {
        bits -= 8;
        out.write((buffer >> bits) & 0xff);
      }
    }
    return out.toByteArray();
  }
}
''';

/// The Android glue: holds the pairing link and the VM service URI, and
/// starts the tunnel once it has both. [manifest] is what this build
/// compiled in, recorded here rather than in Dart because a hot restart can
/// change the Dart but not what was built natively.
String dvAndroidDevClientSource(DVDevClientManifest manifest) {
  final String json = jsonEncode(manifest.toJson())
      .replaceAll(r'\', r'\\')
      .replaceAll('"', r'\"');
  return '''
package dev.dartvel.devclient;

// GENERATED by dartvel build --profile development. Do not edit.
//
// Dart calls vmService() over JNI when the app starts, with the URI of its own
// VM service. A scanned dartvel-dev:// link arrives through
// DartvelDevPairActivity. With both, the tunnel starts on a Java thread, which
// a hot restart -- that kills every Dart isolate -- does not touch.

import android.content.Context;
import android.content.SharedPreferences;
import android.util.Log;

public final class DartvelDevClient {
  /** The binding manifest this build compiled in. */
  static final String MANIFEST = "$json";

  /** Referenced so the build is recognisable as a development build. */
  static final String MARKER = "$dvDevClientShellMarker";

  private static final String TAG = "DartvelDevClient";
  private static final String PREFS = "dev.dartvel.devclient";

  private static String link;
  private static String vmService;
  private static DartvelDevTunnel tunnel;
  private static String status = "not paired: scan the code dartvel dev --dev-client prints";

  private DartvelDevClient() {}

  /** Called from Dart with this app's VM service URI. Returns the status. */
  public static synchronized String vmService(String uri) {
    if (uri != null && !uri.equals(vmService) && tunnel != null) {
      tunnel.close();
      tunnel = null;
    }
    vmService = uri;
    if (link == null) link = stored();
    start();
    return status;
  }

  /** A scanned or opened pairing link. */
  public static synchronized void pair(Context context, String newLink) {
    link = newLink;
    if (context != null) {
      prefs(context).edit().putString("link", newLink).apply();
    }
    if (tunnel != null) {
      tunnel.close();
      tunnel = null;
    }
    start();
  }

  public static synchronized String status() {
    return status;
  }

  /** The dev server's host, for reaching the backend it runs beside. */
  public static synchronized String serverHost() {
    return tunnel == null ? null : tunnel.host;
  }

  private static void start() {
    if (link == null || vmService == null || tunnel != null) return;
    try {
      tunnel = DartvelDevTunnel.fromLink(link, vmService, MANIFEST,
          new DartvelDevTunnel.Listener() {
            public void status(String message) {
              Log.i(TAG, message);
              synchronized (DartvelDevClient.class) {
                status = message;
              }
            }
          });
    } catch (IllegalArgumentException e) {
      status = "the pairing link could not be used: " + e.getMessage();
      Log.w(TAG, status);
      return;
    }
    Thread thread = new Thread(tunnel, "dartvel-dev-tunnel");
    thread.setDaemon(true);
    thread.start();
  }

  private static String stored() {
    Context context = dev.dartvel.jni.DartvelContext.context();
    return context == null ? null : prefs(context).getString("link", null);
  }

  private static SharedPreferences prefs(Context context) {
    return context.getSharedPreferences(PREFS, Context.MODE_PRIVATE);
  }
}
''';
}

/// The activity a scanned `dartvel-dev://` link opens. It records the link and
/// brings the application forward; it draws nothing.
String dvAndroidDevPairActivitySource() => '''
package dev.dartvel.devclient;

// GENERATED by dartvel build --profile development. Do not edit.

import android.app.Activity;
import android.content.Intent;
import android.net.Uri;
import android.os.Bundle;

public final class DartvelDevPairActivity extends Activity {
  @Override
  protected void onCreate(Bundle state) {
    super.onCreate(state);
    Uri data = getIntent() == null ? null : getIntent().getData();
    if (data != null) {
      DartvelDevClient.pair(getApplicationContext(), data.toString());
    }
    Intent launch = getPackageManager().getLaunchIntentForPackage(getPackageName());
    if (launch != null) {
      launch.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
      startActivity(launch);
    }
    finish();
  }
}
''';

const String _markStart = '    <!-- dartvel.devclient: start -->\n';
const String _markEnd = '    <!-- dartvel.devclient: end -->\n';

/// [manifest], the debug source set's manifest, with the pairing activity
/// declared. Marked and rewritten, so building twice declares it once.
///
/// Null [manifest] is a project with no debug manifest, which gets one.
String dvAndroidDevClientDebugManifest(String? manifest) {
  String source =
      manifest ??
      '<manifest xmlns:android="http://schemas.android.com/apk/res/android">\n'
          '    <uses-permission android:name="android.permission.INTERNET"/>\n'
          '</manifest>\n';
  final int existing = source.indexOf(_markStart);
  if (existing >= 0) {
    final int end = source.indexOf(_markEnd, existing);
    source =
        source.substring(0, existing) +
        source.substring(end + _markEnd.length);
  }
  final StringBuffer block = StringBuffer()
    ..write(_markStart)
    ..writeln('    <!-- A scanned dartvel-dev:// link pairs this development')
    ..writeln('         build with dartvel dev. Debug builds only. -->')
    ..writeln('    <application>')
    ..writeln('        <activity')
    ..writeln(
      '            android:name="dev.dartvel.devclient.DartvelDevPairActivity"',
    )
    ..writeln('            android:exported="true"')
    ..writeln('            android:noHistory="true"')
    ..writeln(
      '            android:theme="@android:style/Theme.Translucent.NoTitleBar">',
    )
    ..writeln('            <intent-filter>')
    ..writeln(
      '                <action android:name="android.intent.action.VIEW"/>',
    )
    ..writeln(
      '                <category android:name="android.intent.category.DEFAULT"/>',
    )
    ..writeln(
      '                <category android:name="android.intent.category.BROWSABLE"/>',
    )
    ..writeln(
      '                <data android:scheme="$dvDevClientLinkScheme" android:host="pair"/>',
    )
    ..writeln('            </intent-filter>')
    ..writeln('        </activity>')
    ..writeln('    </application>')
    ..write(_markEnd);
  final int close = source.lastIndexOf('</manifest>');
  if (close < 0) return source;
  if (!source.contains('android.permission.INTERNET')) {
    block.write(
      '    <uses-permission android:name="android.permission.INTERNET"/>\n',
    );
  }
  return '${source.substring(0, close)}$block${source.substring(close)}';
}

/// Platforms whose development build carries the dev client.
///
/// Android only: the tunnel is Java. An iOS debug build cannot run from the
/// home screen without a debugger attached, which is why iOS syncs code as
/// OTA patches instead.
const Set<String> dvDevClientPlatforms = <String>{'android'};

/// The entrypoint `flutter build` is given for [platform] under [profile]:
/// the development entrypoint for a development build that carries the dev
/// client, and [target] as it was for everything else.
String? dvDevelopmentBuildTarget({
  required String platform,
  required DVBuildProfile profile,
  required String? target,
}) {
  if (profile.isDevelopment && dvDevClientPlatforms.contains(platform)) {
    return dvDevelopmentEntrypoint;
  }
  return target;
}

/// The development entrypoint: the tunnel's Dart half, then the
/// application's own `main`.
///
/// [package] and [target] name the application's entrypoint; a target under
/// `lib/` is imported by its package URI so it is the same library the rest of
/// the application imports.
String dvDevelopmentEntrypointSource({
  required String package,
  String target = 'lib/main.dart',
}) {
  final String normalized = target.replaceAll(r'\', '/');
  final String import = normalized.startsWith('lib/')
      ? 'package:$package/${normalized.substring(4)}'
      : '../../$normalized';
  return '''
// GENERATED by `dartvel build --profile development`. Do not edit.
//
// The entrypoint of a development build, and the one `dartvel dev
// --dev-client` attaches with, so a hot restart comes back through here and
// the device stays paired. A profile or release build never imports it.
import 'package:dartvel_flutter/dev_client.dart' show DVDevClientSession;

import '$import' as app;

void main(List<String> args) {
  DVDevClientSession.start();
  final Function entry = app.main;
  if (entry is void Function(List<String>)) {
    entry(args);
  } else {
    (entry as dynamic)();
  }
}
''';
}
