/// What `dartvel build linux --profile development` writes so the build pairs
/// with `dartvel dev` and hot reloads over the network.
///
/// The design is Android's and iOS's (see android_dev_client.dart and
/// apple_dev_client.dart): the app dials out to the dev server over TLS pinned
/// to the key in the pairing link, and the dev server reaches the app's Dart
/// VM service back through the connection so `flutter attach` can reload it.
/// Here the tunnel is C++ on GIO, running on threads of its own, which a hot
/// restart -- that kills every Dart isolate -- does not touch.
///
/// A desktop application is not opened by scanning a code, so the link is its
/// launch flag: the `dartvel-dev://pair?...` link `dartvel dev` prints, passed
/// as an argument, which is also how a desktop environment hands an
/// application a URL it is registered for.
///
///     ./build/linux/x64/debug/bundle/<app> 'dartvel-dev://pair?...'
///
/// Two things are written, both Debug-only: `linux/runner/dartvel_dev_client.cc`,
/// whose body is inside `#ifndef NDEBUG`, and a marked block in
/// `linux/runner/CMakeLists.txt` that compiles it, and exports its functions to
/// Dart's FFI lookup, only when CMAKE_BUILD_TYPE is Debug. A profile or
/// release build takes the block back out.
library dartvel_cli.devclient.linux_dev_client;

import 'dart:convert';

import 'package:dartvel_core/dartvel.dart'
    show
        DVDevClientManifest,
        dvDevClientLinkScheme,
        dvDevClientShellMarker,
        dvDevClientTunnelPath,
        dvDevClientTunnelProtocol;

import 'apple_dev_client.dart'
    show dvAppleDevClientServerHostSymbol, dvAppleDevClientVmServiceSymbol;

/// Where the tunnel is written, relative to the project root.
const String dvLinuxDevTunnelPath = 'linux/runner/dartvel_dev_client.cc';

/// The runner's CMake file the block goes into.
const String dvLinuxRunnerCmakePath = 'linux/runner/CMakeLists.txt';

const String _cmakeStart = '# dartvel.devclient: begin\n';
const String _cmakeEnd = '# dartvel.devclient: end\n';

/// [cmake], the runner's CMakeLists.txt, with the tunnel compiled into a
/// Debug build -- or, when not [enabled], without it.
String dvLinuxRunnerCmakeWithDevClient(String cmake, {required bool enabled}) {
  final RegExp block = RegExp(
    '${RegExp.escape(_cmakeStart)}.*?${RegExp.escape(_cmakeEnd)}',
    dotAll: true,
  );
  final String stripped = cmake.replaceAll(block, '');
  if (!enabled) return stripped;
  const String insert =
      '$_cmakeStart'
      '# A development build pairs with `dartvel dev`: the tunnel, and its\n'
      '# functions exported to Dart\'s FFI lookup. Debug builds only.\n'
      'if(CMAKE_BUILD_TYPE STREQUAL "Debug")\n'
      '  target_sources(\${BINARY_NAME} PRIVATE "dartvel_dev_client.cc")\n'
      '  set_target_properties(\${BINARY_NAME} PROPERTIES ENABLE_EXPORTS ON)\n'
      'endif()\n'
      '$_cmakeEnd';
  // After the application target exists, and before anything else touches
  // it: the line after add_executable's closing parenthesis.
  final int start = stripped.indexOf(r'add_executable(${BINARY_NAME}');
  if (start < 0) return stripped;
  final int close = stripped.indexOf('\n)\n', start);
  if (close < 0) return stripped;
  final int at = close + 3;
  return '${stripped.substring(0, at)}$insert${stripped.substring(at)}';
}

String _cString(String value) =>
    value.replaceAll(r'\', r'\\').replaceAll('"', r'\"');

/// The C++ tunnel, recording [manifest]: what this build compiled in.
String dvLinuxDevTunnelSource(DVDevClientManifest manifest) {
  final String json = _cString(jsonEncode(manifest.toJson()));
  return '''
// GENERATED by dartvel build --profile development. Do not edit.
//
// The native half of a Linux development build's pairing with `dartvel dev`.
// Dart calls $dvAppleDevClientVmServiceSymbol() over FFI when the app starts,
// with the URI of its own Dart VM service. The pairing link is the launch
// flag: a dartvel-dev://pair link among the process's arguments. With both,
// the tunnel dials out to the dev server over GIO TLS, trusting only a
// certificate whose public key is the key in the link, and the dev server
// reaches the VM service back through it. The tunnel runs on threads of its
// own, which a hot restart -- that kills every Dart isolate -- does not touch.
//
// CMake compiles this into Debug builds only, and everything below is inside
// #ifndef NDEBUG as well.

#ifndef NDEBUG

#include <gio/gio.h>
#include <glib.h>

#include <algorithm>
#include <atomic>
#include <chrono>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <fstream>
#include <memory>
#include <mutex>
#include <sstream>
#include <string>
#include <thread>
#include <vector>

namespace {

const char kPath[] = "$dvDevClientTunnelPath";
const char kProtocol[] = "$dvDevClientTunnelProtocol";
const char kScheme[] = "$dvDevClientLinkScheme";
const char kManifest[] = "$json";
// Referenced so the build is recognisable as a development build.
const char kMarker[] = "$dvDevClientShellMarker";

std::mutex& StatusLock() {
  static std::mutex lock;
  return lock;
}

std::string& StatusText() {
  static std::string status = "not paired: pass the link dartvel dev prints";
  return status;
}

void SetStatus(const std::string& status) {
  {
    std::lock_guard<std::mutex> guard(StatusLock());
    StatusText() = status;
  }
  fprintf(stderr, "[DartvelDevClient] %s\\n", status.c_str());
  fflush(stderr);
}

bool IsPairLink(const std::string& candidate) {
  const std::string prefix = std::string(kScheme) + "://pair";
  return candidate.compare(0, prefix.size(), prefix) == 0;
}

std::vector<unsigned char> Base64UrlDecode(const std::string& text) {
  std::string s = text;
  for (char& c : s) {
    if (c == '-') c = '+';
    if (c == '_') c = '/';
  }
  while (s.size() % 4 != 0) s.push_back('=');
  gsize length = 0;
  guchar* bytes = g_base64_decode(s.c_str(), &length);
  std::vector<unsigned char> out(bytes, bytes + length);
  g_free(bytes);
  return out;
}

std::string Base64UrlEncode(const unsigned char* data, size_t length) {
  gchar* encoded = g_base64_encode(data, length);
  std::string s;
  for (const char* p = encoded; *p != '\\0'; p++) {
    if (*p == '=') continue;
    s.push_back(*p == '+' ? '-' : *p == '/' ? '_' : *p);
  }
  g_free(encoded);
  return s;
}

// -- the certificate's public key, read by structure --------------------------

struct Element {
  unsigned char tag;
  size_t start;
  size_t end;
};

bool ReadElement(const unsigned char* der, size_t at, size_t limit, Element* out) {
  if (at + 2 > limit) return false;
  size_t length = der[at + 1];
  size_t start = at + 2;
  if (length & 0x80) {
    size_t count = length & 0x7f;
    if (count == 0 || count > 4 || start + count > limit) return false;
    length = 0;
    for (size_t i = 0; i < count; i++) length = (length << 8) | der[start + i];
    start += count;
  }
  if (start + length > limit) return false;
  *out = Element{der[at], start, start + length};
  return true;
}

// The uncompressed P-256 point of the certificate's subject public key info:
// certificate, to-be-signed certificate, its seventh field. Never searched
// for in the bytes, where a certificate for another key can carry it anywhere.
bool CertificateKey(const unsigned char* der, size_t size, std::vector<unsigned char>* key) {
  static const unsigned char kEcPublicKey[] = {0x2a, 0x86, 0x48, 0xce, 0x3d, 0x02, 0x01};
  static const unsigned char kPrime256v1[] = {0x2a, 0x86, 0x48, 0xce, 0x3d, 0x03, 0x01, 0x07};
  Element certificate, tbs, field, algorithm, type, curve, bits;
  if (!ReadElement(der, 0, size, &certificate) || certificate.tag != 0x30) return false;
  if (!ReadElement(der, certificate.start, certificate.end, &tbs) || tbs.tag != 0x30) return false;
  if (!ReadElement(der, tbs.start, tbs.end, &field)) return false;
  if (field.tag == 0xa0 && !ReadElement(der, field.end, tbs.end, &field)) return false;
  for (int i = 0; i < 5; i++) {
    if (!ReadElement(der, field.end, tbs.end, &field)) return false;
  }
  if (field.tag != 0x30) return false;
  if (!ReadElement(der, field.start, field.end, &algorithm) || algorithm.tag != 0x30) return false;
  if (!ReadElement(der, algorithm.start, algorithm.end, &type) || type.tag != 0x06 ||
      type.end - type.start != sizeof(kEcPublicKey) ||
      memcmp(der + type.start, kEcPublicKey, sizeof(kEcPublicKey)) != 0) {
    return false;
  }
  if (!ReadElement(der, type.end, algorithm.end, &curve) || curve.tag != 0x06 ||
      curve.end - curve.start != sizeof(kPrime256v1) ||
      memcmp(der + curve.start, kPrime256v1, sizeof(kPrime256v1)) != 0) {
    return false;
  }
  if (!ReadElement(der, algorithm.end, field.end, &bits) || bits.tag != 0x03 ||
      bits.end - bits.start != 66 || der[bits.start] != 0 || der[bits.start + 1] != 0x04) {
    return false;
  }
  key->assign(der + bits.start + 1, der + bits.end);
  return true;
}

bool CertificateHoldsKey(GTlsCertificate* certificate, const std::vector<unsigned char>& pin) {
  if (certificate == nullptr) return false;
  GByteArray* der = nullptr;
  g_object_get(certificate, "certificate", &der, nullptr);
  if (der == nullptr) return false;
  std::vector<unsigned char> key;
  const bool read = CertificateKey(der->data, der->len, &key);
  g_byte_array_unref(der);
  if (!read || key.size() != pin.size()) return false;
  unsigned char difference = 0;
  for (size_t i = 0; i < key.size(); i++) difference |= key[i] ^ pin[i];
  return difference == 0;
}

struct Pin {
  std::vector<unsigned char> key;
  bool refused = false;
};

gboolean AcceptCertificate(GTlsConnection* connection, GTlsCertificate* certificate,
                           GTlsCertificateFlags errors, gpointer data) {
  Pin* pin = static_cast<Pin*>(data);
  const bool trusted = CertificateHoldsKey(certificate, pin->key);
  if (!trusted) pin->refused = true;
  return trusted ? TRUE : FALSE;
}

// -- a blocking connection over GIO ------------------------------------------

class Connection {
 public:
  Connection() : cancellable_(g_cancellable_new()) {}
  ~Connection() {
    Close();
    if (stream_ != nullptr) g_object_unref(stream_);
    if (socket_ != nullptr) g_object_unref(socket_);
    if (client_ != nullptr) g_object_unref(client_);
    g_object_unref(cancellable_);
  }

  // Empty when connected; why not otherwise. With [pin], over TLS trusting
  // only a certificate for that key, and [pin_refused] set when that is why.
  std::string Open(const std::string& host, int port, const std::vector<unsigned char>* pin,
                   bool* pin_refused) {
    GError* error = nullptr;
    client_ = g_socket_client_new();
    g_socket_client_set_timeout(client_, 10);
    socket_ = g_socket_client_connect_to_host(client_, host.c_str(), static_cast<guint16>(port),
                                              cancellable_, &error);
    if (socket_ == nullptr) return TakeError(error, "the connection failed");
    // The client's timeout is for connecting. Left on the socket it ends
    // every read that waits longer: an idle control connection, and the VM
    // service stream between reloads.
    g_socket_set_timeout(g_socket_connection_get_socket(socket_), 0);
    if (pin == nullptr) {
      stream_ = G_IO_STREAM(g_object_ref(socket_));
      return std::string();
    }
    if (!g_tls_backend_supports_tls(g_tls_backend_get_default())) {
      return "this system has no TLS for GIO; install glib-networking";
    }
    GIOStream* tls = g_tls_client_connection_new(G_IO_STREAM(socket_), nullptr, &error);
    if (tls == nullptr) return TakeError(error, "TLS could not start");
    stream_ = tls;
    pin_.key = *pin;
    g_signal_connect(tls, "accept-certificate", G_CALLBACK(AcceptCertificate), &pin_);
    const gboolean shaken = g_tls_connection_handshake(G_TLS_CONNECTION(tls), cancellable_, &error);
    // Checked whatever the handshake decided: a certificate some authority
    // on this machine trusts never reaches accept-certificate.
    GTlsCertificate* peer = g_tls_connection_get_peer_certificate(G_TLS_CONNECTION(tls));
    if (pin_.refused || (shaken && !CertificateHoldsKey(peer, pin_.key))) {
      if (error != nullptr) g_error_free(error);
      *pin_refused = true;
      return "not the key this device was paired with";
    }
    if (!shaken) return TakeError(error, "the TLS handshake failed");
    return std::string();
  }

  bool Write(const std::string& data) { return Write(data.data(), data.size()); }

  bool Write(const char* data, size_t size) {
    if (stream_ == nullptr) return false;
    gsize written = 0;
    return g_output_stream_write_all(g_io_stream_get_output_stream(stream_), data, size, &written,
                                     cancellable_, nullptr) == TRUE;
  }

  // Bytes read into [buffer]; 0 at the end of the stream or on an error.
  size_t Read(char* buffer, size_t size) {
    if (!buffer_.empty()) {
      const size_t n = std::min(size, buffer_.size());
      memcpy(buffer, buffer_.data(), n);
      buffer_.erase(0, n);
      return n;
    }
    if (stream_ == nullptr) return 0;
    const gssize n = g_input_stream_read(g_io_stream_get_input_stream(stream_), buffer, size,
                                         cancellable_, nullptr);
    return n > 0 ? static_cast<size_t>(n) : 0;
  }

  bool ReadLine(std::string* line) {
    while (true) {
      const size_t newline = buffer_.find('\\n');
      if (newline != std::string::npos) {
        size_t length = newline;
        if (length > 0 && buffer_[length - 1] == '\\r') length--;
        line->assign(buffer_, 0, length);
        buffer_.erase(0, newline + 1);
        return true;
      }
      if (buffer_.size() > 65536 || stream_ == nullptr) return false;
      char chunk[16384];
      const gssize n = g_input_stream_read(g_io_stream_get_input_stream(stream_), chunk,
                                           sizeof(chunk), cancellable_, nullptr);
      if (n <= 0) return false;
      buffer_.append(chunk, static_cast<size_t>(n));
    }
  }

  void Close() { g_cancellable_cancel(cancellable_); }

 private:
  static std::string TakeError(GError* error, const char* fallback) {
    std::string message = error != nullptr ? error->message : fallback;
    if (error != nullptr) g_error_free(error);
    return message;
  }

  GCancellable* cancellable_;
  GSocketClient* client_ = nullptr;
  GSocketConnection* socket_ = nullptr;
  GIOStream* stream_ = nullptr;
  Pin pin_;
  std::string buffer_;
};

// -- the tunnel --------------------------------------------------------------

class Tunnel : public std::enable_shared_from_this<Tunnel> {
 public:
  static std::shared_ptr<Tunnel> FromLink(const std::string& link, const std::string& vm_service,
                                          std::string* error) {
    GUri* uri = g_uri_parse(link.c_str(), G_URI_FLAGS_ENCODED_QUERY, nullptr);
    if (uri == nullptr || g_strcmp0(g_uri_get_scheme(uri), kScheme) != 0) {
      if (uri != nullptr) g_uri_unref(uri);
      *error = "not a pairing link";
      return nullptr;
    }
    GHashTable* query = g_uri_get_query(uri) == nullptr
                            ? nullptr
                            : g_uri_parse_params(g_uri_get_query(uri), -1, "&", G_URI_PARAMS_NONE,
                                                 nullptr);
    g_uri_unref(uri);
    auto value = [query](const char* key) -> std::string {
      const char* v = query == nullptr ? nullptr : static_cast<const char*>(g_hash_table_lookup(query, key));
      return v == nullptr ? std::string() : std::string(v);
    };
    const std::string server = value("server");
    const std::string token = value("token");
    const std::vector<unsigned char> key = Base64UrlDecode(value("key"));
    if (query != nullptr) g_hash_table_unref(query);
    if (server.empty() || token.empty() || key.empty()) {
      *error = "the link names no server, token or key";
      return nullptr;
    }
    if (key.size() != 65 || key[0] != 0x04) {
      *error = "the link's key is not a P-256 point";
      return nullptr;
    }
    GUri* server_uri = g_uri_parse(server.c_str(), G_URI_FLAGS_NONE, nullptr);
    if (server_uri == nullptr || g_strcmp0(g_uri_get_scheme(server_uri), "https") != 0 ||
        g_uri_get_host(server_uri) == nullptr) {
      if (server_uri != nullptr) g_uri_unref(server_uri);
      *error = "the link names a dev server that is not https; pass the link a current dartvel dev prints";
      return nullptr;
    }
    GUri* vm = g_uri_parse(vm_service.c_str(), G_URI_FLAGS_NONE, nullptr);
    if (vm == nullptr || g_uri_get_port(vm) <= 0) {
      if (vm != nullptr) g_uri_unref(vm);
      g_uri_unref(server_uri);
      *error = "the VM service URI has no port";
      return nullptr;
    }
    std::shared_ptr<Tunnel> tunnel(new Tunnel());
    tunnel->host_ = g_uri_get_host(server_uri);
    tunnel->port_ = g_uri_get_port(server_uri) > 0 ? g_uri_get_port(server_uri) : 443;
    tunnel->token_ = token;
    tunnel->key_ = key;
    tunnel->vm_port_ = g_uri_get_port(vm);
    const char* path = g_uri_get_path(vm);
    tunnel->vm_path_ = path != nullptr && path[0] != '\\0' ? path : "/";
    if (tunnel->vm_path_.back() != '/') tunnel->vm_path_.push_back('/');
    g_uri_unref(vm);
    g_uri_unref(server_uri);
    return tunnel;
  }

  const std::string& host() const { return host_; }

  void Start() {
    std::shared_ptr<Tunnel> self = shared_from_this();
    std::thread([self]() { self->Run(); }).detach();
  }

  void Close() {
    closed_ = true;
    std::lock_guard<std::mutex> guard(control_lock_);
    if (control_ != nullptr) control_->Close();
  }

 private:
  Tunnel() = default;

  std::string Server() const { return host_ + ":" + std::to_string(port_); }

  void Run() {
    int attempt = 0;
    while (!closed_) {
      attempt++;
      SetStatus("connecting to " + Server());
      std::string refused;
      const std::string failure = RunControl(&refused);
      if (closed_) return;
      if (!refused.empty()) {
        SetStatus(refused);
        return;
      }
      if (failure.empty()) {
        SetStatus("the dev server at " + Server() + " disconnected");
        attempt = 0;
      } else {
        SetStatus("could not reach the dev server at " + Server() + ": " + failure);
      }
      std::this_thread::sleep_for(std::chrono::seconds(std::max(1, std::min(10, attempt))));
    }
  }

  // An upgraded tunnel connection, or nullptr with [failure] or [refused] set.
  std::unique_ptr<Connection> Open(const std::string& query, std::string* failure,
                                   std::string* refused) {
    unsigned char random[32];
    std::ifstream urandom("/dev/urandom", std::ios::binary);
    if (!urandom.read(static_cast<char*>(static_cast<void*>(random)), sizeof(random))) {
      *failure = "no random bytes for the nonce";
      return nullptr;
    }
    const std::string nonce = Base64UrlEncode(random, sizeof(random));
    std::unique_ptr<Connection> connection(new Connection());
    bool pin_refused = false;
    const std::string error = connection->Open(host_, port_, &key_, &pin_refused);
    if (!error.empty()) {
      if (pin_refused) {
        *refused = "the server at " + Server() +
                   " did not present the key this device was paired with, so nothing was sent to it.";
      } else {
        *failure = error;
      }
      return nullptr;
    }
    std::ostringstream request;
    request << "GET " << kPath << "?" << query << "&nonce=" << nonce << " HTTP/1.1\\r\\n"
            << "Host: " << Server() << "\\r\\n"
            << "Authorization: Bearer " << token_ << "\\r\\n"
            << "Connection: Upgrade\\r\\n"
            << "Upgrade: " << kProtocol << "\\r\\n\\r\\n";
    if (!connection->Write(request.str())) {
      *failure = "the dev server closed the connection";
      return nullptr;
    }
    std::string status;
    if (!connection->ReadLine(&status)) {
      *failure = "the dev server closed the connection";
      return nullptr;
    }
    std::string header;
    while (connection->ReadLine(&header) && !header.empty()) {
    }
    const size_t space = status.find(' ');
    const int code = space == std::string::npos ? 0 : atoi(status.c_str() + space + 1);
    if (code == 401) {
      *refused = "the dev server at " + Server() +
                 " refused this device. Its pairing ends when dartvel dev restarts; pass the new link.";
      return nullptr;
    }
    if (code != 101) {
      *failure = "the dev server answered HTTP " + std::to_string(code);
      return nullptr;
    }
    return connection;
  }

  std::string RunControl(std::string* refused) {
    std::string failure;
    std::unique_ptr<Connection> control = Open("role=control", &failure, refused);
    if (control == nullptr) return failure;
    {
      std::lock_guard<std::mutex> guard(control_lock_);
      control_ = control.get();
    }
    control->Write(std::string("{\\"vmService\\":\\"") + vm_path_ + "\\",\\"manifest\\":" + kManifest +
                   "}\\n");
    SetStatus("paired with " + Server() + std::string(kMarker).substr(0, 0));
    std::string line;
    std::shared_ptr<Tunnel> self = shared_from_this();
    while (control->ReadLine(&line)) {
      if (line.compare(0, 5, "open ") == 0) {
        const std::string id = line.substr(5);
        std::thread([self, id]() { self->Stream(id); }).detach();
      } else if (line.compare(0, 8, "refused ") == 0) {
        *refused = "the dev server refused this build: " + line.substr(8);
        break;
      }
    }
    {
      std::lock_guard<std::mutex> guard(control_lock_);
      control_ = nullptr;
    }
    return std::string();
  }

  void Stream(const std::string& id) {
    std::string failure;
    std::string refused;
    std::shared_ptr<Connection> up(Open("role=stream&id=" + id, &failure, &refused).release());
    if (up == nullptr) {
      SetStatus("a stream to the VM service failed: " + (failure.empty() ? refused : failure));
      return;
    }
    std::shared_ptr<Connection> vm(new Connection());
    bool unused = false;
    const std::string error = vm->Open("127.0.0.1", vm_port_, nullptr, &unused);
    if (!error.empty()) {
      SetStatus("a stream to the VM service failed: " + error);
      return;
    }
    std::thread([up, vm]() { Pipe(vm.get(), up.get()); }).detach();
    Pipe(up.get(), vm.get());
  }

  static void Pipe(Connection* from, Connection* to) {
    char buffer[16384];
    size_t n;
    while ((n = from->Read(buffer, sizeof(buffer))) > 0) {
      if (!to->Write(buffer, n)) break;
    }
    from->Close();
    to->Close();
  }

  std::string host_;
  int port_ = 443;
  std::string token_;
  std::vector<unsigned char> key_;
  int vm_port_ = 0;
  std::string vm_path_;
  std::atomic<bool> closed_{false};
  std::mutex control_lock_;
  Connection* control_ = nullptr;
};

std::recursive_mutex& Lock() {
  static std::recursive_mutex lock;
  return lock;
}

std::string& VmService() {
  static std::string uri;
  return uri;
}

std::string& Link() {
  static std::string link;
  return link;
}

std::shared_ptr<Tunnel>& CurrentTunnel() {
  static std::shared_ptr<Tunnel> tunnel;
  return tunnel;
}

// The pairing link the process was launched with, or empty.
std::string LaunchLink() {
  std::ifstream cmdline("/proc/self/cmdline", std::ios::binary);
  std::string argument;
  std::string link;
  while (std::getline(cmdline, argument, '\\0')) {
    if (IsPairLink(argument)) link = argument;
  }
  return link;
}

}  // namespace

extern "C" {

// Called from Dart with this app's VM service URI. Returns the status, in a
// buffer this file owns.
__attribute__((visibility("default")))
const char* $dvAppleDevClientVmServiceSymbol(const char* uri) {
  std::lock_guard<std::recursive_mutex> guard(Lock());
  // The first URI this process reported: a restarted isolate can report the
  // dev machine's DDS address instead of this app's own service.
  if (VmService().empty() && uri != nullptr) VmService() = uri;
  if (Link().empty()) Link() = LaunchLink();
  if (!Link().empty() && !VmService().empty() && CurrentTunnel() == nullptr) {
    std::string error;
    std::shared_ptr<Tunnel> tunnel = Tunnel::FromLink(Link(), VmService(), &error);
    if (tunnel == nullptr) {
      SetStatus("the pairing link could not be used: " + error);
    } else {
      CurrentTunnel() = tunnel;
      tunnel->Start();
    }
  }
  static char status[2048];
  std::lock_guard<std::mutex> status_guard(StatusLock());
  g_strlcpy(status, StatusText().c_str(), sizeof(status));
  return status;
}

// The dev server's host, for reaching the backend it runs beside; NULL
// before a tunnel starts.
__attribute__((visibility("default")))
const char* $dvAppleDevClientServerHostSymbol(void) {
  std::lock_guard<std::recursive_mutex> guard(Lock());
  if (CurrentTunnel() == nullptr) return nullptr;
  static char host[512];
  g_strlcpy(host, CurrentTunnel()->host().c_str(), sizeof(host));
  return host;
}

}  // extern "C"

#endif  // NDEBUG
''';
}
