/// What `dartvel build windows --profile development` writes so the build
/// pairs with `dartvel dev` and hot reloads over the network.
///
/// The design is the other platforms' (see android_dev_client.dart): the app
/// dials out to the dev server over TLS pinned to the key in the pairing link,
/// and the dev server reaches the app's Dart VM service back through the
/// connection so `flutter attach` can reload it. Here the tunnel is C++ on
/// Winsock and Schannel, on threads of its own, which a hot restart -- that
/// kills every Dart isolate -- does not touch.
///
/// As on Linux, the link is the launch flag: the `dartvel-dev://pair?...` link
/// `dartvel dev` prints, passed as an argument.
///
/// Two things are written: `windows/runner/dartvel_dev_client.cpp`, whose body
/// is inside `#ifdef _DEBUG`, and a marked line in the runner's
/// CMakeLists.txt that adds it to the Debug configuration only. Windows builds
/// with a multi-configuration generator, so the configuration is chosen by a
/// generator expression; CMAKE_BUILD_TYPE is empty there. A profile or release
/// build takes the line back out.
library dartvel_cli.devclient.windows_dev_client;

import 'dart:convert';

import 'package:dartvel_core/dartvel.dart'
    show
        DVDevClientManifest,
        dvDevClientLinkScheme,
        dvDevClientShellMarker,
        dvDevClientTunnelPath,
        dvDevClientTunnelProtocol;

import 'apple_dev_client.dart'
    show dvAppleDevClientServerHostSymbol, dvAppleDevClientVmServiceSymbol;

/// Where the tunnel is written, relative to the project root.
const String dvWindowsDevTunnelPath = 'windows/runner/dartvel_dev_client.cpp';

/// The runner's CMake file the line goes into.
const String dvWindowsRunnerCmakePath = 'windows/runner/CMakeLists.txt';

const String _cmakeStart = '# dartvel.devclient: begin\n';
const String _cmakeEnd = '# dartvel.devclient: end\n';

/// [cmake], the runner's CMakeLists.txt, with the tunnel compiled into the
/// Debug configuration -- or, when not [enabled], without it.
String dvWindowsRunnerCmakeWithDevClient(
  String cmake, {
  required bool enabled,
}) {
  final RegExp block = RegExp(
    '${RegExp.escape(_cmakeStart)}.*?${RegExp.escape(_cmakeEnd)}',
    dotAll: true,
  );
  final String stripped = cmake.replaceAll(block, '');
  if (!enabled) return stripped;
  const String insert =
      '$_cmakeStart'
      '# A development build pairs with `dartvel dev`. The Debug configuration\n'
      '# only: a generator expression, because this generator builds every\n'
      '# configuration from one project.\n'
      r'target_sources(${BINARY_NAME} PRIVATE "$<$<CONFIG:Debug>:dartvel_dev_client.cpp>")'
      '\n'
      '$_cmakeEnd';
  final int start = stripped.indexOf(r'add_executable(${BINARY_NAME}');
  if (start < 0) return stripped;
  final int close = stripped.indexOf('\n)\n', start);
  if (close < 0) return stripped;
  final int at = close + 3;
  return '${stripped.substring(0, at)}$insert${stripped.substring(at)}';
}

String _cString(String value) =>
    value.replaceAll(r'\', r'\\').replaceAll('"', r'\"');

/// The C++ tunnel, recording [manifest]: what this build compiled in.
String dvWindowsDevTunnelSource(DVDevClientManifest manifest) => _source
    .replaceAll('@@MANIFEST@@', _cString(jsonEncode(manifest.toJson())))
    .replaceAll('@@PATH@@', dvDevClientTunnelPath)
    .replaceAll('@@PROTOCOL@@', dvDevClientTunnelProtocol)
    .replaceAll('@@SCHEME@@', dvDevClientLinkScheme)
    .replaceAll('@@MARKER@@', dvDevClientShellMarker)
    .replaceAll('@@VM_SERVICE@@', dvAppleDevClientVmServiceSymbol)
    .replaceAll('@@SERVER_HOST@@', dvAppleDevClientServerHostSymbol);

const String _source = r'''
// GENERATED by dartvel build --profile development. Do not edit.
//
// The native half of a Windows development build's pairing with
// `dartvel dev`. Dart calls @@VM_SERVICE@@() over FFI when the app starts,
// with the URI of its own Dart VM service. The pairing link is the launch
// flag: a dartvel-dev://pair link among the process's arguments. With both,
// the tunnel dials out to the dev server over Schannel TLS, trusting only a
// certificate whose public key is the key in the link, and the dev server
// reaches the VM service back through it. The tunnel runs on threads of its
// own, which a hot restart -- that kills every Dart isolate -- does not touch.
//
// CMake adds this to the Debug configuration only, and everything below is
// inside #ifdef _DEBUG as well.

#ifdef _DEBUG

#define SECURITY_WIN32
#include <winsock2.h>
#include <ws2tcpip.h>
#include <windows.h>
#include <bcrypt.h>
#include <schannel.h>
#include <security.h>
#include <wincrypt.h>

#include <algorithm>
#include <atomic>
#include <chrono>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <memory>
#include <mutex>
#include <string>
#include <thread>
#include <vector>

#pragma comment(lib, "ws2_32.lib")
#pragma comment(lib, "secur32.lib")
#pragma comment(lib, "crypt32.lib")
#pragma comment(lib, "bcrypt.lib")

namespace {

const char kPath[] = "@@PATH@@";
const char kProtocol[] = "@@PROTOCOL@@";
const char kScheme[] = "@@SCHEME@@";
const char kManifest[] = "@@MANIFEST@@";
// Referenced so the build is recognisable as a development build.
const char kMarker[] = "@@MARKER@@";

std::mutex& StatusLock() {
  static std::mutex lock;
  return lock;
}

std::string& StatusText() {
  static std::string status = "not paired: pass the link dartvel dev prints";
  return status;
}

void SetStatus(const std::string& status) {
  {
    std::lock_guard<std::mutex> guard(StatusLock());
    StatusText() = status;
  }
  const std::string line = "[DartvelDevClient] " + status + "\n";
  OutputDebugStringA(line.c_str());
  fprintf(stderr, "%s", line.c_str());
  fflush(stderr);
}

bool IsPairLink(const std::string& candidate) {
  const std::string prefix = std::string(kScheme) + "://pair";
  return candidate.compare(0, prefix.size(), prefix) == 0;
}

std::string PercentDecode(const std::string& text) {
  std::string out;
  for (size_t i = 0; i < text.size(); i++) {
    if (text[i] == '%' && i + 2 < text.size()) {
      out.push_back(static_cast<char>(strtol(text.substr(i + 1, 2).c_str(), nullptr, 16)));
      i += 2;
    } else {
      out.push_back(text[i]);
    }
  }
  return out;
}

std::string QueryValue(const std::string& link, const std::string& key) {
  const size_t question = link.find('?');
  if (question == std::string::npos) return std::string();
  size_t at = question + 1;
  while (at <= link.size()) {
    size_t end = link.find('&', at);
    if (end == std::string::npos) end = link.size();
    const std::string pair = link.substr(at, end - at);
    const size_t eq = pair.find('=');
    if (eq != std::string::npos && PercentDecode(pair.substr(0, eq)) == key) {
      return PercentDecode(pair.substr(eq + 1));
    }
    at = end + 1;
  }
  return std::string();
}

const char kAlphabet[] = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_";

std::vector<unsigned char> Base64UrlDecode(const std::string& text) {
  std::vector<unsigned char> out;
  int buffer = 0;
  int bits = 0;
  for (char c : text) {
    if (c == '+') c = '-';
    if (c == '/') c = '_';
    if (c == '=') break;
    const char* at = strchr(kAlphabet, c);
    if (at == nullptr || c == '\0') return std::vector<unsigned char>();
    buffer = (buffer << 6) | static_cast<int>(at - kAlphabet);
    bits += 6;
    if (bits >= 8) {
      bits -= 8;
      out.push_back(static_cast<unsigned char>((buffer >> bits) & 0xff));
    }
  }
  return out;
}

std::string Base64UrlEncode(const unsigned char* data, size_t length) {
  std::string out;
  size_t i = 0;
  while (i + 2 < length) {
    const int n = (data[i] << 16) | (data[i + 1] << 8) | data[i + 2];
    out.push_back(kAlphabet[(n >> 18) & 63]);
    out.push_back(kAlphabet[(n >> 12) & 63]);
    out.push_back(kAlphabet[(n >> 6) & 63]);
    out.push_back(kAlphabet[n & 63]);
    i += 3;
  }
  if (length - i == 1) {
    const int n = data[i] << 16;
    out.push_back(kAlphabet[(n >> 18) & 63]);
    out.push_back(kAlphabet[(n >> 12) & 63]);
  } else if (length - i == 2) {
    const int n = (data[i] << 16) | (data[i + 1] << 8);
    out.push_back(kAlphabet[(n >> 18) & 63]);
    out.push_back(kAlphabet[(n >> 12) & 63]);
    out.push_back(kAlphabet[(n >> 6) & 63]);
  }
  return out;
}

// scheme://host:port/path, as far as the tunnel needs it.
struct Url {
  std::string scheme;
  std::string host;
  int port = 0;
  std::string path;
};

bool ParseUrl(const std::string& text, Url* url) {
  const size_t colon = text.find("://");
  if (colon == std::string::npos) return false;
  url->scheme = text.substr(0, colon);
  const size_t host_start = colon + 3;
  const size_t path_start = text.find('/', host_start);
  std::string authority = text.substr(host_start, path_start == std::string::npos
                                                      ? std::string::npos
                                                      : path_start - host_start);
  url->path = path_start == std::string::npos ? "/" : text.substr(path_start);
  const size_t port_colon = authority.rfind(':');
  if (port_colon != std::string::npos && authority.find(']', port_colon) == std::string::npos) {
    url->port = atoi(authority.substr(port_colon + 1).c_str());
    authority = authority.substr(0, port_colon);
  }
  if (!authority.empty() && authority.front() == '[' && authority.back() == ']') {
    authority = authority.substr(1, authority.size() - 2);
  }
  url->host = authority;
  return !url->host.empty();
}

std::wstring Wide(const std::string& text) {
  if (text.empty()) return std::wstring();
  const int size = MultiByteToWideChar(CP_UTF8, 0, text.data(), static_cast<int>(text.size()), nullptr, 0);
  std::wstring out(size, L'\0');
  MultiByteToWideChar(CP_UTF8, 0, text.data(), static_cast<int>(text.size()), &out[0], size);
  return out;
}

std::string Narrow(const wchar_t* text) {
  const int size = WideCharToMultiByte(CP_UTF8, 0, text, -1, nullptr, 0, nullptr, nullptr);
  if (size <= 1) return std::string();
  std::string out(size - 1, '\0');
  WideCharToMultiByte(CP_UTF8, 0, text, -1, &out[0], size, nullptr, nullptr);
  return out;
}

bool WinsockReady() {
  static bool ready = []() {
    WSADATA data;
    return WSAStartup(MAKEWORD(2, 2), &data) == 0;
  }();
  return ready;
}

// Whether [certificate]'s subject public key info is the P-256 key [pin],
// read by structure from the certificate the handshake presented.
bool CertificateHoldsKey(PCCERT_CONTEXT certificate, const std::vector<unsigned char>& pin) {
  static const BYTE kPrime256v1[] = {0x06, 0x08, 0x2a, 0x86, 0x48, 0xce, 0x3d, 0x03, 0x01, 0x07};
  if (certificate == nullptr || certificate->pCertInfo == nullptr) return false;
  const CERT_PUBLIC_KEY_INFO& info = certificate->pCertInfo->SubjectPublicKeyInfo;
  if (info.Algorithm.pszObjId == nullptr ||
      strcmp(info.Algorithm.pszObjId, szOID_ECC_PUBLIC_KEY) != 0) {
    return false;
  }
  if (info.Algorithm.Parameters.cbData != sizeof(kPrime256v1) ||
      memcmp(info.Algorithm.Parameters.pbData, kPrime256v1, sizeof(kPrime256v1)) != 0) {
    return false;
  }
  if (info.PublicKey.cbUnusedBits != 0 || info.PublicKey.cbData != pin.size()) return false;
  unsigned char difference = 0;
  for (size_t i = 0; i < pin.size(); i++) difference |= info.PublicKey.pbData[i] ^ pin[i];
  return difference == 0;
}

// -- a blocking connection, with or without TLS -------------------------------

class Connection {
 public:
  Connection() {
    SecInvalidateHandle(&credentials_);
    SecInvalidateHandle(&context_);
  }

  ~Connection() {
    Close();
    if (SecIsValidHandle(&context_)) DeleteSecurityContext(&context_);
    if (SecIsValidHandle(&credentials_)) FreeCredentialsHandle(&credentials_);
  }

  // Empty when connected; why not otherwise. With [pin], over TLS trusting
  // only a certificate for that key, and [pin_refused] set when that is why.
  std::string Open(const std::string& host, int port, const std::vector<unsigned char>* pin,
                   bool* pin_refused) {
    if (!WinsockReady()) return "Winsock did not start";
    addrinfo hints = {};
    hints.ai_family = AF_UNSPEC;
    hints.ai_socktype = SOCK_STREAM;
    hints.ai_protocol = IPPROTO_TCP;
    addrinfo* found = nullptr;
    if (getaddrinfo(host.c_str(), std::to_string(port).c_str(), &hints, &found) != 0) {
      return "could not resolve " + host;
    }
    for (addrinfo* at = found; at != nullptr; at = at->ai_next) {
      SOCKET s = socket(at->ai_family, at->ai_socktype, at->ai_protocol);
      if (s == INVALID_SOCKET) continue;
      if (connect(s, at->ai_addr, static_cast<int>(at->ai_addrlen)) == 0) {
        socket_ = s;
        break;
      }
      closesocket(s);
    }
    freeaddrinfo(found);
    if (socket_ == INVALID_SOCKET) return "could not connect to " + host;
    if (pin == nullptr) return std::string();
    return Handshake(host, *pin, pin_refused);
  }

  bool Write(const std::string& data) { return Write(data.data(), data.size()); }

  bool Write(const char* data, size_t size) {
    if (socket_ == INVALID_SOCKET) return false;
    if (!tls_) return SendAll(data, size);
    while (size > 0) {
      const size_t n = std::min<size_t>(size, sizes_.cbMaximumMessage);
      std::vector<char> message(sizes_.cbHeader + n + sizes_.cbTrailer);
      memcpy(&message[sizes_.cbHeader], data, n);
      SecBuffer buffers[4] = {
          {sizes_.cbHeader, SECBUFFER_STREAM_HEADER, message.data()},
          {static_cast<unsigned long>(n), SECBUFFER_DATA, message.data() + sizes_.cbHeader},
          {sizes_.cbTrailer, SECBUFFER_STREAM_TRAILER, message.data() + sizes_.cbHeader + n},
          {0, SECBUFFER_EMPTY, nullptr},
      };
      SecBufferDesc description = {SECBUFFER_VERSION, 4, buffers};
      if (EncryptMessage(&context_, 0, &description, 0) != SEC_E_OK) return false;
      if (!SendAll(message.data(),
                   buffers[0].cbBuffer + buffers[1].cbBuffer + buffers[2].cbBuffer)) {
        return false;
      }
      data += n;
      size -= n;
    }
    return true;
  }

  // Bytes read into [buffer]; 0 at the end of the stream or on an error.
  size_t Read(char* buffer, size_t size) {
    if (plain_.empty() && !Fill()) return 0;
    const size_t n = std::min(size, plain_.size());
    memcpy(buffer, plain_.data(), n);
    plain_.erase(plain_.begin(), plain_.begin() + n);
    return n;
  }

  bool ReadLine(std::string* line) {
    while (true) {
      const auto newline = std::find(plain_.begin(), plain_.end(), '\n');
      if (newline != plain_.end()) {
        std::string text(plain_.begin(), newline);
        if (!text.empty() && text.back() == '\r') text.pop_back();
        plain_.erase(plain_.begin(), newline + 1);
        *line = text;
        return true;
      }
      if (plain_.size() > 65536 || !Fill()) return false;
    }
  }

  void Close() {
    SOCKET s = socket_;
    socket_ = INVALID_SOCKET;
    if (s != INVALID_SOCKET) {
      shutdown(s, SD_BOTH);
      closesocket(s);
    }
  }

 private:
  bool SendAll(const char* data, size_t size) {
    while (size > 0) {
      const int sent = send(socket_, data, static_cast<int>(std::min<size_t>(size, 1 << 20)), 0);
      if (sent <= 0) return false;
      data += sent;
      size -= static_cast<size_t>(sent);
    }
    return true;
  }

  bool Receive() {
    char chunk[16384];
    const int n = recv(socket_, chunk, sizeof(chunk), 0);
    if (n <= 0) return false;
    encrypted_.insert(encrypted_.end(), chunk, chunk + n);
    return true;
  }

  std::string Handshake(const std::string& host, const std::vector<unsigned char>& pin,
                        bool* pin_refused) {
    SCHANNEL_CRED settings = {};
    settings.dwVersion = SCHANNEL_CRED_VERSION;
    settings.grbitEnabledProtocols = SP_PROT_TLS1_2_CLIENT;
    // Windows' own chain validation is off: the pin below is the only thing
    // that decides whether this server is trusted.
    settings.dwFlags = SCH_CRED_MANUAL_CRED_VALIDATION | SCH_CRED_NO_DEFAULT_CREDS;
    if (AcquireCredentialsHandleW(nullptr, const_cast<LPWSTR>(UNISP_NAME_W), SECPKG_CRED_OUTBOUND,
                                  nullptr, &settings, nullptr, nullptr, &credentials_,
                                  nullptr) != SEC_E_OK) {
      return "Schannel credentials could not be acquired";
    }
    const DWORD flags = ISC_REQ_SEQUENCE_DETECT | ISC_REQ_REPLAY_DETECT | ISC_REQ_CONFIDENTIALITY |
                        ISC_REQ_ALLOCATE_MEMORY | ISC_REQ_STREAM | ISC_REQ_MANUAL_CRED_VALIDATION;
    std::wstring target = Wide(host);
    DWORD out_flags = 0;
    bool first = true;
    while (true) {
      SecBuffer in_buffers[2] = {
          {static_cast<unsigned long>(encrypted_.size()), SECBUFFER_TOKEN,
           encrypted_.empty() ? nullptr : encrypted_.data()},
          {0, SECBUFFER_EMPTY, nullptr},
      };
      SecBufferDesc in_description = {SECBUFFER_VERSION, 2, in_buffers};
      SecBuffer out_buffer = {0, SECBUFFER_TOKEN, nullptr};
      SecBufferDesc out_description = {SECBUFFER_VERSION, 1, &out_buffer};
      const SECURITY_STATUS status = InitializeSecurityContextW(
          &credentials_, first ? nullptr : &context_, &target[0], flags, 0, 0,
          first ? nullptr : &in_description, 0, first ? &context_ : nullptr, &out_description,
          &out_flags, nullptr);
      first = false;
      if (out_buffer.pvBuffer != nullptr) {
        const bool sent = out_buffer.cbBuffer == 0 ||
                          SendAll(static_cast<const char*>(out_buffer.pvBuffer), out_buffer.cbBuffer);
        FreeContextBuffer(out_buffer.pvBuffer);
        if (!sent) return "the dev server closed the connection during the handshake";
      }
      if (status == SEC_E_INCOMPLETE_MESSAGE) {
        if (!Receive()) return "the dev server closed the connection during the handshake";
        continue;
      }
      if (status == SEC_E_OK || status == SEC_I_CONTINUE_NEEDED) {
        if (in_buffers[1].BufferType == SECBUFFER_EXTRA) {
          encrypted_.erase(encrypted_.begin(), encrypted_.end() - in_buffers[1].cbBuffer);
        } else {
          encrypted_.clear();
        }
      }
      if (status == SEC_E_OK) break;
      if (status != SEC_I_CONTINUE_NEEDED) {
        char text[64];
        snprintf(text, sizeof(text), "the TLS handshake failed (0x%08lx)",
                 static_cast<unsigned long>(status));
        return text;
      }
      if (encrypted_.empty() && !Receive()) {
        return "the dev server closed the connection during the handshake";
      }
    }
    PCCERT_CONTEXT certificate = nullptr;
    if (QueryContextAttributesW(&context_, SECPKG_ATTR_REMOTE_CERT_CONTEXT, &certificate) != SEC_E_OK) {
      *pin_refused = true;
      return "the dev server presented no certificate";
    }
    const bool trusted = CertificateHoldsKey(certificate, pin);
    CertFreeCertificateContext(certificate);
    if (!trusted) {
      *pin_refused = true;
      return "not the key this device was paired with";
    }
    if (QueryContextAttributesW(&context_, SECPKG_ATTR_STREAM_SIZES, &sizes_) != SEC_E_OK) {
      return "the TLS stream sizes could not be read";
    }
    tls_ = true;
    return std::string();
  }

  // More plaintext into plain_; false at the end of the stream.
  bool Fill() {
    if (socket_ == INVALID_SOCKET) return false;
    if (!tls_) {
      char chunk[16384];
      const int n = recv(socket_, chunk, sizeof(chunk), 0);
      if (n <= 0) return false;
      plain_.insert(plain_.end(), chunk, chunk + n);
      return true;
    }
    while (true) {
      if (!encrypted_.empty()) {
        SecBuffer buffers[4] = {
            {static_cast<unsigned long>(encrypted_.size()), SECBUFFER_DATA, encrypted_.data()},
            {0, SECBUFFER_EMPTY, nullptr},
            {0, SECBUFFER_EMPTY, nullptr},
            {0, SECBUFFER_EMPTY, nullptr},
        };
        SecBufferDesc description = {SECBUFFER_VERSION, 4, buffers};
        const SECURITY_STATUS status = DecryptMessage(&context_, &description, 0, nullptr);
        if (status == SEC_E_OK) {
          std::vector<char> extra;
          for (SecBuffer& b : buffers) {
            if (b.BufferType == SECBUFFER_DATA && b.cbBuffer > 0) {
              const char* p = static_cast<const char*>(b.pvBuffer);
              plain_.insert(plain_.end(), p, p + b.cbBuffer);
            } else if (b.BufferType == SECBUFFER_EXTRA && b.cbBuffer > 0) {
              const char* p = static_cast<const char*>(b.pvBuffer);
              extra.assign(p, p + b.cbBuffer);
            }
          }
          encrypted_.swap(extra);
          if (!plain_.empty()) return true;
          continue;
        }
        if (status != SEC_E_INCOMPLETE_MESSAGE) return false;
      }
      if (!Receive()) return false;
    }
  }

  SOCKET socket_ = INVALID_SOCKET;
  CredHandle credentials_;
  CtxtHandle context_;
  SecPkgContext_StreamSizes sizes_ = {};
  bool tls_ = false;
  std::vector<char> encrypted_;
  std::vector<char> plain_;
};

// -- the tunnel --------------------------------------------------------------

class Tunnel : public std::enable_shared_from_this<Tunnel> {
 public:
  static std::shared_ptr<Tunnel> FromLink(const std::string& link, const std::string& vm_service,
                                          std::string* error) {
    if (!IsPairLink(link)) {
      *error = "not a pairing link";
      return nullptr;
    }
    const std::string server = QueryValue(link, "server");
    const std::string token = QueryValue(link, "token");
    const std::vector<unsigned char> key = Base64UrlDecode(QueryValue(link, "key"));
    if (server.empty() || token.empty() || key.empty()) {
      *error = "the link names no server, token or key";
      return nullptr;
    }
    if (key.size() != 65 || key[0] != 0x04) {
      *error = "the link's key is not a P-256 point";
      return nullptr;
    }
    Url server_url;
    if (!ParseUrl(server, &server_url) || server_url.scheme != "https") {
      *error = "the link names a dev server that is not https; pass the link a current dartvel dev prints";
      return nullptr;
    }
    Url vm;
    if (!ParseUrl(vm_service, &vm) || vm.port <= 0) {
      *error = "the VM service URI has no port";
      return nullptr;
    }
    std::shared_ptr<Tunnel> tunnel(new Tunnel());
    tunnel->host_ = server_url.host;
    tunnel->port_ = server_url.port > 0 ? server_url.port : 443;
    tunnel->token_ = token;
    tunnel->key_ = key;
    tunnel->vm_port_ = vm.port;
    tunnel->vm_path_ = vm.path.empty() ? "/" : vm.path;
    if (tunnel->vm_path_.back() != '/') tunnel->vm_path_.push_back('/');
    return tunnel;
  }

  const std::string& host() const { return host_; }

  void Start() {
    std::shared_ptr<Tunnel> self = shared_from_this();
    std::thread([self]() { self->Run(); }).detach();
  }

 private:
  Tunnel() = default;

  std::string Server() const { return host_ + ":" + std::to_string(port_); }

  void Run() {
    int attempt = 0;
    while (true) {
      attempt++;
      SetStatus("connecting to " + Server());
      std::string refused;
      const std::string failure = RunControl(&refused);
      if (!refused.empty()) {
        SetStatus(refused);
        return;
      }
      if (failure.empty()) {
        SetStatus("the dev server at " + Server() + " disconnected");
        attempt = 0;
      } else {
        SetStatus("could not reach the dev server at " + Server() + ": " + failure);
      }
      std::this_thread::sleep_for(std::chrono::seconds(std::max(1, std::min(10, attempt))));
    }
  }

  std::unique_ptr<Connection> Open(const std::string& query, std::string* failure,
                                   std::string* refused) {
    unsigned char random[32];
    if (!BCRYPT_SUCCESS(BCryptGenRandom(nullptr, random, sizeof(random),
                                        BCRYPT_USE_SYSTEM_PREFERRED_RNG))) {
      *failure = "no random bytes for the nonce";
      return nullptr;
    }
    const std::string nonce = Base64UrlEncode(random, sizeof(random));
    std::unique_ptr<Connection> connection(new Connection());
    bool pin_refused = false;
    const std::string error = connection->Open(host_, port_, &key_, &pin_refused);
    if (!error.empty()) {
      if (pin_refused) {
        *refused = "the server at " + Server() +
                   " did not present the key this device was paired with, so nothing was sent to it.";
      } else {
        *failure = error;
      }
      return nullptr;
    }
    const std::string request = std::string("GET ") + kPath + "?" + query + "&nonce=" + nonce +
                                " HTTP/1.1\r\nHost: " + Server() + "\r\nAuthorization: Bearer " +
                                token_ + "\r\nConnection: Upgrade\r\nUpgrade: " + kProtocol +
                                "\r\n\r\n";
    if (!connection->Write(request)) {
      *failure = "the dev server closed the connection";
      return nullptr;
    }
    std::string status;
    if (!connection->ReadLine(&status)) {
      *failure = "the dev server closed the connection";
      return nullptr;
    }
    std::string header;
    while (connection->ReadLine(&header) && !header.empty()) {
    }
    const size_t space = status.find(' ');
    const int code = space == std::string::npos ? 0 : atoi(status.c_str() + space + 1);
    if (code == 401) {
      *refused = "the dev server at " + Server() +
                 " refused this device. Its pairing ends when dartvel dev restarts; pass the new link.";
      return nullptr;
    }
    if (code != 101) {
      *failure = "the dev server answered HTTP " + std::to_string(code);
      return nullptr;
    }
    return connection;
  }

  std::string RunControl(std::string* refused) {
    std::string failure;
    std::unique_ptr<Connection> control = Open("role=control", &failure, refused);
    if (control == nullptr) return failure;
    control->Write(std::string("{\"vmService\":\"") + vm_path_ + "\",\"manifest\":" + kManifest +
                   "}\n");
    SetStatus("paired with " + Server() + std::string(kMarker).substr(0, 0));
    std::string line;
    std::shared_ptr<Tunnel> self = shared_from_this();
    while (control->ReadLine(&line)) {
      if (line.compare(0, 5, "open ") == 0) {
        const std::string id = line.substr(5);
        std::thread([self, id]() { self->Stream(id); }).detach();
      } else if (line.compare(0, 8, "refused ") == 0) {
        *refused = "the dev server refused this build: " + line.substr(8);
        break;
      }
    }
    return std::string();
  }

  void Stream(const std::string& id) {
    std::string failure;
    std::string refused;
    std::shared_ptr<Connection> up(Open("role=stream&id=" + id, &failure, &refused).release());
    if (up == nullptr) {
      SetStatus("a stream to the VM service failed: " + (failure.empty() ? refused : failure));
      return;
    }
    std::shared_ptr<Connection> vm(new Connection());
    bool unused = false;
    const std::string error = vm->Open("127.0.0.1", vm_port_, nullptr, &unused);
    if (!error.empty()) {
      SetStatus("a stream to the VM service failed: " + error);
      return;
    }
    std::thread([up, vm]() { Pipe(vm.get(), up.get()); }).detach();
    Pipe(up.get(), vm.get());
  }

  static void Pipe(Connection* from, Connection* to) {
    char buffer[16384];
    size_t n;
    while ((n = from->Read(buffer, sizeof(buffer))) > 0) {
      if (!to->Write(buffer, n)) break;
    }
    from->Close();
    to->Close();
  }

  std::string host_;
  int port_ = 443;
  std::string token_;
  std::vector<unsigned char> key_;
  int vm_port_ = 0;
  std::string vm_path_;
};

std::recursive_mutex& Lock() {
  static std::recursive_mutex lock;
  return lock;
}

std::string& VmService() {
  static std::string uri;
  return uri;
}

std::string& Link() {
  static std::string link;
  return link;
}

std::shared_ptr<Tunnel>& CurrentTunnel() {
  static std::shared_ptr<Tunnel> tunnel;
  return tunnel;
}

// The pairing link the process was launched with, or empty.
std::string LaunchLink() {
  int count = 0;
  LPWSTR* arguments = CommandLineToArgvW(GetCommandLineW(), &count);
  std::string link;
  if (arguments == nullptr) return link;
  for (int i = 1; i < count; i++) {
    const std::string argument = Narrow(arguments[i]);
    if (IsPairLink(argument)) link = argument;
  }
  LocalFree(arguments);
  return link;
}

}  // namespace

extern "C" {

// Called from Dart with this app's VM service URI. Returns the status, in a
// buffer this file owns.
__declspec(dllexport) const char* @@VM_SERVICE@@(const char* uri) {
  std::lock_guard<std::recursive_mutex> guard(Lock());
  // The first URI this process reported: a restarted isolate can report the
  // dev machine's DDS address instead of this app's own service.
  if (VmService().empty() && uri != nullptr) VmService() = uri;
  if (Link().empty()) Link() = LaunchLink();
  if (!Link().empty() && !VmService().empty() && CurrentTunnel() == nullptr) {
    std::string error;
    std::shared_ptr<Tunnel> tunnel = Tunnel::FromLink(Link(), VmService(), &error);
    if (tunnel == nullptr) {
      SetStatus("the pairing link could not be used: " + error);
    } else {
      CurrentTunnel() = tunnel;
      tunnel->Start();
    }
  }
  static char status[2048];
  std::lock_guard<std::mutex> status_guard(StatusLock());
  strncpy_s(status, sizeof(status), StatusText().c_str(), _TRUNCATE);
  return status;
}

// The dev server's host, for reaching the backend it runs beside; NULL
// before a tunnel starts.
__declspec(dllexport) const char* @@SERVER_HOST@@(void) {
  std::lock_guard<std::recursive_mutex> guard(Lock());
  if (CurrentTunnel() == nullptr) return nullptr;
  static char host[512];
  strncpy_s(host, sizeof(host), CurrentTunnel()->host().c_str(), _TRUNCATE);
  return host;
}

}  // extern "C"

#endif  // _DEBUG
''';
