// Nothing was watching for an advisory against a package this repository
// pins.
//
// The secure-development policy listed that as a gap and the compliance plan
// ranked it second, so here is the check: every tracked pubspec.lock, every
// hosted package in it, asked of OSV in one batch.
//
// The failure modes worth testing are the quiet ones. A lock file whose git
// and path and SDK entries are read as pub.dev packages asks about names that
// do not exist there, gets an empty answer for each, and reports a clean run
// over packages it never checked. A batch response read out of order attaches
// somebody else's advisory to a package — or, worse, drops a real one.
import 'package:test/test.dart';

import '../../tool/ci/dependency_advisories.dart';

const String _lock = '''
# Generated by pub
packages:
  archive:
    dependency: transitive
    description:
      name: archive
      sha256: "a96e"
      url: "https://pub.dev"
    source: hosted
    version: "4.0.9"
  dartvel_core:
    dependency: "direct main"
    description:
      path: "../dartvel_core"
      relative: true
    source: path
    version: "0.5.0"
  flutter:
    dependency: "direct main"
    description: flutter
    source: sdk
    version: "0.0.0"
  some_fork:
    dependency: "direct main"
    description:
      path: "."
      ref: main
      resolved-ref: "abc"
      url: "https://github.com/example/some_fork"
    source: git
    version: "1.0.0"
sdks:
  dart: ">=3.12.0 <4.0.0"
''';

void main() {
  group('reading a lock file', () {
    test('a hosted package, with the version that is pinned', () {
      expect(dvLockedPackages(_lock), <String, String>{'archive': '4.0.9'});
    });

    test('what OSV has never heard of is left out', () {
      // A path, a git fork and the SDK itself. Asking pub.dev about them
      // returns nothing, which reads exactly like a clean answer -- so this
      // is the difference between checking a dependency and believing it was
      // checked.
      final Map<String, String> found = dvLockedPackages(_lock);
      expect(found.keys, isNot(contains('dartvel_core')));
      expect(found.keys, isNot(contains('flutter')));
      expect(found.keys, isNot(contains('some_fork')));
    });

    test('a lock file with nothing hosted in it', () {
      expect(dvLockedPackages('packages:\nsdks:\n  dart: ">=3.12.0 <4.0.0"\n'),
          isEmpty);
    });
  });

  group('the query', () {
    test('one entry per package, in the Pub ecosystem', () {
      final String body =
          dvOsvQuery(<String, String>{'archive': '4.0.9', 'http': '1.6.0'});
      expect(body, contains('"ecosystem":"Pub"'));
      expect(body, contains('"name":"archive"'));
      expect(body, contains('"version":"4.0.9"'));
      expect(body, contains('"name":"http"'));
    });

    test('the order the names were given is the order asked', () {
      // OSV answers a batch positionally: results[0] belongs to queries[0].
      // Sorting one side and not the other is how an advisory ends up
      // reported against the wrong package.
      expect(dvOsvNames(<String, String>{'b': '1.0.0', 'a': '2.0.0'}),
          <String>['a', 'b']);
      expect(dvOsvQuery(<String, String>{'b': '1.0.0', 'a': '2.0.0'}).indexOf('"a"'),
          lessThan(
              dvOsvQuery(<String, String>{'b': '1.0.0', 'a': '2.0.0'}).indexOf('"b"')));
    });
  });

  group('reading the answer', () {
    const String response = '''
{"results":[{},{"vulns":[{"id":"GHSA-xxxx-yyyy","modified":"2026-01-01"}]},{}]}
''';

    test('a package with an advisory, named with its id', () {
      final List<DVAdvisory> found = dvOsvFindings(
        response,
        <String>['a', 'b', 'c'],
        <String, String>{'a': '1.0.0', 'b': '2.0.0', 'c': '3.0.0'},
      );
      expect(found, hasLength(1));
      expect(found.single.package, 'b');
      expect(found.single.version, '2.0.0');
      expect(found.single.ids, <String>['GHSA-xxxx-yyyy']);
    });

    test('a clean batch finds nothing', () {
      expect(
        dvOsvFindings('{"results":[{},{},{}]}', <String>['a', 'b', 'c'],
            <String, String>{'a': '1', 'b': '2', 'c': '3'}),
        isEmpty,
      );
    });

    test('an answer of the wrong length is refused, not half-read', () {
      // A truncated batch would otherwise report the packages it did cover
      // as clean and say nothing about the rest.
      expect(
        () => dvOsvFindings('{"results":[{}]}', <String>['a', 'b'],
            <String, String>{'a': '1', 'b': '2'}),
        throwsA(isA<FormatException>()),
      );
    });

    test('a body that is not the answer at all', () {
      expect(
        () => dvOsvFindings('<html>502</html>', <String>['a'],
            <String, String>{'a': '1'}),
        throwsA(isA<FormatException>()),
      );
    });
  });

  group('this repository', () {
    test('every lock file resolution left is read, and names packages', () {
      // Lock files are gitignored, so they exist only once something has
      // resolved. That is what the check's first CI run found out the hard
      // way -- it read nothing and would have reported a clean scan if it
      // had not refused an empty set outright.
      final Map<String, Map<String, String>> byFile = dvRepositoryPackages();
      expect(byFile, isNotEmpty,
          reason: 'no pubspec.lock anywhere: run `flutter pub get` first, '
              'which is what the workflow does before the check');
      expect(byFile.keys, contains('pubspec.lock'));
      expect(byFile.values.expand((Map<String, String> p) => p.keys),
          contains('args'));
    });
  });
}
